In [1]:
import os
os.chdir('../../../../..')

In [2]:
import numpy as np

from sklearn.cluster import AgglomerativeClustering, SpectralClustering, DBSCAN
from kmedoids import KMedoids

from src.datasets import QM9Dataset
from src.helper_functions import plot_molecules_with_py3dmol, create_chemiscope_viewer, plot_distance_matrix_projection, evaluate_distance_matrix_clustering_sweep, average_numeric_by_cluster

In [ ]:
qm9 = QM9Dataset(limit=5000, sampling_strategy="stratified", stratify_by=["num_atoms", "gap"], add_acsf=True)
df = qm9.load()
molecules = qm9.get_molecules()

2026-04-15 15:48:55.359 | INFO     | src.datasets:load:493 - Loading cached full QM9 dataset from: data/QM9/dataset_cleaned.parquet
2026-04-15 15:48:55.707 | INFO     | src.datasets:_sample_qm9_df:685 - QM9 sampling complete: strategy=stratified, requested_limit=5500, returned_rows=5500.
2026-04-15 15:48:55.708 | INFO     | src.datasets:_add_requested_descriptors:126 - Applying requested QM9 descriptors to sampled dataframe (rows=5500).
2026-04-15 15:48:55.708 | INFO     | src.features:compute_acsf:193 - Computing ACSF (rcut=6.0)...
2026-04-15 15:49:36.426 | SUCCESS  | src.datasets:add_acsf:850 - Added ACSF embeddings.
2026-04-15 15:49:36.427 | INFO     | src.datasets:_add_requested_descriptors:149 - Added descriptor column(s): ['acsf_embedding']
2026-04-15 15:49:36.439 | INFO     | src.datasets:_drop_rows_with_null_required_descriptors:578 - Dropped QM9 rows with null/empty descriptor vectors: dropped=23, remaining=5477, descriptor_cols=['acsf_embedding'].
2026-04-15 15:49:36.440 | INFO     | src.datasets:load:527 - QM9 descriptor null-filtering complete: attempts=1, requested_limit=5000, returned_rows=5000.
2026-04-15 15:49:58.619 | SUCCESS  | src.datasets:get_molecules:1168 - Saved 5000 molecules to data/QM9/qm9_subset.xyz (failed: 0, requested: 5000).
2026-04-15 15:49:58.620 | INFO     | src.datasets:load:493 - Loading cached full QM9 dataset from: data/QM9/dataset_cleaned.parquet
2026-04-15 15:49:58.809 | INFO     | src.datasets:_sample_qm9_df:685 - QM9 sampling complete: strategy=stratified, requested_limit=5500, returned_rows=5500.
2026-04-15 15:49:58.809 | INFO     | src.datasets:_add_requested_descriptors:126 - Applying requested QM9 descriptors to sampled dataframe (rows=5500).
2026-04-15 15:49:58.810 | INFO     | src.features:compute_acsf:193 - Computing ACSF (rcut=6.0)...
2026-04-15 15:50:40.077 | SUCCESS  | src.datasets:add_acsf:850 - Added ACSF embeddings.
2026-04-15 15:50:40.078 | INFO     | src.datasets:_add_requested_descriptors:149 - Added descriptor column(s): ['acsf_embedding']
2026-04-15 15:50:40.090 | INFO     | src.datasets:_drop_rows_with_null_required_descriptors:578 - Dropped QM9 rows with null/empty descriptor vectors: dropped=23, remaining=5477, descriptor_cols=['acsf_embedding'].
2026-04-15 15:50:40.091 | INFO     | src.datasets:load:527 - QM9 descriptor null-filtering complete: attempts=1, requested_limit=5000, returned_rows=5000.

In [7]:
len(molecules[0:2])

2

In [8]:
plot_molecules_with_py3dmol(molecules[0:3])

In [10]:
dist_matrix = qm9.get_distance_matrix(
    descriptor="acsf",
    dist_type="euclidean",
)

2026-04-15 15:50:59.442 | INFO     | src.distance:_compute_and_save:34 - Computing euclidean distance matrix...
2026-04-15 15:50:59.898 | SUCCESS  | src.distance:_compute_and_save:79 - Saved distance matrix to data/QM9/dist_acsf_euclidean.npy

# Determining the best number of clusters for each clustering method

In [11]:
out = evaluate_distance_matrix_clustering_sweep(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    dataset_name="qm9",
)

Evaluation k:   0%|          | 0/19 [00:02<?, ?it/s]

KeyboardInterrupt:

In [12]:
# find the n molecules that are not on the diagonal with the smallest distance
n = 10
# Get the indices of the upper triangle (excluding diagonal)
triu_indices = np.triu_indices_from(dist_matrix, k=1)
# Get the distances and corresponding molecule pairs
distances = dist_matrix[triu_indices]
molecule_pairs = list(zip(triu_indices[0], triu_indices[1]))
# Get the indices of the n smallest distances
smallest_indices = np.argsort(distances)[:n]
# Get the corresponding molecule pairs for the n smallest distances
closest_pairs = [molecule_pairs[i] for i in smallest_indices]
print("Closest molecule pairs (indices):", closest_pairs)
mols = [(molecules[idx1], molecules[idx2]) for idx1, idx2 in closest_pairs]

Closest molecule pairs (indices): [(np.int64(1332), np.int64(1333)), (np.int64(1429), np.int64(1430)), (np.int64(3300), np.int64(3313)), (np.int64(4398), np.int64(4418)), (np.int64(2814), np.int64(2845)), (np.int64(3389), np.int64(3698)), (np.int64(3621), np.int64(3622)), (np.int64(3674), np.int64(3675)), (np.int64(4183), np.int64(4188)), (np.int64(1473), np.int64(1488))]

In [13]:
print(mols[0])

(Atoms(symbols='H3CH3NHOCNCNC2', pbc=False, initial_charges=..., mass=..., partial_charge=...), Atoms(symbols='H3CH3NHOCNCNC2', pbc=False, initial_charges=..., mass=..., partial_charge=...))

In [14]:
plot_molecules_with_py3dmol(mols[1])

# Hiercical Clustering on Distance Matrix

In [16]:
model_hier = AgglomerativeClustering(metric='precomputed', n_clusters=3, linkage='complete')
labels_hier = model_hier.fit_predict(dist_matrix)
df = df.with_columns(labels_hier=labels_hier)

In [17]:
create_chemiscope_viewer(df, dist_matrix, labels_hier, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [18]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_hier,
    clustering_method="hierarchical"
)

2026-04-15 15:52:10.435 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_hierarchical_projection.png

{'coords': array([[-42.87330632,  26.97616543],
        [ 72.57577087,   0.38978408],
        [ 99.66756854,  32.53057816],
        ...,
        [-33.04061161,  41.09393408],
        [-45.10445665,  39.92296242],
        [-31.10718847, -25.59146542]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_hierarchical_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'hierarchical'}

In [19]:
average_numeric_by_cluster(df, "labels_hier")

shape: (3, 59)
┌────────────┬───────┬────────────┬───────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ labels_hie ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ C        ┆ pct_alipha ┆ pct_aromat ┆ pct_acycl │
│ r          ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ---      ┆ tic_ring   ┆ ic         ┆ ic        │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ f64      ┆ ---        ┆ ---        ┆ ---       │
│ i64        ┆       ┆ f64        ┆           ┆   ┆          ┆ f64        ┆ f64        ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 0          ┆ 814   ┆ 1.851738   ┆ 14.45086  ┆ … ┆ 1.095235 ┆ 36.117936  ┆ 47.542998  ┆ 16.339066 │
│ 1          ┆ 3150  ┆ 2.12       ┆ 18.238413 ┆ … ┆ 1.116646 ┆ 83.650794  ┆ 5.079365   ┆ 11.269841 │
│ 2          ┆ 1036  ┆ 2.231232   ┆ 21.206564 ┆ … ┆ 1.197572 ┆ 94.401544  ┆ 0.289575   ┆ 5.30888   │
└────────────┴───────┴────────────┴───────────┴───┴──────────┴────────────┴────────────┴───────────┘

# KMedoids

In [20]:
model_km = KMedoids(n_clusters=3, metric="precomputed")
labels_km = model_km.fit_predict(dist_matrix)
df = df.with_columns(labels_km=labels_km)

In [21]:
create_chemiscope_viewer(df, dist_matrix, labels_km, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [22]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_km,
    clustering_method="kmedoids"
)

2026-04-15 15:52:46.900 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_kmedoids_projection.png

{'coords': array([[-42.87330632,  26.97616543],
        [ 72.57577087,   0.38978408],
        [ 99.66756854,  32.53057816],
        ...,
        [-33.04061161,  41.09393408],
        [-45.10445665,  39.92296242],
        [-31.10718847, -25.59146542]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_kmedoids_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'kmedoids'}

In [23]:
average_numeric_by_cluster(df, "labels_km")

shape: (3, 60)
┌───────────┬───────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ labels_km ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_hie ┆ pct_alipha ┆ pct_aroma ┆ pct_acycl │
│ ---       ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ r          ┆ tic_ring   ┆ tic       ┆ ic        │
│ u64       ┆ u32   ┆ ---        ┆ f64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆       ┆ f64        ┆           ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞═══════════╪═══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0         ┆ 1872  ┆ 2.22956    ┆ 20.729167 ┆ … ┆ 1.525107   ┆ 91.933761  ┆ 0.42735   ┆ 7.638889  │
│ 1         ┆ 2046  ┆ 2.096535   ┆ 17.686217 ┆ … ┆ 1.013685   ┆ 86.950147  ┆ 3.225806  ┆ 9.824047  │
│ 2         ┆ 1082  ┆ 1.879505   ┆ 14.965804 ┆ … ┆ 0.270795   ┆ 37.615527  ┆ 43.992606 ┆ 18.391867 │
└───────────┴───────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

# Spectral

In [ ]:
model_spectral = SpectralClustering(
                n_clusters=6,
                affinity="precomputed",
                assign_labels='kmeans',
                random_state=42,
            )

labels_spectral = model_spectral.fit_predict(dist_matrix)
df = df.with_columns(labels_spectral=labels_spectral)

In [ ]:
create_chemiscope_viewer(df, dist_matrix, labels_spectral, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [ ]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_spectral,
    clustering_method="spectral"
)

2026-04-15 08:37:08.191 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_spectral_projection.png

{'coords': array([[-42.873386 ,  26.976103 ],
        [ 72.57561  ,   0.3898516],
        [ 99.66764  ,  32.530502 ],
        ...,
        [-33.040558 ,  41.093994 ],
        [-45.104256 ,  39.92297  ],
        [-31.107193 , -25.591467 ]], shape=(5000, 2), dtype=float32),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_spectral_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'spectral'}

In [ ]:
average_numeric_by_cluster(df, "labels_spectral")

Hierarchical Clustering
shape: (6, 57)
┌─────────────────┬───────┬───────────┬────────────┬──────────┬───────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬──────────┬───────────┬───────────┬───────────┬──────────┬─────────────┬──────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────┬────────────┬────────────┬────────────┬────────────┬──────────┬──────────┬──────────┬─────────────┬───────────┐
│ labels_spectral ┆ count ┆ num_atoms ┆ mol_weight ┆ logp     ┆ tpsa      ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu       ┆ alpha     ┆ homo      ┆ lumo      ┆ gap      ┆ r2          ┆ zpve     ┆ u0            ┆ u             ┆ h             ┆ g             ┆ cv        ┆ u0_atom    ┆ u_atom     ┆ h_atom     ┆ g_atom     ┆ A        ┆ B        ┆ C        ┆ labels_hier ┆ labels_km │
│ ---             ┆ ---   ┆ ---       ┆ ---        ┆ ---      ┆ ---       ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---      ┆ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---         ┆ ---      ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---      ┆ ---      ┆ ---      ┆ ---         ┆ ---       │
│ i32             ┆ u32   ┆ f64       ┆ f64        ┆ f64      ┆ f64       ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64      ┆ f64       ┆ f64       ┆ f64       ┆ f64      ┆ f64         ┆ f64      ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64       ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64      ┆ f64      ┆ f64      ┆ f64         ┆ f64       │
╞═════════════════╪═══════╪═══════════╪════════════╪══════════╪═══════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪══════════╪═══════════╪═══════════╪═══════════╪══════════╪═════════════╪══════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════╪════════════╪════════════╪════════════╪════════════╪══════════╪══════════╪══════════╪═════════════╪═══════════╡
│ 0               ┆ 4995  ┆ 18.236637 ┆ 122.572573 ┆ 0.085085 ┆ 35.715916 ┆ 0.875572          ┆ 12.835568           ┆ 8.768168        ┆ 1.673273  ┆ 0.114915           ┆ 2.061841     ┆ 2.318519            ┆ 0.068723      ┆ 0.200393      ┆ 0.730885      ┆ 0.913714      ┆ 1.953353         ┆ 6.536737        ┆ 0.449249       ┆ 1.160761        ┆ 4.813213        ┆ 6.337738          ┆ 38.563764       ┆ 1.262149        ┆ 0.001401   ┆ 0.363564   ┆ 0.024024  ┆ 0.136136 ┆ 0.125726 ┆ 0.001602           ┆ 0.041241 ┆ 0.128328  ┆ 0.561361 ┆ 0.0002   ┆ 2.344945   ┆ 2.632916 ┆ 75.379197 ┆ -6.539705 ┆ 0.376228  ┆ 6.915932 ┆ 1185.694292 ┆ 4.124279 ┆ -11113.683143 ┆ -11113.450572 ┆ -11113.424879 ┆ -11114.593643 ┆ 31.880968 ┆ -76.854738 ┆ -77.325034 ┆ -77.768053 ┆ -71.521835 ┆ 3.380604 ┆ 1.402963 ┆ 1.129736 ┆ 2.693694    ┆ 0.562162  │
│ 1               ┆ 1     ┆ 15.0      ┆ 122.0      ┆ 0.0      ┆ 45.0      ┆ 0.717266          ┆ 12.789243           ┆ 9.0             ┆ 5.0       ┆ 0.0                ┆ 2.266667     ┆ 0.0                 ┆ 0.166667      ┆ 0.0           ┆ 0.833333      ┆ 1.0           ┆ 3.0              ┆ 6.0             ┆ 1.0            ┆ 0.0             ┆ 5.0             ┆ 5.0               ┆ 31.0            ┆ 1.301549        ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 0.0                ┆ 0.0      ┆ 0.0       ┆ 1.0      ┆ 0.0      ┆ 3.0        ┆ 3.9742   ┆ 69.290001 ┆ -7.001489 ┆ -0.040817 ┆ 6.960673 ┆ 924.122192  ┆ 3.133473 ┆ -11340.451172 ┆ -11340.27832  ┆ -11340.25293  ┆ -11341.288086 ┆ 25.725    ┆ -66.378105 ┆ -66.782951 ┆ -67.142738 ┆ -61.875324 ┆ 3.4103   ┆ 1.60812  ┆ 1.38385  ┆ 1.0         ┆ 0.0       │
│ 2               ┆ 1     ┆ 20.0      ┆ 121.0      ┆ 1.0      ┆ 23.0      ┆ 0.849655          ┆ 12.709961           ┆ 9.0             ┆ 2.0       ┆ 0.0                ┆ 2.1          ┆ 1.0                 ┆ 0.125         ┆ 0.0           ┆ 0.875         ┆ 0.0           ┆ 1.0              ┆ 7.0             ┆ 1.0            ┆ 0.0             ┆ 7.0             ┆ 6.0               ┆ 44.0            ┆ 1.276041        ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 0.0                ┆ 0.0      ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 1.0        ┆ 4.0327   ┆ 82.339996 ┆ -7.518506 ┆ 1.012264  ┆ 8.530769 ┆ 1163.295044 ┆ 4.697447 ┆ -9960.482422  ┆ -9960.255859  ┆ -9960.230469  ┆ -9961.373047  ┆ 32.591999 ┆ -86.530884 ┆ -87.074921 ┆ -87.563255 ┆ -80.656952 ┆ 2.7421   ┆ 1.2618   ┆ 1.19092  ┆ 0.0         ┆ 1.0       │
│ 3               ┆ 1     ┆ 15.0      ┆ 122.0      ┆ 0.0      ┆ 45.0      ┆ 0.717266          ┆ 12.789243           ┆ 9.0             ┆ 5.0       ┆ 0.0                ┆ 2.266667     ┆ 0.0                 ┆ 0.166667      ┆ 0.0           ┆ 0.833333      ┆ 1.0           ┆ 3.0              ┆ 6.0             ┆ 1.0            ┆ 0.0             ┆ 5.0             ┆ 5.0               ┆ 31.0            ┆ 1.299166        ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 0.0                ┆ 0.0      ┆ 0.0       ┆ 1.0      ┆ 0.0      ┆ 3.0        ┆ 5.46     ┆ 69.400002 ┆ -7.042306 ┆ -0.14422  ┆ 6.898087 ┆ 919.410278  ┆ 3.134017 ┆ -11340.56543  ┆ -11340.393555 ┆ -11340.367188 ┆ -11341.401367 ┆ 25.672001 ┆ -66.492226 ┆ -66.897591 ┆ -67.257378 ┆ -61.988552 ┆ 3.39366  ┆ 1.62364  ┆ 1.40316  ┆ 1.0         ┆ 0.0       │
│ 4               ┆ 1     ┆ 21.0      ┆ 128.0      ┆ 0.0      ┆ 40.0      ┆ 0.990829          ┆ 12.820921           ┆ 9.0             ┆ 3.0       ┆ 0.0                ┆ 2.095238     ┆ 2.0                 ┆ 0.0           ┆ 0.0           ┆ 1.0           ┆ 2.0           ┆ 2.0              ┆ 7.0             ┆ 0.0            ┆ 0.0             ┆ 7.0             ┆ 6.0               ┆ 45.0            ┆ 1.269356        ┆ 0.0        ┆ 2.0        ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 0.0                ┆ 0.0      ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 2.0        ┆ 2.1983   ┆ 77.160004 ┆ -6.76203  ┆ 1.975547  ┆ 8.737576 ┆ 1077.371948 ┆ 5.023004 ┆ -11543.541992 ┆ -11543.318359 ┆ -11543.292969 ┆ -11544.416992 ┆ 33.237999 ┆ -85.920044 ┆ -86.506447 ┆ -87.020523 ┆ -79.732033 ┆ 2.38722  ┆ 1.61268  ┆ 1.28395  ┆ 0.0         ┆ 1.0       │
│ 5               ┆ 1     ┆ 21.0      ┆ 128.0      ┆ 0.0      ┆ 40.0      ┆ 0.990829          ┆ 12.820921           ┆ 9.0             ┆ 3.0       ┆ 0.0                ┆ 2.095238     ┆ 2.0                 ┆ 0.0           ┆ 0.0           ┆ 1.0           ┆ 2.0           ┆ 2.0              ┆ 7.0             ┆ 0.0            ┆ 0.0             ┆ 7.0             ┆ 7.0               ┆ 45.0            ┆ 1.268368        ┆ 0.0        ┆ 2.0        ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 0.0                ┆ 0.0      ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 2.0        ┆ 2.4281   ┆ 77.269997 ┆ -6.658626 ┆ 1.989152  ┆ 8.647778 ┆ 1086.435059 ┆ 5.02529  ┆ -11543.538086 ┆ -11543.317383 ┆ -11543.292969 ┆ -11544.410156 ┆ 33.113998 ┆ -85.916969 ┆ -86.505714 ┆ -87.019791 ┆ -79.725502 ┆ 2.64634  ┆ 1.38702  ┆ 1.34698  ┆ 0.0         ┆ 1.0       │
└─────────────────┴───────┴───────────┴────────────┴──────────┴───────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴──────────┴───────────┴───────────┴───────────┴──────────┴─────────────┴──────────┴───────────────┴───────────────┴───────────────┴───────────────┴───────────┴────────────┴────────────┴────────────┴────────────┴──────────┴──────────┴──────────┴─────────────┴───────────┘

# DBSCAN

In [45]:
model_db = DBSCAN(
    eps=0.6,
    min_samples=2,
    metric='precomputed',
)

labels_db = model_db.fit_predict(dist_matrix)
df = df.with_columns(labels_db=labels_db)
print(np.unique(labels_db, return_counts=True))

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([  30, 4927,    2,   15,    4,    2,    8,    3,    2,    3,    2,
          2]))

In [46]:
create_chemiscope_viewer(df, dist_matrix, labels_db, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [47]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_db,
    clustering_method="dbscan"
)

2026-04-15 15:55:51.511 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_dbscan_projection.png

{'coords': array([[-42.87330632,  26.97616543],
        [ 72.57577087,   0.38978408],
        [ 99.66756854,  32.53057816],
        ...,
        [-33.04061161,  41.09393408],
        [-45.10445665,  39.92296242],
        [-31.10718847, -25.59146542]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_dbscan_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'dbscan'}

In [48]:
average_numeric_by_cluster(df, "labels_db")

shape: (12, 61)
┌───────────┬───────┬────────────┬───────────┬───┬───────────┬────────────┬────────────┬───────────┐
│ labels_db ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_km ┆ pct_alipha ┆ pct_aromat ┆ pct_acycl │
│ ---       ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ---       ┆ tic_ring   ┆ ic         ┆ ic        │
│ i64       ┆ u32   ┆ ---        ┆ f64       ┆   ┆ f64       ┆ ---        ┆ ---        ┆ ---       │
│           ┆       ┆ f64        ┆           ┆   ┆           ┆ f64        ┆ f64        ┆ f64       │
╞═══════════╪═══════╪════════════╪═══════════╪═══╪═══════════╪════════════╪════════════╪═══════════╡
│ -1        ┆ 30    ┆ 1.838803   ┆ 12.366667 ┆ … ┆ 1.7       ┆ 33.333333  ┆ 46.666667  ┆ 20.0      │
│ 0         ┆ 4927  ┆ 2.10453    ┆ 18.323118 ┆ … ┆ 0.827481  ┆ 79.013599  ┆ 10.33083   ┆ 10.655571 │
│ 1         ┆ 2     ┆ 1.763636   ┆ 13.0      ┆ … ┆ 2.0       ┆ 0.0        ┆ 0.0        ┆ 100.0     │
│ 2         ┆ 15    ┆ 1.607148   ┆ 11.466667 ┆ … ┆ 2.0       ┆ 0.0        ┆ 100.0      ┆ 0.0       │
│ 3         ┆ 4     ┆ 1.807143   ┆ 13.0      ┆ … ┆ 2.0       ┆ 0.0        ┆ 50.0       ┆ 50.0      │
│ …         ┆ …     ┆ …          ┆ …         ┆ … ┆ …         ┆ …          ┆ …          ┆ …         │
│ 6         ┆ 3     ┆ 1.42735    ┆ 12.333333 ┆ … ┆ 2.0       ┆ 0.0        ┆ 0.0        ┆ 100.0     │
│ 7         ┆ 2     ┆ 2.236074   ┆ 27.5      ┆ … ┆ 0.0       ┆ 0.0        ┆ 0.0        ┆ 100.0     │
│ 8         ┆ 3     ┆ 1.666667   ┆ 10.0      ┆ … ┆ 2.0       ┆ 0.0        ┆ 100.0      ┆ 0.0       │
│ 9         ┆ 2     ┆ 1.769231   ┆ 13.0      ┆ … ┆ 2.0       ┆ 100.0      ┆ 0.0        ┆ 0.0       │
│ 10        ┆ 2     ┆ 2.0        ┆ 13.0      ┆ … ┆ 2.0       ┆ 100.0      ┆ 0.0        ┆ 0.0       │
└───────────┴───────┴────────────┴───────────┴───┴───────────┴────────────┴────────────┴───────────┘