In [1]:
import os
os.chdir('../../../../..')

In [2]:
import numpy as np

from sklearn.cluster import AgglomerativeClustering, SpectralClustering, DBSCAN
from kmedoids import KMedoids

from src.datasets import QM9Dataset
from src.helper_functions import plot_molecules_with_py3dmol, create_chemiscope_viewer, plot_distance_matrix_projection, evaluate_distance_matrix_clustering_sweep, average_numeric_by_cluster

In [3]:
qm9 = QM9Dataset(limit=5000, sampling_strategy="stratified", stratify_by=["num_atoms", "gap"], add_acsf=True)
df = qm9.load()
molecules = qm9.get_molecules()

2026-04-21 10:37:24.418 | INFO     | src.datasets:load:496 - Loading cached full QM9 dataset from: data/QM9/dataset_cleaned.parquet
2026-04-21 10:37:24.919 | INFO     | src.datasets:_sample_qm9_df:688 - QM9 sampling complete: strategy=stratified, requested_limit=5500, returned_rows=5500.
2026-04-21 10:37:24.921 | INFO     | src.datasets:_add_requested_descriptors:129 - Applying requested QM9 descriptors to sampled dataframe (rows=5500).
2026-04-21 10:37:24.922 | INFO     | src.features:compute_acsf:201 - Computing ACSF (rcut=6.0)...
2026-04-21 10:39:16.678 | SUCCESS  | src.datasets:add_acsf:853 - Added ACSF embeddings.
2026-04-21 10:39:16.686 | INFO     | src.datasets:_add_requested_descriptors:152 - Added descriptor column(s): ['acsf_embedding']
2026-04-21 10:39:16.745 | INFO     | src.datasets:_drop_rows_with_null_required_descriptors:581 - Dropped QM9 rows with null/empty descriptor vectors: dropped=23, remaining=5477, descriptor_cols=['acsf_embedding'].
2026-04-21 10:39:16.747 | INFO     | src.datasets:load:530 - QM9 descriptor null-filtering complete: attempts=1, requested_limit=5000, returned_rows=5000.
2026-04-21 10:40:41.248 | SUCCESS  | src.datasets:get_molecules:1181 - Saved 5000 molecules to data/QM9/qm9_subset.xyz (failed: 0, requested: 5000).

In [4]:
len(molecules[0:2])

2

In [5]:
plot_molecules_with_py3dmol(molecules[0:3])

In [5]:
dist_matrix = qm9.get_distance_matrix(
    descriptor="acsf",
    dist_type="euclidean",
    force_calculate=True,
    pca_variance=99
)

2026-04-21 10:40:41.367 | INFO     | src.datasets:get_distance_matrix:991 - Applying PCA to retain 99.00% of variance.
2026-04-21 10:40:41.734 | INFO     | src.datasets:get_distance_matrix:1001 - PCA reduced 'acsf' dimensions from 65 to 5
2026-04-21 10:40:41.838 | INFO     | src.datasets:get_distance_matrix:1012 - Calculating distance matrix for acsf using euclidean distance.
2026-04-21 10:40:42.393 | SUCCESS  | src.distance:_compute_and_save:79 - Saved distance matrix to data/QM9/dist_acsf_euclidean_pca0.99.npy

# Determining the best number of clusters for each clustering method

In [6]:
out = evaluate_distance_matrix_clustering_sweep(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    dataset_name="qm9",
)

Evaluation k:   0%|          | 0/19 [00:05<?, ?it/s]

KeyboardInterrupt:

In [7]:
# find the n molecules that are not on the diagonal with the smallest distance
n = 10
# Get the indices of the upper triangle (excluding diagonal)
triu_indices = np.triu_indices_from(dist_matrix, k=1)
# Get the distances and corresponding molecule pairs
distances = dist_matrix[triu_indices]
molecule_pairs = list(zip(triu_indices[0], triu_indices[1]))
# Get the indices of the n smallest distances
smallest_indices = np.argsort(distances)[:n]
# Get the corresponding molecule pairs for the n smallest distances
closest_pairs = [molecule_pairs[i] for i in smallest_indices]
print("Closest molecule pairs (indices):", closest_pairs)
mols = [(molecules[idx1], molecules[idx2]) for idx1, idx2 in closest_pairs]

Closest molecule pairs (indices): [(np.int64(1332), np.int64(1333)), (np.int64(3300), np.int64(3313)), (np.int64(2814), np.int64(2845)), (np.int64(1567), np.int64(4667)), (np.int64(1429), np.int64(1430)), (np.int64(2849), np.int64(2957)), (np.int64(2756), np.int64(3460)), (np.int64(3389), np.int64(3698)), (np.int64(3244), np.int64(3413)), (np.int64(1473), np.int64(1488))]

In [8]:
print(mols[0])

(Atoms(symbols='H3CH3NHOCNCNC2', pbc=False, initial_charges=..., mass=..., partial_charge=...), Atoms(symbols='H3CH3NHOCNCNC2', pbc=False, initial_charges=..., mass=..., partial_charge=...))

In [9]:
plot_molecules_with_py3dmol(mols[1])

# Hiercical Clustering on Distance Matrix

In [10]:
model_hier = AgglomerativeClustering(metric='precomputed', n_clusters=3, linkage='complete')
labels_hier = model_hier.fit_predict(dist_matrix)
df = df.with_columns(labels_hier=labels_hier)

In [15]:
create_chemiscope_viewer(df, dist_matrix, labels_hier, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [13]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_hier,
    clustering_method="hierarchical"
)

2026-04-21 10:46:23.679 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_hierarchical_projection.png

{'coords': array([[-43.62463075,  26.47490526],
        [ 72.80547255,   0.14337807],
        [ 99.82023045,  33.12011067],
        ...,
        [-33.22654004,  41.25085348],
        [-45.36688247,  39.99436312],
        [-31.06818226, -25.73946776]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_hierarchical_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'hierarchical'}

In [14]:
average_numeric_by_cluster(df, "labels_hier")

shape: (3, 59)
┌─────────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬────────────────────┬──────────────┬─────────────┐
│ labels_hier ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---         ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---                ┆ ---          ┆ ---         │
│ i64         ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64                ┆ f64          ┆ f64         │
╞═════════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪════════════════════╪══════════════╪═════════════╡
│ 0           ┆ 2684  ┆ 2.0066              ┆ 16.5261   ┆ 121.7761   ┆ -0.0868 ┆ 43.9173 ┆ 0.8570            ┆ 12.8360             ┆ 8.7321          ┆ 1.5108    ┆ 0.1993             ┆ 2.0508       ┆ 2.0425              ┆ 0.0995        ┆ 0.2975        ┆ 0.6030        ┆ 0.9721        ┆ 2.3744           ┆ 5.9437          ┆ 0.6367         ┆ 1.6561          ┆ 3.6270          ┆ 6.3342            ┆ 33.3089         ┆ 1.2647          ┆ 0.0022     ┆ 0.3320     ┆ 0.0436    ┆ 0.1688   ┆ 0.1882   ┆ 0.0015             ┆ 0.0663   ┆ 0.1684    ┆ 0.6017   ┆ 0.0004   ┆ 2.8122     ┆ 3.0045 ┆ 72.2464 ┆ -6.5564 ┆ -0.1388 ┆ 6.4176 ┆ 1166.5638 ┆ 3.5846 ┆ -11393.1850 ┆ -11392.9581 ┆ -11392.9324 ┆ -11394.0939 ┆ 30.5730 ┆ -71.1596 ┆ -71.5697 ┆ -71.9687 ┆ -66.3192 ┆ 3.6081 ┆ 1.4008 ┆ 1.1054 ┆ 67.3621            ┆ 19.1133      ┆ 13.5246     │
│ 1           ┆ 2290  ┆ 2.2136              ┆ 20.3279   ┆ 123.6852   ┆ 0.2913  ┆ 25.7572 ┆ 0.9053            ┆ 12.8290             ┆ 8.8231          ┆ 1.8747    ┆ 0.0057             ┆ 2.0755       ┆ 2.6563              ┆ 0.0319        ┆ 0.0797        ┆ 0.8884        ┆ 0.8476        ┆ 1.4349           ┆ 7.2655          ┆ 0.2293         ┆ 0.5672          ┆ 6.2581          ┆ 6.3493            ┆ 44.9659         ┆ 1.2591          ┆ 0.0004     ┆ 0.4057     ┆ 0.0000    ┆ 0.0952   ┆ 0.0533   ┆ 0.0017             ┆ 0.0122   ┆ 0.0825    ┆ 0.5197   ┆ 0.0000   ┆ 1.7686     ┆ 2.1871 ┆ 79.2760 ┆ -6.5136 ┆ 1.0037  ┆ 7.5172 ┆ 1212.3499 ┆ 4.7818 ┆ -10790.1695 ┆ -10789.9296 ┆ -10789.9039 ┆ -10791.0826 ┆ 33.5234 ┆ -83.8756 ┆ -84.4191 ┆ -84.9159 ┆ -77.9402 ┆ 3.0776 ┆ 1.3987 ┆ 1.1544 ┆ 91.5721            ┆ 0.5677       ┆ 7.8603      │
│ 2           ┆ 26    ┆ 1.6153              ┆ 10.6538   ┆ 107.1154   ┆ -0.3077 ┆ 66.7692 ┆ 0.1660            ┆ 13.3662             ┆ 7.6923          ┆ 1.0769    ┆ 1.0000             ┆ 2.0134       ┆ 0.8077              ┆ 0.1442        ┆ 0.7596        ┆ 0.0962        ┆ 0.7692        ┆ 4.1923           ┆ 3.5769          ┆ 0.5000         ┆ 2.0769          ┆ 0.2692          ┆ 5.5769            ┆ 17.2692         ┆ 1.2712          ┆ 0.0000     ┆ 0.0000     ┆ 0.1154    ┆ 0.3462   ┆ 0.0385   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0385   ┆ 0.0000   ┆ 4.8462     ┆ 3.7279 ┆ 55.5038 ┆ -7.2099 ┆ -1.6098 ┆ 5.6000 ┆ 783.6545  ┆ 1.9384 ┆ -10760.7394 ┆ -10760.5723 ┆ -10760.5466 ┆ -10761.5692 ┆ 21.8929 ┆ -46.6608 ┆ -46.9044 ┆ -47.1525 ┆ -43.5250 ┆ 6.4974 ┆ 2.0186 ┆ 1.5061 ┆ 7.6923             ┆ 92.3077      ┆ 0.0000      │
└─────────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴────────────────────┴──────────────┴─────────────┘

shape: (3, 59)
┌────────────┬───────┬────────────┬───────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ labels_hie ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ C        ┆ pct_alipha ┆ pct_aromat ┆ pct_acycl │
│ r          ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ---      ┆ tic_ring   ┆ ic         ┆ ic        │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ f64      ┆ ---        ┆ ---        ┆ ---       │
│ i64        ┆       ┆ f64        ┆           ┆   ┆          ┆ f64        ┆ f64        ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 0          ┆ 2684  ┆ 2.006618   ┆ 16.52608  ┆ … ┆ 1.10543  ┆ 67.362146  ┆ 19.113264  ┆ 13.52459  │
│ 1          ┆ 2290  ┆ 2.213586   ┆ 20.327948 ┆ … ┆ 1.15437  ┆ 91.572052  ┆ 0.567686   ┆ 7.860262  │
│ 2          ┆ 26    ┆ 1.615254   ┆ 10.653846 ┆ … ┆ 1.506122 ┆ 7.692308   ┆ 92.307692  ┆ 0.0       │
└────────────┴───────┴────────────┴───────────┴───┴──────────┴────────────┴────────────┴───────────┘

# KMedoids

In [ ]:
model_km = KMedoids(n_clusters=3, metric="precomputed")
labels_km = model_km.fit_predict(dist_matrix)
df = df.with_columns(labels_km=labels_km)
print(np.unique(labels_km, return_counts=True))

In [17]:
create_chemiscope_viewer(df, dist_matrix, labels_km, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [18]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_km,
    clustering_method="kmedoids"
)

2026-04-21 10:53:07.118 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_kmedoids_projection.png

{'coords': array([[-43.62463075,  26.47490526],
        [ 72.80547255,   0.14337807],
        [ 99.82023045,  33.12011067],
        ...,
        [-33.22654004,  41.25085348],
        [-45.36688247,  39.99436312],
        [-31.06818226, -25.73946776]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_kmedoids_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'kmedoids'}

In [19]:
average_numeric_by_cluster(df, "labels_km")

shape: (3, 60)
┌───────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬────────────────────┬──────────────┬─────────────┐
│ labels_km ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---       ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---                ┆ ---          ┆ ---         │
│ u64       ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64                ┆ f64          ┆ f64         │
╞═══════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪════════════════════╪══════════════╪═════════════╡
│ 0         ┆ 1922  ┆ 2.1018              ┆ 17.7196   ┆ 123.2216   ┆ -0.1015 ┆ 38.1935 ┆ 0.9015            ┆ 12.8190             ┆ 8.8085          ┆ 1.7862    ┆ 0.0380             ┆ 2.0779       ┆ 2.2232              ┆ 0.0764        ┆ 0.1623        ┆ 0.7613        ┆ 0.9313        ┆ 2.1420           ┆ 6.3200          ┆ 0.5213         ┆ 1.0276          ┆ 4.7695          ┆ 6.2914            ┆ 37.2097         ┆ 1.2663          ┆ 0.0005     ┆ 0.4298     ┆ 0.0052    ┆ 0.1113   ┆ 0.1254   ┆ 0.0021             ┆ 0.0541   ┆ 0.1629    ┆ 0.7107   ┆ 0.0000   ┆ 2.4901     ┆ 2.8539 ┆ 73.8278 ┆ -6.6132 ┆ 0.1914  ┆ 6.8045 ┆ 1169.0343 ┆ 3.9477 ┆ -11334.8607 ┆ -11334.6303 ┆ -11334.6046 ┆ -11335.7703 ┆ 31.5120 ┆ -75.0639 ┆ -75.5164 ┆ -75.9461 ┆ -69.8743 ┆ 3.2855 ┆ 1.4025 ┆ 1.1399 ┆ 0.2081      ┆ 87.0447            ┆ 3.7981       ┆ 9.1571      │
│ 1         ┆ 1923  ┆ 2.2257              ┆ 20.7005   ┆ 123.7821   ┆ 0.3703  ┆ 23.3313 ┆ 0.9125            ┆ 12.8236             ┆ 8.8310          ┆ 1.9064    ┆ 0.0036             ┆ 2.0770       ┆ 2.6942              ┆ 0.0250        ┆ 0.0727        ┆ 0.9023        ┆ 0.7962        ┆ 1.3203           ┆ 7.4041          ┆ 0.1856         ┆ 0.5299          ┆ 6.4727          ┆ 6.3583            ┆ 46.0244         ┆ 1.2587          ┆ 0.0005     ┆ 0.3947     ┆ 0.0000    ┆ 0.0764   ┆ 0.0426   ┆ 0.0010             ┆ 0.0099   ┆ 0.0770    ┆ 0.5044   ┆ 0.0000   ┆ 1.6427     ┆ 2.0747 ┆ 80.1117 ┆ -6.4982 ┆ 1.1148  ┆ 7.6130 ┆ 1221.0305 ┆ 4.8997 ┆ -10718.5657 ┆ -10718.3247 ┆ -10718.2990 ┆ -10719.4794 ┆ 33.7746 ┆ -85.2075 ┆ -85.7643 ┆ -86.2707 ┆ -79.1656 ┆ 3.0575 ┆ 1.3955 ┆ 1.1540 ┆ 0.9828      ┆ 91.6797            ┆ 0.3640       ┆ 7.9563      │
│ 2         ┆ 1155  ┆ 1.8850              ┆ 14.9957   ┆ 119.4857   ┆ -0.0788 ┆ 52.2251 ┆ 0.7709            ┆ 12.8828             ┆ 8.5974          ┆ 1.1056    ┆ 0.4277             ┆ 2.0103       ┆ 1.8459              ┆ 0.1289        ┆ 0.4756        ┆ 0.3955        ┆ 1.0814        ┆ 2.6944           ┆ 5.4537          ┆ 0.7688         ┆ 2.4277          ┆ 2.1290          ┆ 6.3784            ┆ 28.3983         ┆ 1.2611          ┆ 0.0043     ┆ 0.2035     ┆ 0.0952    ┆ 0.2762   ┆ 0.2641   ┆ 0.0017             ┆ 0.0719   ┆ 0.1558    ┆ 0.4069   ┆ 0.0009   ┆ 3.2719     ┆ 3.1988 ┆ 70.0804 ┆ -6.4886 ┆ -0.5434 ┆ 5.9452 ┆ 1153.9291 ┆ 3.1275 ┆ -11403.6119 ┆ -11403.3900 ┆ -11403.3643 ┆ -11404.5183 ┆ 29.3343 ┆ -65.9340 ┆ -66.2900 ┆ -66.6497 ┆ -61.5427 ┆ 4.0747 ┆ 1.4165 ┆ 1.0732 ┆ 0.0450      ┆ 40.7792            ┆ 40.6926      ┆ 18.5281     │
└───────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴────────────────────┴──────────────┴─────────────┘

shape: (3, 60)
┌───────────┬───────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ labels_km ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_hie ┆ pct_alipha ┆ pct_aroma ┆ pct_acycl │
│ ---       ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ r          ┆ tic_ring   ┆ tic       ┆ ic        │
│ u64       ┆ u32   ┆ ---        ┆ f64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆       ┆ f64        ┆           ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞═══════════╪═══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0         ┆ 1922  ┆ 2.101834   ┆ 17.719563 ┆ … ┆ 0.208117   ┆ 87.044745  ┆ 3.798127  ┆ 9.157128  │
│ 1         ┆ 1923  ┆ 2.225683   ┆ 20.700468 ┆ … ┆ 0.982839   ┆ 91.679667  ┆ 0.364015  ┆ 7.956318  │
│ 2         ┆ 1155  ┆ 1.884983   ┆ 14.995671 ┆ … ┆ 0.045022   ┆ 40.779221  ┆ 40.692641 ┆ 18.528139 │
└───────────┴───────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

# Spectral

In [20]:
model_spectral = SpectralClustering(
                n_clusters=3,
                affinity="precomputed",
                assign_labels='kmeans',
                random_state=42,
            )

labels_spectral = model_spectral.fit_predict(dist_matrix)
df = df.with_columns(labels_spectral=labels_spectral)
print(np.unique(labels_spectral, return_counts=True))

(array([0, 1, 2], dtype=int32), array([4998,    1,    1]))

In [21]:
create_chemiscope_viewer(df, dist_matrix, labels_spectral, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [21]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_spectral,
    clustering_method="spectral"
)

2026-04-19 12:29:48.193 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_spectral_projection.png

{'coords': array([[-42.87330632,  26.97616543],
        [ 72.57577087,   0.38978408],
        [ 99.66756854,  32.53057816],
        ...,
        [-33.04061161,  41.09393408],
        [-45.10445665,  39.92296242],
        [-31.10718847, -25.59146542]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_spectral_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'spectral'}

In [22]:
average_numeric_by_cluster(df, "labels_spectral")

shape: (4, 61)
┌─────────────────┬───────┬─────────────────────┬───────────┬────────────┬────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────┬────────────────────┬──────────────┬─────────────┐
│ labels_spectral ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp   ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---             ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---    ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---                ┆ ---          ┆ ---         │
│ i32             ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64    ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64                ┆ f64          ┆ f64         │
╞═════════════════╪═══════╪═════════════════════╪═══════════╪════════════╪════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════╪════════════════════╪══════════════╪═════════════╡
│ 0               ┆ 4997  ┆ 2.0994              ┆ 18.2375   ┆ 122.5733   ┆ 0.0853 ┆ 35.7142 ┆ 0.8756            ┆ 12.8355             ┆ 8.7683          ┆ 1.6736    ┆ 0.1149             ┆ 2.0619       ┆ 2.3182              ┆ 0.0687        ┆ 0.2003        ┆ 0.7310        ┆ 0.9137        ┆ 1.9532           ┆ 6.5369          ┆ 0.4493         ┆ 1.1603          ┆ 4.8141          ┆ 6.3376            ┆ 38.5661         ┆ 1.2622          ┆ 0.0014     ┆ 0.3638     ┆ 0.0240    ┆ 0.1361   ┆ 0.1257   ┆ 0.0016             ┆ 0.0412   ┆ 0.1283    ┆ 0.5611   ┆ 0.0002   ┆ 2.3446     ┆ 2.6331 ┆ 75.3809 ┆ -6.5399 ┆ 0.3767  ┆ 6.9166 ┆ 1185.6681 ┆ 4.1246 ┆ -11113.5384 ┆ -11113.3058 ┆ -11113.2801 ┆ -11114.4489 ┆ 31.8814 ┆ -76.8585 ┆ -77.3288 ┆ -77.7719 ┆ -71.5253 ┆ 3.3803 ┆ 1.4030 ┆ 1.1298 ┆ 1.0442      ┆ 1.0346    ┆ 78.1269            ┆ 11.0066      ┆ 10.8665     │
│ 1               ┆ 1     ┆ 2.0667              ┆ 15.0000   ┆ 122.0000   ┆ 0.0000 ┆ 45.0000 ┆ 0.7173            ┆ 12.7892             ┆ 9.0000          ┆ 5.0000    ┆ 0.0000             ┆ 2.2667       ┆ 0.0000              ┆ 0.1667        ┆ 0.0000        ┆ 0.8333        ┆ 1.0000        ┆ 3.0000           ┆ 6.0000          ┆ 1.0000         ┆ 0.0000          ┆ 5.0000          ┆ 5.0000            ┆ 31.0000         ┆ 1.3015          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 1.0000   ┆ 0.0000   ┆ 3.0000     ┆ 3.9742 ┆ 69.2900 ┆ -7.0015 ┆ -0.0408 ┆ 6.9607 ┆ 924.1222  ┆ 3.1335 ┆ -11340.4512 ┆ -11340.2783 ┆ -11340.2529 ┆ -11341.2881 ┆ 25.7250 ┆ -66.3781 ┆ -66.7830 ┆ -67.1427 ┆ -61.8753 ┆ 3.4103 ┆ 1.6081 ┆ 1.3838 ┆ 1.0000      ┆ 2.0000    ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
│ 2               ┆ 1     ┆ 2.0667              ┆ 15.0000   ┆ 122.0000   ┆ 0.0000 ┆ 45.0000 ┆ 0.7173            ┆ 12.7892             ┆ 9.0000          ┆ 5.0000    ┆ 0.0000             ┆ 2.2667       ┆ 0.0000              ┆ 0.1667        ┆ 0.0000        ┆ 0.8333        ┆ 1.0000        ┆ 3.0000           ┆ 6.0000          ┆ 1.0000         ┆ 0.0000          ┆ 5.0000          ┆ 5.0000            ┆ 31.0000         ┆ 1.2992          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 1.0000   ┆ 0.0000   ┆ 3.0000     ┆ 5.4600 ┆ 69.4000 ┆ -7.0423 ┆ -0.1442 ┆ 6.8981 ┆ 919.4103  ┆ 3.1340 ┆ -11340.5654 ┆ -11340.3936 ┆ -11340.3672 ┆ -11341.4014 ┆ 25.6720 ┆ -66.4922 ┆ -66.8976 ┆ -67.2574 ┆ -61.9886 ┆ 3.3937 ┆ 1.6236 ┆ 1.4032 ┆ 1.0000      ┆ 2.0000    ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
│ 3               ┆ 1     ┆ 2.1429              ┆ 21.0000   ┆ 128.0000   ┆ 0.0000 ┆ 40.0000 ┆ 0.9908            ┆ 12.8209             ┆ 9.0000          ┆ 3.0000    ┆ 0.0000             ┆ 2.0952       ┆ 2.0000              ┆ 0.0000        ┆ 0.0000        ┆ 1.0000        ┆ 2.0000        ┆ 2.0000           ┆ 7.0000          ┆ 0.0000         ┆ 0.0000          ┆ 7.0000          ┆ 7.0000            ┆ 45.0000         ┆ 1.2684          ┆ 0.0000     ┆ 2.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 2.0000     ┆ 2.4281 ┆ 77.2700 ┆ -6.6586 ┆ 1.9892  ┆ 8.6478 ┆ 1086.4351 ┆ 5.0253 ┆ -11543.5381 ┆ -11543.3174 ┆ -11543.2930 ┆ -11544.4102 ┆ 33.1140 ┆ -85.9170 ┆ -86.5057 ┆ -87.0198 ┆ -79.7255 ┆ 2.6463 ┆ 1.3870 ┆ 1.3470 ┆ 2.0000      ┆ 0.0000    ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
└─────────────────┴───────┴─────────────────────┴───────────┴────────────┴────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴───────────┴────────────────────┴──────────────┴─────────────┘

# DBSCAN

In [22]:
model_db = DBSCAN(
    eps=0.6,
    min_samples=2,
    metric='precomputed',
)

labels_db = model_db.fit_predict(dist_matrix)
df = df.with_columns(labels_db=labels_db)
print(np.unique(labels_db, return_counts=True))

(array([-1,  0,  1,  2,  3,  4,  5]), array([  19, 4970,    2,    3,    2,    2,    2]))

In [23]:
create_chemiscope_viewer(df, dist_matrix, labels_db, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [24]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="acsf",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_db,
    clustering_method="dbscan"
)

2026-04-21 11:08:34.778 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/acsf/pca_dbscan_projection.png

{'coords': array([[-43.62463075,  26.47490526],
        [ 72.80547255,   0.14337807],
        [ 99.82023045,  33.12011067],
        ...,
        [-33.22654004,  41.25085348],
        [-45.36688247,  39.99436312],
        [-31.06818226, -25.73946776]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/acsf/pca_dbscan_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/acsf'),
 'clustering_method': 'dbscan'}

In [26]:
average_numeric_by_cluster(df, "labels_db")

shape: (12, 62)
┌───────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬─────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬───────────┬───────────┬───────────┬──────────┬─────────┬────────┬────────┬─────────────┬───────────┬─────────────────┬────────────────────┬──────────────┬─────────────┐
│ labels_db ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap     ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom   ┆ u_atom    ┆ h_atom    ┆ g_atom   ┆ A       ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ labels_spectral ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---       ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---     ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---             ┆ ---                ┆ ---          ┆ ---         │
│ i64       ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64       ┆ f64       ┆ f64       ┆ f64      ┆ f64     ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64             ┆ f64                ┆ f64          ┆ f64         │
╞═══════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪═════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪═══════════╪═══════════╪═══════════╪══════════╪═════════╪════════╪════════╪═════════════╪═══════════╪═════════════════╪════════════════════╪══════════════╪═════════════╡
│ -1        ┆ 30    ┆ 1.8388              ┆ 12.3667   ┆ 111.3000   ┆ -0.2667 ┆ 53.6667 ┆ 0.5824            ┆ 13.1662             ┆ 7.9000          ┆ 1.1667    ┆ 0.5333             ┆ 2.0133       ┆ 1.0333              ┆ 0.1311        ┆ 0.5163        ┆ 0.3526        ┆ 0.9333        ┆ 3.0000           ┆ 4.3000          ┆ 0.6000         ┆ 1.7000          ┆ 1.7333          ┆ 5.6667            ┆ 23.4333         ┆ 1.2697          ┆ 0.0333     ┆ 0.2333     ┆ 0.0667    ┆ 0.3000   ┆ 0.2333   ┆ 0.0000             ┆ 0.0333   ┆ 0.0333    ┆ 0.2667   ┆ 0.0000   ┆ 3.8667     ┆ 2.6359 ┆ 59.4363 ┆ -7.0429 ┆ -0.8542 ┆ 6.1890  ┆ 868.9404  ┆ 2.4241 ┆ -11045.3152 ┆ -11045.1316 ┆ -11045.1058 ┆ -11046.1653 ┆ 24.4973 ┆ -54.1195  ┆ -54.4124  ┆ -54.7045  ┆ -50.5006 ┆ 5.7383  ┆ 1.8978 ┆ 1.4671 ┆ 0.2333      ┆ 0.9000    ┆ 0.0000          ┆ 33.3333            ┆ 46.6667      ┆ 20.0000     │
│ 0         ┆ 4927  ┆ 2.1045              ┆ 18.3231   ┆ 122.7215   ┆ 0.0887  ┆ 35.4132 ┆ 0.8795            ┆ 12.8319             ┆ 8.7792          ┆ 1.6858    ┆ 0.1076             ┆ 2.0630       ┆ 2.3331              ┆ 0.0675        ┆ 0.1944        ┆ 0.7381        ┆ 0.9166        ┆ 1.9336           ┆ 6.5720          ┆ 0.4449         ┆ 1.1461          ┆ 4.8667          ┆ 6.3442            ┆ 38.8052         ┆ 1.2621          ┆ 0.0012     ┆ 0.3676     ┆ 0.0229    ┆ 0.1340   ┆ 0.1246   ┆ 0.0016             ┆ 0.0404   ┆ 0.1287    ┆ 0.5657   ┆ 0.0000   ┆ 2.3215     ┆ 2.6273 ┆ 75.5963 ┆ -6.5318 ┆ 0.3992  ┆ 6.9310  ┆ 1188.8308 ┆ 4.1498 ┆ -11112.4780 ┆ -11112.2449 ┆ -11112.2192 ┆ -11113.3891 ┆ 31.9778 ┆ -77.1805  ┆ -77.6536  ┆ -78.0988  ┆ -71.8223 ┆ 3.3482  ┆ 1.3983 ┆ 1.1270 ┆ 1.0576      ┆ 1.0363    ┆ 0.0012          ┆ 79.0136            ┆ 10.3308      ┆ 10.6556     │
│ 1         ┆ 2     ┆ 1.7636              ┆ 13.0000   ┆ 108.5000   ┆ 0.0000  ┆ 64.5000 ┆ 0.7846            ┆ 13.0765             ┆ 7.5000          ┆ 0.0000    ┆ 0.0000             ┆ 1.8424       ┆ 4.0000              ┆ 0.0000        ┆ 0.7083        ┆ 0.2917        ┆ 0.5000        ┆ 2.5000           ┆ 4.0000          ┆ 0.0000         ┆ 2.5000          ┆ 1.0000          ┆ 7.0000            ┆ 23.0000         ┆ 1.2484          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.5000   ┆ 0.0000             ┆ 0.5000   ┆ 0.0000    ┆ 1.0000   ┆ 0.0000   ┆ 4.0000     ┆ 2.9738 ┆ 56.3750 ┆ -7.1117 ┆ -1.1783 ┆ 5.9348  ┆ 1247.4133 ┆ 2.6293 ┆ -11069.0000 ┆ -11068.7793 ┆ -11068.7539 ┆ -11069.9424 ┆ 26.1540 ┆ -55.1249  ┆ -55.4053  ┆ -55.7137  ┆ -51.4570 ┆ 10.4683 ┆ 1.1141 ┆ 1.0541 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 0.0000             ┆ 0.0000       ┆ 100.0000    │
│ 2         ┆ 15    ┆ 1.6071              ┆ 11.4667   ┆ 107.8667   ┆ -0.2667 ┆ 66.9333 ┆ 0.1707            ┆ 13.2936             ┆ 7.8000          ┆ 1.0667    ┆ 1.0667             ┆ 2.0111       ┆ 1.0667              ┆ 0.1500        ┆ 0.7500        ┆ 0.1000        ┆ 0.8667        ┆ 4.2000           ┆ 3.9333          ┆ 0.5333         ┆ 2.2667          ┆ 0.3333          ┆ 5.8000            ┆ 18.4667         ┆ 1.2625          ┆ 0.0000     ┆ 0.0000     ┆ 0.2000    ┆ 0.4667   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 4.6667     ┆ 4.2927 ┆ 58.5460 ┆ -6.8908 ┆ -1.2283 ┆ 5.6621  ┆ 829.5855  ┆ 2.1928 ┆ -10592.6709 ┆ -10592.4972 ┆ -10592.4717 ┆ -10593.5094 ┆ 22.9176 ┆ -50.0548  ┆ -50.3232  ┆ -50.5922  ┆ -46.6821 ┆ 6.0975  ┆ 1.9154 ┆ 1.4379 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 3         ┆ 4     ┆ 1.8071              ┆ 13.0000   ┆ 123.5000   ┆ -0.5000 ┆ 72.2500 ┆ 0.9364            ┆ 13.0012             ┆ 8.5000          ┆ 0.5000    ┆ 0.5000             ┆ 1.9286       ┆ 2.0000              ┆ 0.0000        ┆ 0.7292        ┆ 0.2708        ┆ 1.0000        ┆ 4.2500           ┆ 4.5000          ┆ 0.0000         ┆ 2.7500          ┆ 1.0000          ┆ 6.2500            ┆ 23.5000         ┆ 1.2600          ┆ 0.0000     ┆ 0.0000     ┆ 0.2500    ┆ 0.2500   ┆ 0.7500   ┆ 0.0000             ┆ 0.2500   ┆ 0.2500    ┆ 0.5000   ┆ 0.0000   ┆ 4.7500     ┆ 4.6397 ┆ 57.3200 ┆ -6.9205 ┆ -1.0150 ┆ 5.9049  ┆ 1180.3120 ┆ 2.4737 ┆ -13126.2065 ┆ -13125.9836 ┆ -13125.9575 ┆ -13127.1179 ┆ 28.0790 ┆ -57.8663  ┆ -58.1443  ┆ -58.4527  ┆ -54.0539 ┆ 4.8393  ┆ 1.3578 ┆ 1.0433 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 0.0000             ┆ 50.0000      ┆ 50.0000     │
│ 4         ┆ 2     ┆ 1.8513              ┆ 14.0000   ┆ 105.5000   ┆ 0.0000  ┆ 67.5000 ┆ 0.1731            ┆ 13.3947             ┆ 7.5000          ┆ 1.0000    ┆ 1.0000             ┆ 2.0000       ┆ 2.5000              ┆ 0.0000        ┆ 0.6667        ┆ 0.3333        ┆ 2.0000        ┆ 4.0000           ┆ 5.5000          ┆ 0.0000         ┆ 2.0000          ┆ 1.0000          ┆ 6.5000            ┆ 26.0000         ┆ 1.2417          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 1.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 4.5000     ┆ 2.3741 ┆ 60.7250 ┆ -5.4600 ┆ 0.8327  ┆ 6.2926  ┆ 869.2469  ┆ 3.0691 ┆ -9918.6611  ┆ -9918.4624  ┆ -9918.4360  ┆ -9919.5195  ┆ 26.0935 ┆ -56.7252  ┆ -57.0660  ┆ -57.4001  ┆ -52.6708 ┆ 6.9944  ┆ 1.7601 ┆ 1.4123 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 5         ┆ 8     ┆ 1.6038              ┆ 10.3750   ┆ 116.5000   ┆ -0.2500 ┆ 71.6250 ┆ 0.6959            ┆ 12.9138             ┆ 8.3750          ┆ 0.6250    ┆ 0.6250             ┆ 1.9295       ┆ 0.7500              ┆ 0.2625        ┆ 0.7063        ┆ 0.0312        ┆ 0.2500        ┆ 4.1250           ┆ 3.1250          ┆ 1.1250         ┆ 2.6250          ┆ 0.1250          ┆ 5.7500            ┆ 16.6250         ┆ 1.2829          ┆ 0.0000     ┆ 0.0000     ┆ 0.1250    ┆ 0.1250   ┆ 0.3750   ┆ 0.0000             ┆ 0.2500   ┆ 0.0000    ┆ 0.2500   ┆ 0.1250   ┆ 4.5000     ┆ 3.1955 ┆ 58.9612 ┆ -7.8277 ┆ -2.4266 ┆ 5.4011  ┆ 1042.1138 ┆ 1.6897 ┆ -12144.9192 ┆ -12144.7271 ┆ -12144.7014 ┆ -12145.7941 ┆ 24.2726 ┆ -49.8402  ┆ -50.0481  ┆ -50.2889  ┆ -46.7663 ┆ 4.9040  ┆ 1.5139 ┆ 1.1332 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 0.0000             ┆ 62.5000      ┆ 37.5000     │
│ 6         ┆ 3     ┆ 1.4274              ┆ 12.3333   ┆ 109.3333   ┆ 0.0000  ┆ 24.6667 ┆ 1.1184            ┆ 12.2716             ┆ 8.3333          ┆ 0.0000    ┆ 0.0000             ┆ 1.8376       ┆ 0.6667              ┆ 0.7619        ┆ 0.0952        ┆ 0.1429        ┆ 0.6667        ┆ 1.3333           ┆ 1.6667          ┆ 5.3333         ┆ 0.6667          ┆ 1.0000          ┆ 7.3333            ┆ 17.6667         ┆ 1.2464          ┆ 0.0000     ┆ 0.6667     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 1.3333     ┆ 0.9262 ┆ 75.6367 ┆ -7.2963 ┆ -1.1039 ┆ 6.1924  ┆ 1525.4664 ┆ 2.2092 ┆ -10045.8672 ┆ -10045.6204 ┆ -10045.5944 ┆ -10046.8138 ┆ 31.1127 ┆ -58.8911  ┆ -59.1199  ┆ -59.4111  ┆ -55.3654 ┆ 4.7116  ┆ 1.1621 ┆ 0.9040 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 0.0000             ┆ 0.0000       ┆ 100.0000    │
│ 7         ┆ 2     ┆ 2.2361              ┆ 27.5000   ┆ 121.0000   ┆ 3.0000  ┆ 0.0000  ┆ 0.9112            ┆ 12.8759             ┆ 8.5000          ┆ 0.0000    ┆ 0.0000             ┆ 1.9271       ┆ 7.5000              ┆ 0.0000        ┆ 0.0000        ┆ 1.0000        ┆ 0.0000        ┆ 0.0000           ┆ 8.5000          ┆ 0.0000         ┆ 0.0000          ┆ 8.5000          ┆ 7.0000            ┆ 61.5000         ┆ 1.2252          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000     ┆ 0.0647 ┆ 94.3450 ┆ -7.9376 ┆ 2.1293  ┆ 10.0669 ┆ 1743.1097 ┆ 7.0483 ┆ -9119.4609  ┆ -9119.1436  ┆ -9119.1182  ┆ -9120.4697  ┆ 42.7180 ┆ -106.9751 ┆ -107.7180 ┆ -108.3992 ┆ -99.1114 ┆ 2.7574  ┆ 1.0430 ┆ 0.8056 ┆ 2.0000      ┆ 0.0000    ┆ 0.0000          ┆ 0.0000             ┆ 0.0000       ┆ 100.0000    │
│ 8         ┆ 3     ┆ 1.6667              ┆ 10.0000   ┆ 115.0000   ┆ 0.0000  ┆ 43.0000 ┆ 1.1480            ┆ 13.1431             ┆ 8.0000          ┆ 1.0000    ┆ 1.0000             ┆ 2.0000       ┆ 0.0000              ┆ 0.0000        ┆ 1.0000        ┆ 0.0000        ┆ 0.0000        ┆ 3.0000           ┆ 4.0000          ┆ 0.0000         ┆ 4.0000          ┆ 0.0000          ┆ 5.0000            ┆ 16.6667         ┆ 1.2903          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 4.0000     ┆ 3.6444 ┆ 52.1333 ┆ -7.5067 ┆ -2.4581 ┆ 5.0486  ┆ 799.6914  ┆ 1.6328 ┆ -12478.4749 ┆ -12478.3138 ┆ -12478.2874 ┆ -12479.2998 ┆ 21.7127 ┆ -47.7864  ┆ -48.0103  ┆ -48.2416  ┆ -44.8225 ┆ 4.3867  ┆ 1.9670 ┆ 1.3163 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 9         ┆ 2     ┆ 1.7692              ┆ 13.0000   ┆ 120.0000   ┆ 0.0000  ┆ 31.5000 ┆ 1.1364            ┆ 12.3425             ┆ 9.0000          ┆ 1.5000    ┆ 0.0000             ┆ 2.0769       ┆ 0.0000              ┆ 0.2857        ┆ 0.5000        ┆ 0.2143        ┆ 0.0000        ┆ 2.0000           ┆ 5.0000          ┆ 2.0000         ┆ 3.5000          ┆ 1.5000          ┆ 6.0000            ┆ 23.0000         ┆ 1.2945          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 1.5000    ┆ 0.5000   ┆ 0.0000   ┆ 2.0000     ┆ 3.9871 ┆ 73.6950 ┆ -6.6654 ┆ -2.4844 ┆ 4.1810  ┆ 1106.2077 ┆ 2.3845 ┆ -11412.6943 ┆ -11412.4868 ┆ -11412.4609 ┆ -11413.5732 ┆ 28.4315 ┆ -63.9774  ┆ -64.2712  ┆ -64.5796  ┆ -60.1122 ┆ 3.8527  ┆ 1.2476 ┆ 1.0164 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
│ 10        ┆ 2     ┆ 2.0000              ┆ 13.0000   ┆ 128.0000   ┆ -0.5000 ┆ 53.5000 ┆ 1.1671            ┆ 12.7052             ┆ 9.0000          ┆ 2.0000    ┆ 0.0000             ┆ 2.1538       ┆ 0.0000              ┆ 0.0000        ┆ 0.4000        ┆ 0.6000        ┆ 0.0000        ┆ 4.0000           ┆ 5.0000          ┆ 0.0000         ┆ 2.0000          ┆ 3.0000          ┆ 5.0000            ┆ 26.0000         ┆ 1.3162          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 1.0000   ┆ 1.0000    ┆ 2.0000   ┆ 0.0000   ┆ 4.0000     ┆ 2.2846 ┆ 57.9100 ┆ -7.3974 ┆ -1.5878 ┆ 5.8110  ┆ 933.2747  ┆ 2.4413 ┆ -13435.1538 ┆ -13434.9707 ┆ -13434.9448 ┆ -13436.0107 ┆ 25.3055 ┆ -60.9410  ┆ -61.2587  ┆ -61.5670  ┆ -57.0320 ┆ 3.1486  ┆ 1.5293 ┆ 1.3479 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
└───────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴─────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴───────────┴───────────┴───────────┴──────────┴─────────┴────────┴────────┴─────────────┴───────────┴─────────────────┴────────────────────┴──────────────┴─────────────┘

# KMeans

In [27]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
X = np.array(df['acsf_embedding'].to_list())
labels_kmeans = kmeans.fit_predict(X)
df = df.with_columns(labels_kmeans=labels_kmeans)
print(np.unique(labels_kmeans, return_counts=True))

(array([0, 1, 2], dtype=int32), array([1818, 1038, 2144]))

In [29]:
create_chemiscope_viewer(df, X, labels_kmeans, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [30]:
average_numeric_by_cluster(df, 'labels_kmeans')

shape: (3, 63)
┌───────────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────┐
│ labels_kmeans ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ labels_spectral ┆ labels_db ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---           ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---         │
│ i32           ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64         │
╞═══════════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════╡
│ 0             ┆ 1818  ┆ 2.2301              ┆ 20.7794   ┆ 123.7761   ┆ 0.3905  ┆ 22.6139 ┆ 0.9113            ┆ 12.8208             ┆ 8.8388          ┆ 1.9373    ┆ 0.0033             ┆ 2.0795       ┆ 2.6529              ┆ 0.0245        ┆ 0.0713        ┆ 0.9042        ┆ 0.7816        ┆ 1.2761           ┆ 7.4576          ┆ 0.1832         ┆ 0.5242          ┆ 6.5303          ┆ 6.3432            ┆ 46.2871         ┆ 1.2590          ┆ 0.0006     ┆ 0.3790     ┆ 0.0000    ┆ 0.0726   ┆ 0.0418   ┆ 0.0011             ┆ 0.0099   ┆ 0.0759    ┆ 0.4857   ┆ 0.0000   ┆ 1.6012     ┆ 2.0663 ┆ 80.4006 ┆ -6.4925 ┆ 1.1361  ┆ 7.6286 ┆ 1218.8450 ┆ 4.9250 ┆ -10684.9590 ┆ -10684.7184 ┆ -10684.6927 ┆ -10685.8718 ┆ 33.7937 ┆ -85.5431 ┆ -86.1033 ┆ -86.6117 ┆ -79.4769 ┆ 3.0402 ┆ 1.3971 ┆ 1.1564 ┆ 1.5391      ┆ 0.0022    ┆ 0.0017          ┆ 0.0055    ┆ 92.0242            ┆ 0.3300       ┆ 7.6458      │
│ 1             ┆ 1038  ┆ 1.8715              ┆ 14.7842   ┆ 119.0896   ┆ -0.0723 ┆ 52.4644 ┆ 0.7645            ┆ 12.8809             ┆ 8.5809          ┆ 1.1098    ┆ 0.4538             ┆ 2.0108       ┆ 1.7418              ┆ 0.1332        ┆ 0.4944        ┆ 0.3724        ┆ 1.0636        ┆ 2.7033           ┆ 5.3921          ┆ 0.7938         ┆ 2.5010          ┆ 1.9971          ┆ 6.3526            ┆ 27.7881         ┆ 1.2616          ┆ 0.0039     ┆ 0.1830     ┆ 0.1012    ┆ 0.2765   ┆ 0.2582   ┆ 0.0019             ┆ 0.0694   ┆ 0.1484    ┆ 0.3911   ┆ 0.0010   ┆ 3.2890     ┆ 3.2123 ┆ 69.8275 ┆ -6.4890 ┆ -0.5905 ┆ 5.8985 ┆ 1142.2715 ┆ 3.0646 ┆ -11382.6863 ┆ -11382.4664 ┆ -11382.4407 ┆ -11383.5901 ┆ 29.0603 ┆ -65.2672 ┆ -65.6172 ┆ -65.9714 ┆ -60.9361 ┆ 4.1297 ┆ 1.4310 ┆ 1.0815 ┆ 0.2437      ┆ 1.0337    ┆ 0.0000          ┆ 0.1416    ┆ 39.0173            ┆ 43.0636      ┆ 17.9191     │
│ 2             ┆ 2144  ┆ 2.0988              ┆ 17.7523   ┆ 123.2421   ┆ -0.0975 ┆ 38.7239 ┆ 0.8990            ┆ 12.8260             ┆ 8.7994          ┆ 1.7267    ┆ 0.0452             ┆ 2.0719       ┆ 2.3111              ┆ 0.0750        ┆ 0.1671        ┆ 0.7579        ┆ 0.9538        ┆ 2.1651           ┆ 6.3102          ┆ 0.5084         ┆ 1.0490          ┆ 4.7239          ┆ 6.3246            ┆ 37.2332         ┆ 1.2652          ┆ 0.0009     ┆ 0.4389     ┆ 0.0070    ┆ 0.1217   ┆ 0.1325   ┆ 0.0019             ┆ 0.0541   ┆ 0.1628    ┆ 0.7076   ┆ 0.0000   ┆ 2.5182     ┆ 2.8351 ┆ 73.8084 ┆ -6.6054 ┆ 0.2013  ┆ 6.8067 ┆ 1178.2535 ┆ 3.9585 ┆ -11347.0579 ┆ -11346.8260 ┆ -11346.8003 ┆ -11347.9695 ┆ 31.6204 ┆ -75.1007 ┆ -75.5531 ┆ -75.9837 ┆ -69.9043 ┆ 3.3055 ┆ 1.3946 ┆ 1.1309 ┆ 1.0126      ┆ 1.9109    ┆ 0.0014          ┆ -0.0005   ┆ 85.3078            ┆ 4.5243       ┆ 10.1679     │
└───────────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴───────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────┘