In [1]:
import os
os.chdir('../../../../..')

In [2]:
import numpy as np

from sklearn.cluster import AgglomerativeClustering, SpectralClustering, DBSCAN, KMeans
from kmedoids import KMedoids

from src.datasets import QM9Dataset
from src.helper_functions import plot_molecules_with_py3dmol, create_chemiscope_viewer, plot_distance_matrix_projection, evaluate_distance_matrix_clustering_sweep, average_numeric_by_cluster

In [3]:
qm9 = QM9Dataset(limit=5000, sampling_strategy="stratified", stratify_by=["num_atoms", "gap"], add_morgan_fingerprint=True)
molecules = qm9.get_molecules()
df = qm9.load()

2026-04-21 15:21:35.163 | INFO     | src.datasets:load:500 - Loading cached full QM9 dataset from: data/QM9/dataset_cleaned.parquet
2026-04-21 15:21:35.405 | INFO     | src.datasets:_sample_qm9_df:692 - QM9 sampling complete: strategy=stratified, requested_limit=5000, returned_rows=5000.
2026-04-21 15:21:35.405 | INFO     | src.datasets:_add_requested_descriptors:129 - Applying requested QM9 descriptors to sampled dataframe (rows=5000).
2026-04-21 15:21:35.405 | INFO     | src.features:compute_morgan_fingerprints:76 - Computing Morgan Fingerprints (Radius=3, Size=2048)...
2026-04-21 15:21:44.628 | INFO     | src.datasets:_add_requested_descriptors:152 - Added descriptor column(s): ['morgan_fingerprint']
2026-04-21 15:22:08.471 | SUCCESS  | src.datasets:get_molecules:1185 - Saved 5000 molecules to data/QM9/qm9_subset.xyz (failed: 0, requested: 5000).
2026-04-21 15:22:08.473 | INFO     | src.datasets:load:500 - Loading cached full QM9 dataset from: data/QM9/dataset_cleaned.parquet
2026-04-21 15:22:08.626 | INFO     | src.datasets:_sample_qm9_df:692 - QM9 sampling complete: strategy=stratified, requested_limit=5000, returned_rows=5000.
2026-04-21 15:22:08.626 | INFO     | src.datasets:_add_requested_descriptors:129 - Applying requested QM9 descriptors to sampled dataframe (rows=5000).
2026-04-21 15:22:08.626 | INFO     | src.features:compute_morgan_fingerprints:76 - Computing Morgan Fingerprints (Radius=3, Size=2048)...
2026-04-21 15:22:18.104 | INFO     | src.datasets:_add_requested_descriptors:152 - Added descriptor column(s): ['morgan_fingerprint']

In [4]:
plot_molecules_with_py3dmol(molecules[0:3])

In [5]:
X = np.array(df['morgan_fingerprint'].to_list())

In [6]:
dist_matrix = qm9.get_distance_matrix(descriptor="morgan", dist_type="jaccard", force_calculate=True)

2026-04-21 15:22:59.331 | INFO     | src.datasets:get_distance_matrix:1016 - Calculating distance matrix for morgan using jaccard distance.
2026-04-21 15:23:17.627 | SUCCESS  | src.distance:_compute_and_save:79 - Saved distance matrix to data/QM9/dist_morgan_jaccard.npy

In [7]:
n = 10
triu_indices = np.triu_indices_from(dist_matrix, k=1)
distances = dist_matrix[triu_indices]
molecule_pairs = list(zip(triu_indices[0], triu_indices[1]))
smallest_indices = np.argsort(distances)[:n]
closest_pairs = [molecule_pairs[i] for i in smallest_indices]
print("Closest molecule pairs (indices):", closest_pairs)
mols = [(molecules[idx1], molecules[idx2]) for idx1, idx2 in closest_pairs]

Closest molecule pairs (indices): [(np.int64(4966), np.int64(4967)), (np.int64(593), np.int64(4376)), (np.int64(413), np.int64(4473)), (np.int64(143), np.int64(3070)), (np.int64(236), np.int64(960)), (np.int64(128), np.int64(593)), (np.int64(448), np.int64(2336)), (np.int64(617), np.int64(1931)), (np.int64(23), np.int64(146)), (np.int64(128), np.int64(4376))]

In [8]:
plot_molecules_with_py3dmol(mols[2])

# Determining the best number of clusters for each clustering method

In [5]:
out = evaluate_distance_matrix_clustering_sweep(
    dist_matrix=dist_matrix,
    fingerprint="morgan",
    distance_metric="tanimoto",
    dataset_name="qm9",
)

NameError: name 'dist_matrix' is not defined

# Hiercical Clustering on Distance Matrix

In [30]:
model_hier = AgglomerativeClustering(metric='precomputed', n_clusters=3, linkage='average')
labels_hier = model_hier.fit_predict(dist_matrix)
df = df.with_columns(labels_hier=labels_hier)
print(np.unique(labels_hier, return_counts=True))

(array([0, 1, 2]), array([ 938,    5, 4057]))

In [29]:
create_chemiscope_viewer(df, dist_matrix, labels_hier, 't-SNE')

Running t-SNE dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_t-SNE_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_t-SNE_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - t-SNE Clustering'}, settings={'map': {'x': {'property': 't-SNE_1'}, 'y'…

In [ ]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="morgan",
    distance_metric="tanimoto",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_hier,
    clustering_method="hierarchical"
)

2026-04-21 13:37:17.864 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/tanimoto/morgan/pca_hierarchical_projection.png

{'coords': array([[ 1.21527925,  1.71274172],
        [ 1.98816896, -1.69302976],
        [-0.2607709 , -0.32863902],
        ...,
        [ 2.57937249, -1.84158736],
        [-0.4344677 , -0.38770645],
        [ 2.69716913, -1.57512399]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/tanimoto/morgan/pca_hierarchical_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/tanimoto/morgan'),
 'clustering_method': 'hierarchical'}

In [31]:
average_numeric_by_cluster(df, "labels_hier")

shape: (3, 62)
┌─────────────┬───────┬─────────────────────┬───────────┬────────────┬────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬────────────────────┬──────────────┬─────────────┬──────────────────┬──────────────┬──────────────────┐
│ labels_hier ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp   ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic ┆ unique_scaffolds ┆ top_scaffold ┆ top_scaffold_pct │
│ ---         ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---    ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---                ┆ ---          ┆ ---         ┆ ---              ┆ ---          ┆ ---              │
│ i64         ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64    ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64                ┆ f64          ┆ f64         ┆ u32              ┆ str          ┆ f64              │
╞═════════════╪═══════╪═════════════════════╪═══════════╪════════════╪════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪════════════════════╪══════════════╪═════════════╪══════════════════╪══════════════╪══════════════════╡
│ 0           ┆ 938   ┆ 1.8624              ┆ 15.5853   ┆ 121.7825   ┆ 0.2292 ┆ 49.8923 ┆ 0.6711            ┆ 12.9649             ┆ 8.7783          ┆ 1.2601    ┆ 0.9296             ┆ 2.0332       ┆ 2.0256              ┆ 0.0359        ┆ 0.6586        ┆ 0.3055        ┆ 1.0309        ┆ 2.8721           ┆ 6.0981          ┆ 0.2122         ┆ 3.3934          ┆ 1.7079          ┆ 6.3443            ┆ 29.3166         ┆ 1.2591          ┆ 0.0160     ┆ 0.1130     ┆ 0.1759    ┆ 0.2420   ┆ 0.0373   ┆ 0.0000             ┆ 0.0245   ┆ 0.0224    ┆ 0.2345   ┆ 0.0160   ┆ 3.4648     ┆ 3.1048 ┆ 72.4444 ┆ -6.1469 ┆ -0.3498 ┆ 5.7971 ┆ 1143.2198 ┆ 3.3162 ┆ -11505.4402 ┆ -11505.2248 ┆ -11505.1992 ┆ -11506.3347 ┆ 29.0662 ┆ -68.0722 ┆ -68.4576 ┆ -68.8324 ┆ -63.4757 ┆ 3.9035 ┆ 1.4447 ┆ 1.0480 ┆ 11.7271            ┆ 88.2729      ┆ 0.0000      ┆ 344              ┆ c1cc[nH]c1   ┆ 8.1023           │
│ 1           ┆ 5     ┆ 2.1717              ┆ 18.6000   ┆ 104.8000   ┆ 1.0000 ┆ 10.8000 ┆ 0.9678            ┆ 12.8218             ┆ 7.4000          ┆ 1.4000    ┆ 0.0000             ┆ 2.0401       ┆ 0.0000              ┆ 0.0000        ┆ 0.0571        ┆ 0.9429        ┆ 0.0000        ┆ 1.2000           ┆ 6.2000          ┆ 0.0000         ┆ 0.4000          ┆ 5.8000          ┆ 5.4000            ┆ 40.4000         ┆ 1.2533          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 1.2000   ┆ 0.0000   ┆ 1.2000     ┆ 0.8256 ┆ 68.1600 ┆ -6.8371 ┆ 1.9870  ┆ 8.8247 ┆ 819.3302  ┆ 4.5404 ┆ -9064.3778  ┆ -9064.1928  ┆ -9064.1671  ┆ -9065.2147  ┆ 26.5914 ┆ -75.6261 ┆ -76.1579 ┆ -76.6103 ┆ -70.2739 ┆ 3.7325 ┆ 2.9226 ┆ 1.8579 ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      ┆ 5                ┆ C1CCCOCC1    ┆ 20.0000          │
│ 2           ┆ 4057  ┆ 2.1338              ┆ 18.5930   ┆ 123.0486   ┆ 0.0653 ┆ 33.7671 ┆ 0.8976            ┆ 12.8295             ┆ 8.7890          ┆ 1.7286    ┆ 0.0084             ┆ 2.0666       ┆ 2.3737              ┆ 0.0713        ┆ 0.1384        ┆ 0.7903        ┆ 0.8930        ┆ 1.8292           ┆ 6.6044          ┆ 0.4740         ┆ 0.8459          ┆ 5.2356          ┆ 6.3562            ┆ 39.8415         ┆ 1.2633          ┆ 0.0000     ┆ 0.3902     ┆ 0.0007    ┆ 0.1048   ┆ 0.1472   ┆ 0.0022             ┆ 0.0429   ┆ 0.1462    ┆ 0.5854   ┆ 0.0000   ┆ 2.2334     ┆ 2.6003 ┆ 75.8065 ┆ -6.6257 ┆ 0.4500  ┆ 7.0757 ┆ 1203.4571 ┆ 4.2285 ┆ -11107.4289 ┆ -11107.1938 ┆ -11107.1681 ┆ -11108.3429 ┆ 32.2728 ┆ -77.9804 ┆ -78.4619 ┆ -78.9141 ┆ -72.5470 ┆ 3.2902 ┆ 1.3890 ┆ 1.1323 ┆ 86.2953            ┆ 0.8381       ┆ 12.8667     ┆ 1226             ┆ Acyclic      ┆ 12.8667          │
└─────────────┴───────┴─────────────────────┴───────────┴────────────┴────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴────────────────────┴──────────────┴─────────────┴──────────────────┴──────────────┴──────────────────┘

shape: (3, 62)
┌────────────┬───────┬────────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ labels_hie ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ pct_acycli ┆ unique_sc ┆ top_scaff ┆ top_scaff │
│ r          ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ c          ┆ affolds   ┆ old       ┆ old_pct   │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ i64        ┆       ┆ f64        ┆           ┆   ┆ f64        ┆ u32       ┆ str       ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 938   ┆ 1.862363   ┆ 15.585288 ┆ … ┆ 0.0        ┆ 344       ┆ c1cc[nH]c ┆ 8.102345  │
│            ┆       ┆            ┆           ┆   ┆            ┆           ┆ 1         ┆           │
│ 1          ┆ 5     ┆ 2.1717     ┆ 18.6      ┆ … ┆ 0.0        ┆ 5         ┆ C1CCCOCC1 ┆ 20.0      │
│ 2          ┆ 4057  ┆ 2.13382    ┆ 18.593049 ┆ … ┆ 12.86665   ┆ 1226      ┆ Acyclic   ┆ 12.86665  │
└────────────┴───────┴────────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘

# KMedoids

In [35]:
model_km = KMedoids(n_clusters=20, metric="precomputed")
labels_km = model_km.fit_predict(dist_matrix)
df = df.with_columns(labels_km=labels_km)

In [37]:
create_chemiscope_viewer(df, dist_matrix, labels_km, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [16]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="morgan",
    distance_metric="tanimoto",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_km,
    clustering_method="kmedoids"
)

2026-04-21 13:37:43.075 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/tanimoto/morgan/pca_kmedoids_projection.png

{'coords': array([[ 1.21527925,  1.71274172],
        [ 1.98816896, -1.69302976],
        [-0.2607709 , -0.32863902],
        ...,
        [ 2.57937249, -1.84158736],
        [-0.4344677 , -0.38770645],
        [ 2.69716913, -1.57512399]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/tanimoto/morgan/pca_kmedoids_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/tanimoto/morgan'),
 'clustering_method': 'kmedoids'}

In [36]:
average_numeric_by_cluster(df, "labels_km")

shape: (20, 64)
┌───────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────────┬────────────────────┬──────────────┬─────────────┬──────────────────┬──────────────┬──────────────────┐
│ labels_km ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ kmeans_labels ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic ┆ unique_scaffolds ┆ top_scaffold ┆ top_scaffold_pct │
│ ---       ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---           ┆ ---                ┆ ---          ┆ ---         ┆ ---              ┆ ---          ┆ ---              │
│ u64       ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64           ┆ f64                ┆ f64          ┆ f64         ┆ u32              ┆ str          ┆ f64              │
╞═══════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════════╪════════════════════╪══════════════╪═════════════╪══════════════════╪══════════════╪══════════════════╡
│ 0         ┆ 207   ┆ 1.8655              ┆ 15.1111   ┆ 121.1594   ┆ 0.1932  ┆ 48.5411 ┆ 0.6830            ┆ 12.9525             ┆ 8.7681          ┆ 1.1691    ┆ 0.9420             ┆ 2.0220       ┆ 1.5411              ┆ 0.0285        ┆ 0.7524        ┆ 0.2190        ┆ 0.9855        ┆ 2.4251           ┆ 6.3623          ┆ 0.1739         ┆ 3.9227          ┆ 1.2560          ┆ 6.1159            ┆ 28.4541         ┆ 1.2587          ┆ 0.0097     ┆ 0.0386     ┆ 0.0580    ┆ 0.1401   ┆ 0.1111   ┆ 0.0000             ┆ 0.0097   ┆ 0.0580    ┆ 0.0580   ┆ 0.0193   ┆ 3.4155     ┆ 3.8673 ┆ 72.9783 ┆ -6.1874 ┆ -0.7434 ┆ 5.4439 ┆ 1118.2415 ┆ 3.1716 ┆ -11479.2830 ┆ -11479.0720 ┆ -11479.0463 ┆ -11480.1723 ┆ 28.5018 ┆ -67.3500 ┆ -67.7214 ┆ -68.0840 ┆ -62.8876 ┆ 3.7135 ┆ 1.5011 ┆ 1.0481 ┆ 0.2802      ┆ 0.9372        ┆ 10.6280            ┆ 89.3720      ┆ 0.0000      ┆ 110              ┆ c1cc[nH]c1   ┆ 12.0773          │
│ 1         ┆ 328   ┆ 2.2048              ┆ 19.1707   ┆ 123.4146   ┆ 0.1433  ┆ 26.0000 ┆ 0.9276            ┆ 12.8102             ┆ 8.8079          ┆ 2.5640    ┆ 0.0183             ┆ 2.1411       ┆ 1.9482              ┆ 0.0111        ┆ 0.0758        ┆ 0.9131        ┆ 0.7805        ┆ 1.6433           ┆ 7.1159          ┆ 0.0793         ┆ 0.5396          ┆ 6.2073          ┆ 6.3415            ┆ 42.2927         ┆ 1.2721          ┆ 0.0000     ┆ 0.4055     ┆ 0.0000    ┆ 0.0762   ┆ 0.0213   ┆ 0.0000             ┆ 0.0000   ┆ 0.0244    ┆ 0.9604   ┆ 0.0000   ┆ 1.9817     ┆ 1.9087 ┆ 75.7499 ┆ -6.4862 ┆ 1.2311  ┆ 7.7174 ┆ 1092.3847 ┆ 4.4477 ┆ -11012.7655 ┆ -11012.5511 ┆ -11012.5255 ┆ -11013.6483 ┆ 30.7604 ┆ -79.8774 ┆ -80.4019 ┆ -80.8689 ┆ -74.2466 ┆ 3.1722 ┆ 1.5967 ┆ 1.3284 ┆ 1.9268      ┆ 1.9055        ┆ 98.1707            ┆ 1.8293       ┆ 0.0000      ┆ 230              ┆ C1CO1        ┆ 2.7439           │
│ 2         ┆ 235   ┆ 1.9942              ┆ 18.6681   ┆ 122.9234   ┆ 0.1064  ┆ 48.4511 ┆ 0.8323            ┆ 12.9248             ┆ 8.6851          ┆ 0.2681    ┆ 0.0596             ┆ 1.9210       ┆ 4.5021              ┆ 0.1978        ┆ 0.0928        ┆ 0.7094        ┆ 1.2383        ┆ 2.4000           ┆ 5.1915          ┆ 1.1830         ┆ 0.4979          ┆ 4.3064          ┆ 6.9489            ┆ 37.6043         ┆ 1.2384          ┆ 0.0000     ┆ 0.8553     ┆ 0.0043    ┆ 0.1191   ┆ 0.0851   ┆ 0.0000             ┆ 0.0213   ┆ 0.0723    ┆ 0.3064   ┆ 0.0000   ┆ 2.6979     ┆ 3.2670 ┆ 75.3591 ┆ -7.1350 ┆ 0.3076  ┆ 7.4427 ┆ 1485.8392 ┆ 4.2260 ┆ -11264.6611 ┆ -11264.3895 ┆ -11264.3639 ┆ -11265.6338 ┆ 35.1132 ┆ -77.0528 ┆ -77.5007 ┆ -77.9548 ┆ -71.6614 ┆ 3.6544 ┆ 1.0368 ┆ 0.8459 ┆ 1.8809      ┆ 1.9362        ┆ 20.4255            ┆ 5.9574       ┆ 73.6170     ┆ 24               ┆ Acyclic      ┆ 73.6170          │
│ 3         ┆ 138   ┆ 2.1711              ┆ 18.5290   ┆ 122.5652   ┆ 0.2319  ┆ 25.0145 ┆ 0.9302            ┆ 12.8118             ┆ 8.7536          ┆ 2.3551    ┆ 0.0435             ┆ 2.1301       ┆ 0.9130              ┆ 0.0304        ┆ 0.0824        ┆ 0.8872        ┆ 0.3841        ┆ 1.7609           ┆ 6.7319          ┆ 0.2101         ┆ 0.5435          ┆ 5.9058          ┆ 6.1449            ┆ 40.3913         ┆ 1.2751          ┆ 0.0000     ┆ 0.0942     ┆ 0.0000    ┆ 0.0652   ┆ 0.0290   ┆ 0.0000             ┆ 0.0145   ┆ 0.0290    ┆ 1.2971   ┆ 0.0000   ┆ 2.0942     ┆ 2.0852 ┆ 74.2679 ┆ -6.5820 ┆ 1.1205  ┆ 7.7027 ┆ 1079.4537 ┆ 4.2761 ┆ -11054.5149 ┆ -11054.3109 ┆ -11054.2852 ┆ -11055.3914 ┆ 29.1336 ┆ -77.8476 ┆ -78.3577 ┆ -78.8082 ┆ -72.4010 ┆ 3.4635 ┆ 1.6150 ┆ 1.3126 ┆ 1.8696      ┆ 1.7464        ┆ 95.6522            ┆ 4.3478       ┆ 0.0000      ┆ 123              ┆ C1OC2CC1C2   ┆ 2.1739           │
│ 4         ┆ 248   ┆ 2.1677              ┆ 20.1976   ┆ 125.9677   ┆ 0.1331  ┆ 30.9395 ┆ 0.9339            ┆ 12.8468             ┆ 8.8992          ┆ 2.0161    ┆ 0.0242             ┆ 2.0897       ┆ 3.3468              ┆ 0.0108        ┆ 0.0613        ┆ 0.9279        ┆ 1.0363        ┆ 1.8831           ┆ 7.0242          ┆ 0.0726         ┆ 0.4032          ┆ 6.3105          ┆ 6.6895            ┆ 43.8669         ┆ 1.2612          ┆ 0.0000     ┆ 0.7097     ┆ 0.0040    ┆ 0.0484   ┆ 0.0081   ┆ 0.0040             ┆ 0.0121   ┆ 0.0242    ┆ 0.8468   ┆ 0.0000   ┆ 2.1129     ┆ 2.1320 ┆ 77.9342 ┆ -6.5097 ┆ 1.3725  ┆ 7.8823 ┆ 1260.3571 ┆ 4.7089 ┆ -11294.0282 ┆ -11293.7813 ┆ -11293.7557 ┆ -11294.9520 ┆ 34.1041 ┆ -82.6254 ┆ -83.1569 ┆ -83.6504 ┆ -76.7270 ┆ 3.1311 ┆ 1.2702 ┆ 1.0624 ┆ 1.9113      ┆ 1.8911        ┆ 97.5806            ┆ 2.4194       ┆ 0.0000      ┆ 118              ┆ C1COC1       ┆ 8.0645           │
│ 5         ┆ 168   ┆ 2.1145              ┆ 19.2500   ┆ 124.0774   ┆ 0.0417  ┆ 43.9940 ┆ 0.8340            ┆ 12.9185             ┆ 8.7798          ┆ 1.0238    ┆ 0.0179             ┆ 1.9950       ┆ 3.0476              ┆ 0.0484        ┆ 0.2260        ┆ 0.7256        ┆ 1.0238        ┆ 1.6429           ┆ 6.8810          ┆ 0.2917         ┆ 1.2381          ┆ 4.6786          ┆ 6.9940            ┆ 40.9702         ┆ 1.2519          ┆ 0.0000     ┆ 0.1488     ┆ 0.0000    ┆ 0.5714   ┆ 0.7024   ┆ 0.0238             ┆ 0.0238   ┆ 0.2024    ┆ 0.2917   ┆ 0.0000   ┆ 2.5714     ┆ 2.9923 ┆ 76.9310 ┆ -6.6094 ┆ 0.2468  ┆ 6.8562 ┆ 1394.6039 ┆ 4.4277 ┆ -11236.8315 ┆ -11236.5747 ┆ -11236.5490 ┆ -11237.7874 ┆ 34.1521 ┆ -79.7155 ┆ -80.2006 ┆ -80.6697 ┆ -74.1301 ┆ 3.6780 ┆ 1.1152 ┆ 0.9242 ┆ 1.9643      ┆ 1.8988        ┆ 75.0000            ┆ 1.7857       ┆ 23.2143     ┆ 47               ┆ Acyclic      ┆ 23.2143          │
│ 6         ┆ 267   ┆ 2.1621              ┆ 18.5243   ┆ 124.5281   ┆ -0.0899 ┆ 35.1236 ┆ 0.9290            ┆ 12.8226             ┆ 8.8577          ┆ 1.7341    ┆ 0.0000             ┆ 2.0693       ┆ 2.7079              ┆ 0.0165        ┆ 0.1952        ┆ 0.7883        ┆ 0.7978        ┆ 1.9888           ┆ 6.8914          ┆ 0.1049         ┆ 1.2210          ┆ 5.1610          ┆ 6.0375            ┆ 40.1760         ┆ 1.2651          ┆ 0.0000     ┆ 0.3558     ┆ 0.0000    ┆ 0.0262   ┆ 0.1348   ┆ 0.0037             ┆ 0.0000   ┆ 0.0749    ┆ 0.4270   ┆ 0.0000   ┆ 2.3708     ┆ 2.8700 ┆ 75.4270 ┆ -6.6301 ┆ -0.3919 ┆ 6.2383 ┆ 1207.0635 ┆ 4.1689 ┆ -11396.4495 ┆ -11396.2087 ┆ -11396.1831 ┆ -11397.3716 ┆ 32.6266 ┆ -77.7058 ┆ -78.1790 ┆ -78.6294 ┆ -72.2920 ┆ 3.0935 ┆ 1.3121 ┆ 1.0822 ┆ 2.0000      ┆ 1.8052        ┆ 97.7528            ┆ 0.0000       ┆ 2.2472      ┆ 117              ┆ C1CC1        ┆ 13.4831          │
│ 7         ┆ 367   ┆ 2.0974              ┆ 18.5286   ┆ 121.4659   ┆ 0.0899  ┆ 24.6785 ┆ 0.9292            ┆ 12.7249             ┆ 8.8365          ┆ 1.9782    ┆ 0.0000             ┆ 2.0910       ┆ 1.9864              ┆ 0.1892        ┆ 0.0696        ┆ 0.7413        ┆ 1.0627        ┆ 1.3215           ┆ 6.3025          ┆ 1.3678         ┆ 0.5150          ┆ 5.3433          ┆ 6.5368            ┆ 38.9946         ┆ 1.2642          ┆ 0.0000     ┆ 0.6131     ┆ 0.0000    ┆ 0.0490   ┆ 0.0327   ┆ 0.0000             ┆ 0.0054   ┆ 0.0518    ┆ 0.3488   ┆ 0.0000   ┆ 1.6104     ┆ 1.7599 ┆ 78.7165 ┆ -6.4678 ┆ 0.8153  ┆ 7.2831 ┆ 1149.1900 ┆ 4.1822 ┆ -10648.6024 ┆ -10648.3671 ┆ -10648.3414 ┆ -10649.5043 ┆ 33.1470 ┆ -78.4621 ┆ -78.9409 ┆ -79.3915 ┆ -73.0377 ┆ 3.0883 ┆ 1.4210 ┆ 1.1823 ┆ 1.9564      ┆ 1.8883        ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      ┆ 154              ┆ C1CC1        ┆ 10.8992          │
│ 8         ┆ 210   ┆ 2.0120              ┆ 18.0238   ┆ 124.2429   ┆ 0.0143  ┆ 47.5048 ┆ 0.8868            ┆ 12.9508             ┆ 8.6524          ┆ 0.1905    ┆ 0.0476             ┆ 1.9086       ┆ 4.2905              ┆ 0.0608        ┆ 0.3205        ┆ 0.6187        ┆ 0.8095        ┆ 2.5143           ┆ 5.7143          ┆ 0.3714         ┆ 1.5952          ┆ 3.5333          ┆ 7.0381            ┆ 36.5905         ┆ 1.2404          ┆ 0.0000     ┆ 0.2238     ┆ 0.0000    ┆ 0.1333   ┆ 0.4714   ┆ 0.0048             ┆ 0.1810   ┆ 0.2571    ┆ 0.6381   ┆ 0.0000   ┆ 3.1524     ┆ 2.8727 ┆ 72.3392 ┆ -6.8794 ┆ -0.5799 ┆ 6.2995 ┆ 1460.1833 ┆ 4.0099 ┆ -11820.6244 ┆ -11820.3541 ┆ -11820.3284 ┆ -11821.6073 ┆ 34.1155 ┆ -74.7781 ┆ -75.2024 ┆ -75.6399 ┆ -69.5827 ┆ 4.0315 ┆ 1.0431 ┆ 0.8545 ┆ 1.9048      ┆ 1.9381        ┆ 13.8095            ┆ 4.7619       ┆ 81.4286     ┆ 15               ┆ Acyclic      ┆ 81.4286          │
│ 9         ┆ 382   ┆ 2.1421              ┆ 17.3639   ┆ 120.4948   ┆ 0.0393  ┆ 39.4450 ┆ 0.7588            ┆ 12.8218             ┆ 8.8220          ┆ 1.8770    ┆ 0.0105             ┆ 2.0843       ┆ 1.4974              ┆ 0.1661        ┆ 0.0777        ┆ 0.7561        ┆ 0.8220        ┆ 1.9084           ┆ 6.2225          ┆ 1.0550         ┆ 0.4974          ┆ 5.0236          ┆ 5.9450            ┆ 37.3665         ┆ 1.2703          ┆ 0.0026     ┆ 0.1309     ┆ 0.0000    ┆ 0.1440   ┆ 0.0131   ┆ 0.0000             ┆ 0.0052   ┆ 0.0812    ┆ 0.3115   ┆ 0.0000   ┆ 2.2461     ┆ 3.6605 ┆ 75.6720 ┆ -6.9347 ┆ 0.1811  ┆ 7.1157 ┆ 1130.5633 ┆ 3.8533 ┆ -10625.1029 ┆ -10624.8781 ┆ -10624.8525 ┆ -10626.0015 ┆ 30.9504 ┆ -74.7922 ┆ -75.2367 ┆ -75.6572 ┆ -69.6941 ┆ 3.2061 ┆ 1.4237 ┆ 1.1731 ┆ 1.9267      ┆ 1.8403        ┆ 97.3822            ┆ 1.0471       ┆ 1.5707      ┆ 169              ┆ C1CC1        ┆ 8.6387           │
│ 10        ┆ 158   ┆ 2.1499              ┆ 19.3481   ┆ 123.0443   ┆ -0.0633 ┆ 35.2848 ┆ 0.9081            ┆ 12.8873             ┆ 8.6835          ┆ 1.5063    ┆ 0.0063             ┆ 2.0485       ┆ 2.9557              ┆ 0.0334        ┆ 0.1181        ┆ 0.8485        ┆ 1.4430        ┆ 1.8291           ┆ 6.7215          ┆ 0.2278         ┆ 0.7215          ┆ 5.4873          ┆ 6.9241            ┆ 41.7025         ┆ 1.2565          ┆ 0.0000     ┆ 0.9177     ┆ 0.0000    ┆ 0.0380   ┆ 0.1076   ┆ 0.0000             ┆ 0.0063   ┆ 0.1139    ┆ 0.2785   ┆ 0.0000   ┆ 2.2468     ┆ 2.3892 ┆ 75.9775 ┆ -6.6377 ┆ 0.8797  ┆ 7.5174 ┆ 1317.2194 ┆ 4.4997 ┆ -11100.2775 ┆ -11100.0386 ┆ -11100.0129 ┆ -11101.2011 ┆ 32.5488 ┆ -79.4902 ┆ -79.9970 ┆ -80.4686 ┆ -73.8589 ┆ 3.7937 ┆ 1.1972 ┆ 0.9891 ┆ 1.9304      ┆ 1.6835        ┆ 98.1013            ┆ 0.6329       ┆ 1.2658      ┆ 86               ┆ C1CC1        ┆ 17.7215          │
│ 11        ┆ 268   ┆ 1.8544              ┆ 15.6269   ┆ 122.2910   ┆ 0.2537  ┆ 53.0672 ┆ 0.6476            ┆ 13.0023             ┆ 8.7799          ┆ 1.1716    ┆ 1.0000             ┆ 2.0242       ┆ 2.4216              ┆ 0.0293        ┆ 0.6782        ┆ 0.2926        ┆ 0.8918        ┆ 3.2687           ┆ 6.0000          ┆ 0.1642         ┆ 3.3769          ┆ 1.6007          ┆ 6.5485            ┆ 29.3284         ┆ 1.2565          ┆ 0.0112     ┆ 0.0709     ┆ 0.0522    ┆ 0.5075   ┆ 0.0261   ┆ 0.0000             ┆ 0.0000   ┆ 0.0075    ┆ 0.2276   ┆ 0.0261   ┆ 3.6381     ┆ 3.0740 ┆ 72.5827 ┆ -6.0868 ┆ -0.4080 ┆ 5.6787 ┆ 1183.3959 ┆ 3.3235 ┆ -11608.1661 ┆ -11607.9474 ┆ -11607.9217 ┆ -11609.0663 ┆ 29.3198 ┆ -67.6399 ┆ -68.0235 ┆ -68.3994 ┆ -63.0346 ┆ 4.1672 ┆ 1.3553 ┆ 1.0089 ┆ 0.0448      ┆ 1.0187        ┆ 4.4776             ┆ 94.7761      ┆ 0.7463      ┆ 100              ┆ c1cocn1      ┆ 11.9403          │
│ 12        ┆ 175   ┆ 2.1024              ┆ 17.0629   ┆ 122.4914   ┆ -0.2000 ┆ 40.1657 ┆ 0.8909            ┆ 12.8323             ┆ 8.7429          ┆ 1.7771    ┆ 0.0343             ┆ 2.0712       ┆ 1.7943              ┆ 0.0420        ┆ 0.2508        ┆ 0.7072        ┆ 0.9257        ┆ 2.2343           ┆ 6.4514          ┆ 0.2571         ┆ 1.4629          ┆ 4.3600          ┆ 6.1714            ┆ 36.0743         ┆ 1.2700          ┆ 0.0000     ┆ 0.4743     ┆ 0.0057    ┆ 0.0686   ┆ 0.2171   ┆ 0.0000             ┆ 0.0000   ┆ 0.0857    ┆ 0.3371   ┆ 0.0000   ┆ 2.6629     ┆ 2.9437 ┆ 72.6183 ┆ -6.6531 ┆ -0.5821 ┆ 6.0709 ┆ 1188.3349 ┆ 3.7604 ┆ -11402.6696 ┆ -11402.4486 ┆ -11402.4229 ┆ -11403.5757 ┆ 29.9489 ┆ -72.7213 ┆ -73.1579 ┆ -73.5708 ┆ -67.7235 ┆ 3.6885 ┆ 1.3591 ┆ 1.1073 ┆ 1.9314      ┆ 1.6457        ┆ 94.8571            ┆ 3.4286       ┆ 1.7143      ┆ 115              ┆ C1CCC1       ┆ 6.2857           │
│ 13        ┆ 221   ┆ 2.1036              ┆ 17.1357   ┆ 124.9095   ┆ -0.2715 ┆ 42.5656 ┆ 0.9558            ┆ 12.8131             ┆ 8.8597          ┆ 2.1176    ┆ 0.0181             ┆ 2.1132       ┆ 1.6652              ┆ 0.0138        ┆ 0.2096        ┆ 0.7766        ┆ 1.0543        ┆ 2.4887           ┆ 6.4072          ┆ 0.0814         ┆ 1.2398          ┆ 4.7602          ┆ 5.8959            ┆ 36.1810         ┆ 1.2763          ┆ 0.0000     ┆ 0.6652     ┆ 0.0045    ┆ 0.0814   ┆ 0.1176   ┆ 0.0090             ┆ 0.0905   ┆ 0.5339    ┆ 0.7421   ┆ 0.0000   ┆ 2.7783     ┆ 2.7669 ┆ 70.8557 ┆ -6.6288 ┆ -0.1862 ┆ 6.4427 ┆ 1072.1298 ┆ 3.7535 ┆ -11824.2245 ┆ -11824.0034 ┆ -11823.9777 ┆ -11825.1184 ┆ 30.6535 ┆ -73.1315 ┆ -73.5709 ┆ -73.9856 ┆ -68.0875 ┆ 2.9501 ┆ 1.5553 ┆ 1.2223 ┆ 1.9005      ┆ 0.7466        ┆ 98.1900            ┆ 1.8100       ┆ 0.0000      ┆ 173              ┆ O=C1CC2CC12  ┆ 3.1674           │
│ 14        ┆ 279   ┆ 2.1573              ┆ 17.7061   ┆ 121.8853   ┆ -0.0824 ┆ 36.7061 ┆ 0.8269            ┆ 12.8476             ┆ 8.7742          ┆ 1.9892    ┆ 0.0502             ┆ 2.0990       ┆ 1.3011              ┆ 0.0224        ┆ 0.2625        ┆ 0.7151        ┆ 1.1254        ┆ 1.7097           ┆ 7.2545          ┆ 0.1470         ┆ 1.6057          ┆ 4.5591          ┆ 5.8244            ┆ 38.3297         ┆ 1.2721          ┆ 0.0000     ┆ 0.1111     ┆ 0.0036    ┆ 0.0573   ┆ 0.5161   ┆ 0.0000             ┆ 0.0466   ┆ 0.3477    ┆ 0.1685   ┆ 0.0000   ┆ 2.4624     ┆ 3.1947 ┆ 74.7122 ┆ -6.3652 ┆ -0.0425 ┆ 6.3227 ┆ 1087.2666 ┆ 3.9817 ┆ -11032.1280 ┆ -11031.9093 ┆ -11031.8836 ┆ -11033.0178 ┆ 30.5350 ┆ -75.7004 ┆ -76.1641 ┆ -76.5935 ┆ -70.4978 ┆ 3.1531 ┆ 1.5872 ┆ 1.2285 ┆ 1.9068      ┆ 0.3297        ┆ 94.9821            ┆ 5.0179       ┆ 0.0000      ┆ 205              ┆ O=C1CCN1     ┆ 5.0179           │
│ 15        ┆ 179   ┆ 1.9514              ┆ 18.6145   ┆ 120.3408   ┆ 0.3352  ┆ 28.2626 ┆ 0.9004            ┆ 12.7763             ┆ 8.6927          ┆ 0.3799    ┆ 0.0782             ┆ 1.9296       ┆ 3.7039              ┆ 0.2994        ┆ 0.1155        ┆ 0.5851        ┆ 0.7486        ┆ 1.5307           ┆ 5.1620          ┆ 2.0782         ┆ 0.7374          ┆ 4.0559          ┆ 7.3687            ┆ 36.8156         ┆ 1.2396          ┆ 0.0000     ┆ 0.3743     ┆ 0.0112    ┆ 0.0894   ┆ 0.1006   ┆ 0.0000             ┆ 0.0223   ┆ 0.1229    ┆ 0.2514   ┆ 0.0000   ┆ 1.8212     ┆ 2.2168 ┆ 79.8221 ┆ -6.7866 ┆ 0.2644  ┆ 7.0510 ┆ 1476.4880 ┆ 4.1860 ┆ -10633.9651 ┆ -10633.6956 ┆ -10633.6699 ┆ -10634.9306 ┆ 35.4736 ┆ -78.1578 ┆ -78.6057 ┆ -79.0584 ┆ -72.7847 ┆ 4.2854 ┆ 1.0366 ┆ 0.8831 ┆ 1.7989      ┆ 1.8939        ┆ 25.1397            ┆ 7.8212       ┆ 67.0391     ┆ 33               ┆ Acyclic      ┆ 67.0391          │
│ 16        ┆ 297   ┆ 1.8461              ┆ 15.7677   ┆ 121.1313   ┆ 0.2155  ┆ 52.1852 ┆ 0.6388            ┆ 12.9958             ┆ 8.7205          ┆ 1.1987    ┆ 0.9966             ┆ 2.0256       ┆ 2.4074              ┆ 0.0229        ┆ 0.7045        ┆ 0.2726        ┆ 1.5253        ┆ 2.6633           ┆ 6.2828          ┆ 0.1347         ┆ 3.5859          ┆ 1.5084          ┆ 6.4141            ┆ 29.4040         ┆ 1.2539          ┆ 0.0269     ┆ 0.1279     ┆ 0.4512    ┆ 0.1953   ┆ 0.0404   ┆ 0.0000             ┆ 0.0034   ┆ 0.0168    ┆ 0.1313   ┆ 0.0135   ┆ 3.4916     ┆ 2.8276 ┆ 72.7347 ┆ -5.9191 ┆ -0.0857 ┆ 5.8334 ┆ 1141.1057 ┆ 3.3845 ┆ -11383.3548 ┆ -11383.1354 ┆ -11383.1097 ┆ -11384.2519 ┆ 29.6126 ┆ -68.3885 ┆ -68.7768 ┆ -69.1563 ┆ -63.7471 ┆ 3.8323 ┆ 1.5116 ┆ 1.0642 ┆ 0.1347      ┆ 1.0067        ┆ 7.0707             ┆ 92.9293      ┆ 0.0000      ┆ 101              ┆ c1cn[nH]c1   ┆ 17.5084          │

shape: (20, 64)
┌───────────┬───────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ labels_km ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ pct_acycli ┆ unique_sca ┆ top_scaff ┆ top_scaff │
│ ---       ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ c          ┆ ffolds     ┆ old       ┆ old_pct   │
│ u64       ┆ u32   ┆ ---        ┆ f64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆       ┆ f64        ┆           ┆   ┆ f64        ┆ u32        ┆ str       ┆ f64       │
╞═══════════╪═══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0         ┆ 207   ┆ 1.865508   ┆ 15.111111 ┆ … ┆ 0.0        ┆ 110        ┆ c1cc[nH]c ┆ 12.077295 │
│           ┆       ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 1         ┆ 328   ┆ 2.204771   ┆ 19.170732 ┆ … ┆ 0.0        ┆ 230        ┆ C1CO1     ┆ 2.743902  │
│ 2         ┆ 235   ┆ 1.99417    ┆ 18.668085 ┆ … ┆ 73.617021  ┆ 24         ┆ Acyclic   ┆ 73.617021 │
│ 3         ┆ 138   ┆ 2.171075   ┆ 18.528986 ┆ … ┆ 0.0        ┆ 123        ┆ C1OC2CC1C ┆ 2.173913  │
│           ┆       ┆            ┆           ┆   ┆            ┆            ┆ 2         ┆           │
│ 4         ┆ 248   ┆ 2.167721   ┆ 20.197581 ┆ … ┆ 0.0        ┆ 118        ┆ C1COC1    ┆ 8.064516  │
│ …         ┆ …     ┆ …          ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 15        ┆ 179   ┆ 1.951371   ┆ 18.614525 ┆ … ┆ 67.039106  ┆ 33         ┆ Acyclic   ┆ 67.039106 │
│ 16        ┆ 297   ┆ 1.846142   ┆ 15.767677 ┆ … ┆ 0.0        ┆ 101        ┆ c1cn[nH]c ┆ 17.508418 │
│           ┆       ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 17        ┆ 326   ┆ 2.107032   ┆ 17.180982 ┆ … ┆ 0.0        ┆ 247        ┆ O=C1CCO1  ┆ 3.680982  │
│ 18        ┆ 310   ┆ 2.163001   ┆ 19.270968 ┆ … ┆ 0.0        ┆ 203        ┆ C1OC2CC12 ┆ 5.16129   │
│ 19        ┆ 237   ┆ 2.236308   ┆ 20.375527 ┆ … ┆ 0.0        ┆ 170        ┆ C1COC1    ┆ 4.219409  │
└───────────┴───────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

# Spectral

In [18]:
model_spectral = SpectralClustering(
                n_clusters=3,
                affinity="precomputed",
                assign_labels='kmeans',
                random_state=42,
            )

labels_spectral = model_spectral.fit_predict(dist_matrix)
df = df.with_columns(labels_spectral=labels_spectral)
print(np.unique(labels_spectral, return_counts=True))

(array([0, 1, 2], dtype=int32), array([4998,    1,    1]))

In [19]:
create_chemiscope_viewer(df, dist_matrix, labels_spectral, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [20]:
labels_km

array([0, 2, 1, ..., 2, 2, 2], shape=(5000,), dtype=uint64)

In [21]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="morgan",
    distance_metric="tanimoto",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_spectral,
    clustering_method="spectral"
)

2026-04-21 13:38:32.951 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/tanimoto/morgan/pca_spectral_projection.png

{'coords': array([[ 1.21527925,  1.71274172],
        [ 1.98816896, -1.69302976],
        [-0.2607709 , -0.32863902],
        ...,
        [ 2.57937249, -1.84158736],
        [-0.4344677 , -0.38770645],
        [ 2.69716913, -1.57512399]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/tanimoto/morgan/pca_spectral_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/tanimoto/morgan'),
 'clustering_method': 'spectral'}

In [22]:
average_numeric_by_cluster(df, "labels_spectral")

shape: (3, 61)
┌─────────────────┬───────┬─────────────────────┬───────────┬────────────┬────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────┬────────────────────┬──────────────┬─────────────┐
│ labels_spectral ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp   ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---             ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---    ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---                ┆ ---          ┆ ---         │
│ i32             ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64    ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64                ┆ f64          ┆ f64         │
╞═════════════════╪═══════╪═════════════════════╪═══════════╪════════════╪════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════╪════════════════════╪══════════════╪═════════════╡
│ 0               ┆ 4998  ┆ 2.0830              ┆ 18.0294   ┆ 122.7945   ┆ 0.0968 ┆ 36.7701 ┆ 0.8552            ┆ 12.8548             ┆ 8.7857          ┆ 1.6407    ┆ 0.1811             ┆ 2.0604       ┆ 2.3065              ┆ 0.0646        ┆ 0.2358        ┆ 0.6996        ┆ 0.9182        ┆ 2.0242           ┆ 6.5094          ┆ 0.4244         ┆ 1.3231          ┆ 4.5748          ┆ 6.3529            ┆ 37.8697         ┆ 1.2625          ┆ 0.0030     ┆ 0.3377     ┆ 0.0336    ┆ 0.1305   ┆ 0.1265   ┆ 0.0018             ┆ 0.0394   ┆ 0.1228    ┆ 0.5204   ┆ 0.0030   ┆ 2.4634     ┆ 2.6934 ┆ 75.1691 ┆ -6.5357 ┆ 0.3016  ┆ 6.8374 ┆ 1191.7836 ┆ 4.0578 ┆ -11180.1385 ┆ -11179.9071 ┆ -11179.8814 ┆ -11181.0487 ┆ 31.6670 ┆ -76.1210 ┆ -76.5845 ┆ -77.0222 ┆ -70.8445 ┆ 3.4051 ┆ 1.4011 ┆ 1.1173 ┆ 1.6240      ┆ 1.0200    ┆ 72.3289            ┆ 17.2269      ┆ 10.4442     │
│ 1               ┆ 1     ┆ 1.5455              ┆ 11.0000   ┆ 123.0000   ┆ 0.0000 ┆ 49.0000 ┆ 0.6382            ┆ 13.1385             ┆ 9.0000          ┆ 1.0000    ┆ 1.0000             ┆ 2.0000       ┆ 0.0000              ┆ 0.2000        ┆ 0.8000        ┆ 0.0000        ┆ 0.0000        ┆ 3.0000           ┆ 4.0000          ┆ 1.0000         ┆ 4.0000          ┆ 0.0000          ┆ 6.0000            ┆ 17.0000         ┆ 1.3040          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 4.0000     ┆ 2.9366 ┆ 67.3900 ┆ -7.9648 ┆ -2.4681 ┆ 5.4967 ┆ 1155.4125 ┆ 1.8277 ┆ -12401.5801 ┆ -12401.3994 ┆ -12401.3740 ┆ -12402.4355 ┆ 24.0560 ┆ -55.6457 ┆ -55.8898 ┆ -56.1467 ┆ -52.3122 ┆ 6.0379 ┆ 1.0236 ┆ 0.8752 ┆ 0.0000      ┆ 0.0000    ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 2               ┆ 1     ┆ 2.1818              ┆ 22.0000   ┆ 114.0000   ┆ 1.0000 ┆ 20.0000 ┆ 0.9479            ┆ 12.8554             ┆ 8.0000          ┆ 1.0000    ┆ 0.0000             ┆ 2.0000       ┆ 2.0000              ┆ 0.0000        ┆ 0.0000        ┆ 1.0000        ┆ 1.0000        ┆ 1.0000           ┆ 7.0000          ┆ 0.0000         ┆ 0.0000          ┆ 7.0000          ┆ 7.0000            ┆ 48.0000         ┆ 1.2461          ┆ 0.0000     ┆ 1.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 1.0000     ┆ 1.2696 ┆ 78.0000 ┆ -7.1103 ┆ 2.1660  ┆ 9.2764 ┆ 1172.3645 ┆ 5.5109 ┆ -9530.2188  ┆ -9529.9922  ┆ -9529.9668  ┆ -9531.1045  ┆ 32.2800 ┆ -87.9827 ┆ -88.6038 ┆ -89.1436 ┆ -81.6318 ┆ 3.8701 ┆ 1.3082 ┆ 1.0530 ┆ 2.0000      ┆ 2.0000    ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
└─────────────────┴───────┴─────────────────────┴───────────┴────────────┴────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴───────────┴────────────────────┴──────────────┴─────────────┘

shape: (3, 61)
┌────────────┬───────┬────────────┬───────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ labels_spe ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_km ┆ pct_alipha ┆ pct_aroma ┆ pct_acycl │
│ ctral      ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ---       ┆ tic_ring   ┆ tic       ┆ ic        │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ f64       ┆ ---        ┆ ---       ┆ ---       │
│ i32        ┆       ┆ f64        ┆           ┆   ┆           ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 4998  ┆ 2.08302    ┆ 18.029412 ┆ … ┆ 1.020008  ┆ 72.328932  ┆ 17.226891 ┆ 10.444178 │
│ 1          ┆ 1     ┆ 1.545455   ┆ 11.0      ┆ … ┆ 0.0       ┆ 0.0        ┆ 100.0     ┆ 0.0       │
│ 2          ┆ 1     ┆ 2.181818   ┆ 22.0      ┆ … ┆ 2.0       ┆ 100.0      ┆ 0.0       ┆ 0.0       │
└────────────┴───────┴────────────┴───────────┴───┴───────────┴────────────┴───────────┴───────────┘

# DBSCAN

In [33]:
model_db = DBSCAN(
    eps=0.8,
    min_samples=2,
    metric='precomputed',
)

labels_db = model_db.fit_predict(dist_matrix)
df = df.with_columns(labels_db=labels_db)
print(np.unique(labels_db, return_counts=True))

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7]), array([  20, 4961,    2,    2,    4,    4,    3,    2,    2]))

In [36]:
create_chemiscope_viewer(df, dist_matrix, labels_db, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [37]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="morgan",
    distance_metric="tanimoto",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_db,
    clustering_method="dbscan"
)

2026-04-21 13:44:54.711 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/tanimoto/morgan/pca_dbscan_projection.png

{'coords': array([[ 1.21527925,  1.71274172],
        [ 1.98816896, -1.69302976],
        [-0.2607709 , -0.32863902],
        ...,
        [ 2.57937249, -1.84158736],
        [-0.4344677 , -0.38770645],
        [ 2.69716913, -1.57512399]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/tanimoto/morgan/pca_dbscan_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/tanimoto/morgan'),
 'clustering_method': 'dbscan'}

In [38]:
clusters = average_numeric_by_cluster(df, "labels_db")
clusters.show(limit=25)

shape: (9, 63)
┌───────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────┬─────────────────┬───────────────┬────────────────────┬──────────────┬─────────────┐
│ labels_db ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ labels_spectral ┆ kmeans_labels ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---       ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---             ┆ ---           ┆ ---                ┆ ---          ┆ ---         │
│ i64       ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64             ┆ f64           ┆ f64                ┆ f64          ┆ f64         │
╞═══════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════╪═════════════════╪═══════════════╪════════════════════╪══════════════╪═════════════╡
│ -1        ┆ 20    ┆ 1.9823              ┆ 14.0000   ┆ 121.3500   ┆ -0.3500 ┆ 54.1000 ┆ 0.4343            ┆ 13.1067             ┆ 8.8000          ┆ 1.9500    ┆ 0.9000             ┆ 2.1246       ┆ 0.7000              ┆ 0.0250        ┆ 0.7061        ┆ 0.2689        ┆ 1.1000        ┆ 2.9500           ┆ 6.3500          ┆ 0.1000         ┆ 3.1000          ┆ 1.5500          ┆ 5.9000            ┆ 28.2000         ┆ 1.2712          ┆ 0.0000     ┆ 0.0000     ┆ 0.0500    ┆ 0.5500   ┆ 0.0000   ┆ 0.0500             ┆ 0.0000   ┆ 0.0000    ┆ 0.0500   ┆ 0.0000   ┆ 4.0500     ┆ 4.7966 ┆ 70.1490 ┆ -6.1922 ┆ -0.8165 ┆ 5.3759 ┆ 957.2563  ┆ 2.8578 ┆ -11463.5771 ┆ -11463.3970 ┆ -11463.3712 ┆ -11464.4236 ┆ 25.4675 ┆ -61.8042 ┆ -62.1636 ┆ -62.4977 ┆ -57.6079 ┆ 4.1102 ┆ 1.7144 ┆ 1.2440 ┆ 0.7000      ┆ 0.1000    ┆ 0.0000          ┆ 1.0500        ┆ 40.0000            ┆ 60.0000      ┆ 0.0000      │
│ 0         ┆ 4961  ┆ 2.0842              ┆ 18.0617   ┆ 122.7930   ┆ 0.0974  ┆ 36.6293 ┆ 0.8578            ┆ 12.8529             ┆ 8.7851          ┆ 1.6402    ┆ 0.1766             ┆ 2.0601       ┆ 2.3169              ┆ 0.0650        ┆ 0.2317        ┆ 0.7034        ┆ 0.9163        ┆ 2.0171           ┆ 6.5126          ┆ 0.4273         ┆ 1.3060          ┆ 4.6013          ┆ 6.3550            ┆ 37.9530         ┆ 1.2624          ┆ 0.0030     ┆ 0.3396     ┆ 0.0329    ┆ 0.1286   ┆ 0.1272   ┆ 0.0016             ┆ 0.0397   ┆ 0.1238    ┆ 0.5233   ┆ 0.0030   ┆ 2.4505     ┆ 2.6850 ┆ 75.2049 ┆ -6.5386 ┆ 0.3122  ┆ 6.8508 ┆ 1193.4273 ┆ 4.0677 ┆ -11175.2014 ┆ -11174.9696 ┆ -11174.9439 ┆ -11176.1120 ┆ 31.7094 ┆ -76.2365 ┆ -76.7009 ┆ -77.1394 ┆ -70.9513 ┆ 3.4029 ┆ 1.3987 ┆ 1.1166 ┆ 1.6313      ┆ 1.0262    ┆ 0.0006          ┆ 1.4838        ┆ 72.5257            ┆ 16.9522      ┆ 10.5221     │
│ 1         ┆ 2     ┆ 1.8077              ┆ 13.0000   ┆ 116.0000   ┆ 0.5000  ┆ 62.5000 ┆ 0.3934            ┆ 13.0571             ┆ 8.5000          ┆ 1.0000    ┆ 0.0000             ┆ 2.0000       ┆ 1.0000              ┆ 0.0000        ┆ 1.0000        ┆ 0.0000        ┆ 1.0000        ┆ 2.5000           ┆ 5.5000          ┆ 0.0000         ┆ 4.5000          ┆ 0.0000          ┆ 6.0000            ┆ 23.5000         ┆ 1.2731          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.5000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 4.0000     ┆ 2.7161 ┆ 71.4450 ┆ -6.8423 ┆ -2.4041 ┆ 4.4382 ┆ 873.4919  ┆ 2.5728 ┆ -10973.9258 ┆ -10973.7437 ┆ -10973.7183 ┆ -10974.7769 ┆ 24.8405 ┆ -58.4182 ┆ -58.7373 ┆ -59.0456 ┆ -54.5480 ┆ 3.0883 ┆ 2.0984 ┆ 1.3787 ┆ 0.0000      ┆ 0.0000    ┆ 0.0000          ┆ 1.0000        ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
│ 2         ┆ 2     ┆ 2.1738              ┆ 14.5000   ┆ 115.0000   ┆ 0.5000  ┆ 30.0000 ┆ 0.6949            ┆ 12.8139             ┆ 8.5000          ┆ 3.0000    ┆ 1.0000             ┆ 2.2583       ┆ 0.5000              ┆ 0.0000        ┆ 0.5000        ┆ 0.5000        ┆ 1.5000        ┆ 1.5000           ┆ 8.0000          ┆ 0.0000         ┆ 3.0000          ┆ 3.0000          ┆ 6.0000            ┆ 31.5000         ┆ 1.2788          ┆ 0.0000     ┆ 0.0000     ┆ 0.5000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 2.5000     ┆ 3.4009 ┆ 69.6900 ┆ -5.6083 ┆ 0.3551  ┆ 5.9620 ┆ 858.5151  ┆ 3.0680 ┆ -10317.4707 ┆ -10317.3052 ┆ -10317.2793 ┆ -10318.2949 ┆ 24.2930 ┆ -64.7029 ┆ -65.0961 ┆ -65.4430 ┆ -60.3907 ┆ 4.6037 ┆ 1.8287 ┆ 1.4772 ┆ 2.0000      ┆ 0.0000    ┆ 0.0000          ┆ 0.5000        ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 3         ┆ 4     ┆ 1.8215              ┆ 17.0000   ┆ 120.0000   ┆ 1.0000  ┆ 28.0000 ┆ 0.7052            ┆ 12.7500             ┆ 9.0000          ┆ 1.0000    ┆ 1.0000             ┆ 2.0000       ┆ 0.0000              ┆ 0.0000        ┆ 1.0000        ┆ 0.0000        ┆ 1.0000        ┆ 1.0000           ┆ 8.0000          ┆ 0.0000         ┆ 7.0000          ┆ 0.0000          ┆ 6.0000            ┆ 31.0000         ┆ 1.2400          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 2.0000     ┆ 2.1726 ┆ 88.3675 ┆ -5.4001 ┆ -0.8510 ┆ 4.5484 ┆ 1044.9260 ┆ 3.7682 ┆ -10363.4065 ┆ -10363.2019 ┆ -10363.1765 ┆ -10364.2712 ┆ 29.5103 ┆ -74.8546 ┆ -75.3057 ┆ -75.7169 ┆ -69.8115 ┆ 2.4121 ┆ 1.8905 ┆ 1.1615 ┆ 0.0000      ┆ 1.2500    ┆ 0.0000          ┆ 1.0000        ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 4         ┆ 4     ┆ 2.1972              ┆ 13.5000   ┆ 130.7500   ┆ -0.5000 ┆ 59.0000 ┆ 0.6213            ┆ 13.3349             ┆ 9.0000          ┆ 1.0000    ┆ 0.0000             ┆ 2.0000       ┆ 2.2500              ┆ 0.0000        ┆ 0.5667        ┆ 0.4333        ┆ 1.7500        ┆ 3.7500           ┆ 5.2500          ┆ 0.0000         ┆ 2.2500          ┆ 1.7500          ┆ 6.5000            ┆ 29.7500         ┆ 1.2545          ┆ 0.0000     ┆ 0.5000     ┆ 0.0000    ┆ 0.7500   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 5.0000     ┆ 2.2692 ┆ 70.3325 ┆ -6.7682 ┆ -2.2749 ┆ 4.4933 ┆ 1114.9848 ┆ 2.5364 ┆ -13114.9380 ┆ -13114.7207 ┆ -13114.6948 ┆ -13115.8457 ┆ 28.5005 ┆ -57.6600 ┆ -57.9624 ┆ -58.2836 ┆ -53.6401 ┆ 2.9390 ┆ 1.5292 ┆ 0.9836 ┆ 2.0000      ┆ 0.0000    ┆ 0.0000          ┆ 1.0000        ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
│ 5         ┆ 3     ┆ 1.5303              ┆ 11.3333   ┆ 125.6667   ┆ 0.0000  ┆ 71.6667 ┆ 0.3262            ┆ 13.2218             ┆ 9.0000          ┆ 2.0000    ┆ 2.0000             ┆ 2.1768       ┆ 1.0000              ┆ 0.0000        ┆ 1.0000        ┆ 0.0000        ┆ 1.0000        ┆ 5.6667           ┆ 4.3333          ┆ 0.0000         ┆ 3.3333          ┆ 0.0000          ┆ 6.6667            ┆ 17.3333         ┆ 1.2965          ┆ 0.0000     ┆ 0.0000     ┆ 1.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 5.6667     ┆ 2.6511 ┆ 58.8567 ┆ -6.3403 ┆ -0.8272 ┆ 5.5121 ┆ 939.6593  ┆ 1.9730 ┆ -13048.0055 ┆ -13047.8395 ┆ -13047.8141 ┆ -13048.8353 ┆ 23.2660 ┆ -52.0330 ┆ -52.3039 ┆ -52.5694 ┆ -48.5529 ┆ 4.9858 ┆ 1.5210 ┆ 1.1436 ┆ 0.0000      ┆ 0.0000    ┆ 0.0000          ┆ 1.0000        ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 6         ┆ 2     ┆ 1.5577              ┆ 12.5000   ┆ 128.5000   ┆ 0.5000  ┆ 99.5000 ┆ 0.4183            ┆ 13.3013             ┆ 9.0000          ┆ 1.0000    ┆ 0.0000             ┆ 2.0000       ┆ 2.0000              ┆ 0.0000        ┆ 1.0000        ┆ 0.0000        ┆ 1.5000        ┆ 4.0000           ┆ 3.5000          ┆ 0.0000         ┆ 3.0000          ┆ 0.0000          ┆ 7.0000            ┆ 19.5000         ┆ 1.2880          ┆ 0.0000     ┆ 1.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.5000   ┆ 0.0000   ┆ 6.0000     ┆ 3.0179 ┆ 63.7250 ┆ -6.8124 ┆ -1.5116 ┆ 5.3008 ┆ 1045.4077 ┆ 2.2762 ┆ -13496.3550 ┆ -13496.1514 ┆ -13496.1260 ┆ -13497.2471 ┆ 27.6350 ┆ -54.0335 ┆ -54.3113 ┆ -54.6068 ┆ -50.2738 ┆ 3.1542 ┆ 1.5246 ┆ 1.0277 ┆ 0.0000      ┆ 1.0000    ┆ 0.0000          ┆ 1.0000        ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
│ 7         ┆ 2     ┆ 1.8750              ┆ 12.0000   ┆ 131.0000   ┆ 2.0000  ┆ 49.5000 ┆ 1.0742            ┆ 13.3290             ┆ 9.0000          ┆ 1.0000    ┆ 0.0000             ┆ 2.0000       ┆ 1.5000              ┆ 0.0000        ┆ 0.9000        ┆ 0.1000        ┆ 0.0000        ┆ 1.5000           ┆ 4.5000          ┆ 0.0000         ┆ 4.0000          ┆ 0.5000          ┆ 6.0000            ┆ 22.5000         ┆ 1.2978          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 1.5000   ┆ 0.0000   ┆ 4.5000     ┆ 2.9158 ┆ 62.5050 ┆ -6.2328 ┆ -1.4735 ┆ 4.7606 ┆ 1055.4998 ┆ 2.0820 ┆ -14092.7622 ┆ -14092.5693 ┆ -14092.5439 ┆ -14093.6392 ┆ 26.4455 ┆ -55.4413 ┆ -55.7102 ┆ -55.9929 ┆ -51.8388 ┆ 3.1534 ┆ 1.4245 ┆ 0.9806 ┆ 0.0000      ┆ 0.0000    ┆ 0.0000          ┆ 1.0000        ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
└───────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴───────────┴─────────────────┴───────────────┴────────────────────┴──────────────┴─────────────┘

labels_db,count,token_to_atom_ratio,num_atoms,mol_weight,logp,tpsa,election_affinity,ionization_energies,num_heavy_atoms,num_rings,num_aromatic_rings,coordination,num_rotatable_bonds,fraction_csp1,fraction_csp2,fraction_csp3,h_bond_donors,h_bond_acceptors,branching_index,num_sp_carbons,num_sp2_carbons,num_sp3_carbons,main_chain_length,raw_token_count,avg_bond_length,fr_benzene,fr_alcohol,fr_phenol,fr_amine,fr_amide,fr_carboxylic_acid,fr_ester,fr_ketone,fr_ether,fr_nitro,fr_halogen,mu,alpha,homo,lumo,gap,r2,zpve,u0,u,h,g,cv,u0_atom,u_atom,h_atom,g_atom,A,B,C,labels_hier,labels_km,labels_spectral,kmeans_labels,pct_aliphatic_ring,pct_aromatic,pct_acyclic
i64,u32,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64
-1,20,1.982317,14.0,121.35,-0.35,54.1,0.434298,13.106688,8.8,1.95,0.9,2.124564,0.7,0.025,0.706131,0.268869,1.1,2.95,6.35,0.1,3.1,1.55,5.9,28.2,1.271156,0.0,0.0,0.05,0.55,0.0,0.05,0.0,0.0,0.05,0.0,4.05,4.796605,70.149,-6.192223,-0.816478,5.375881,957.25625,2.857846,-11463.577148,-11463.397021,-11463.371191,-11464.423584,25.4675,-61.804194,-62.163584,-62.497659,-57.60794,4.110221,1.714434,1.244005,0.7,0.1,0.0,1.05,40.0,60.0,0.0
0,4961,2.084161,18.061681,122.792985,0.097359,36.629309,0.857806,12.852904,8.785124,1.640194,0.176577,2.060108,2.316872,0.064981,0.231657,0.703363,0.916348,2.017134,6.512598,0.427333,1.305987,4.60129,6.354969,37.953034,1.262427,0.003024,0.339649,0.032856,0.128603,0.127192,0.001613,0.03971,0.123765,0.523282,0.003024,2.450514,2.684956,75.204896,-6.538606,0.31217,6.850783,1193.427261,4.067718,-11175.201364,-11174.969623,-11174.943949,-11176.112005,31.709364,-76.236466,-76.700851,-77.139371,-70.951255,3.402927,1.398659,1.116594,1.631324,1.026204,0.000605,1.483773,72.5257,16.952227,10.522072
1,2,1.807692,13.0,116.0,0.5,62.5,0.393377,13.057106,8.5,1.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,2.5,5.5,0.0,4.5,0.0,6.0,23.5,1.2731,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,4.0,2.71605,71.445,-6.842303,-2.404126,4.438177,873.491882,2.572809,-10973.925781,-10973.743652,-10973.718262,-10974.776855,24.8405,-58.418196,-58.737267,-59.045641,-54.548006,3.088295,2.098375,1.37873,0.0,0.0,0.0,1.0,100.0,0.0,0.0
2,2,2.17381,14.5,115.0,0.5,30.0,0.694857,12.813877,8.5,3.0,1.0,2.258333,0.5,0.0,0.5,0.5,1.5,1.5,8.0,0.0,3.0,3.0,6.0,31.5,1.27876,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.5,3.40095,69.690002,-5.608267,0.355109,5.962015,858.515137,3.067961,-10317.470703,-10317.305176,-10317.279297,-10318.294922,24.293,-64.702887,-65.096088,-65.443037,-60.390657,4.60368,1.82866,1.477235,2.0,0.0,0.0,0.5,0.0,100.0,0.0
3,4,1.821487,17.0,120.0,1.0,28.0,0.705207,12.749954,9.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,1.0,1.0,8.0,0.0,7.0,0.0,6.0,31.0,1.239993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.1726,88.3675,-5.4001,-0.851036,4.548383,1044.925995,3.768192,-10363.406494,-10363.201904,-10363.176514,-10364.27124,29.51025,-74.854586,-75.305737,-75.716942,-69.811499,2.412133,1.890455,1.161532,0.0,1.25,0.0,1.0,0.0,100.0,0.0
4,4,2.197161,13.5,130.75,-0.5,59.0,0.6213,13.334929,9.0,1.0,0.0,2.0,2.25,0.0,0.566667,0.433333,1.75,3.75,5.25,0.0,2.25,1.75,6.5,29.75,1.254497,0.0,0.5,0.0,0.75,0.0,0.0,0.0,0.0,0.0,0.0,5.0,2.2692,70.3325,-6.768152,-2.274872,4.49328,1114.984802,2.536353,-13114.937988,-13114.720703,-13114.694824,-13115.845703,28.5005,-57.659982,-57.962408,-58.283625,-53.640123,2.938978,1.52925,0.983613,2.0,0.0,0.0,1.0,100.0,0.0,0.0
5,3,1.530303,11.333333,125.666667,0.0,71.666667,0.326196,13.221801,9.0,2.0,2.0,2.176768,1.0,0.0,1.0,0.0,1.0,5.666667,4.333333,0.0,3.333333,0.0,6.666667,17.333333,1.296509,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.666667,2.651133,58.856668,-6.340253,-0.827226,5.51212,939.659261,1.973016,-13048.005534,-13047.839518,-13047.814128,-13048.835286,23.265999,-52.032955,-52.303891,-52.569392,-48.552929,4.985837,1.521013,1.143567,0.0,0.0,0.0,1.0,0.0,100.0,0.0
6,2,1.557692,12.5,128.5,0.5,99.5,0.418346,13.301257,9.0,1.0,0.0,2.0,2.0,0.0,1.0,0.0,1.5,4.0,3.5,0.0,3.0,0.0,7.0,19.5,1.287983,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,6.0,3.0179,63.725002,-6.81237,-1.511592,5.300778,1045.407715,2.276219,-13496.35498,-13496.151367,-13496.125977,-13497.24707,27.635,-54.033451,-54.311279,-54.606781,-50.27383,3.154155,1.524645,1.02771,0.0,1.0,0.0,1.0,100.0,0.0,0.0
7,2,1.875,12.0,131.0,2.0,49.5,1.074162,13.328985,9.0,1.0,0.0,2.0,1.5,0.0,0.9,0.1,0.0,1.5,4.5,0.0,4.0,0.5,6.0,22.5,1.297806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,4.5,2.91575,62.504999,-6.232768,-1.473497,4.760632,1055.499756,2.082038,-14092.762207,-14092.569336,-14092.543945,-14093.63916,26.4455,-55.44133,-55.710247,-55.992889,-51.838768,3.15339,1.42455,0.98058,0.0,0.0,0.0,1.0,100.0,0.0,0.0

# KMeans on embedding

In [27]:
df

shape: (5_000, 66)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ mol_id    ┆ formula  ┆ smiles    ┆ canonical ┆ … ┆ labels_hi ┆ labels_km ┆ labels_sp ┆ labels_db │
│ ---       ┆ ---      ┆ ---       ┆ _smiles   ┆   ┆ er        ┆ ---       ┆ ectral    ┆ ---       │
│ str       ┆ str      ┆ str       ┆ ---       ┆   ┆ ---       ┆ u64       ┆ ---       ┆ i64       │
│           ┆          ┆           ┆ str       ┆   ┆ i64       ┆           ┆ i32       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ qm9_89    ┆ C3H5NO   ┆ [H]N1C([H ┆ [H]N1C([H ┆ … ┆ 2         ┆ 0         ┆ 0         ┆ -1        │
│           ┆          ┆ ])([H])C( ┆ ])([H])C( ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ =O)C1([H] ┆ =O)C1([H] ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ )[H…      ┆ )[H…      ┆   ┆           ┆           ┆           ┆           │
│ qm9_132   ┆ C4H10O   ┆ [H]C([H]) ┆ [H]C([H]) ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ 0         │
│           ┆          ┆ ([H])C([H ┆ ([H])C([H ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ ])([H])OC ┆ ])([H])OC ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ ([H…      ┆ ([H…      ┆   ┆           ┆           ┆           ┆           │
│ qm9_139   ┆ C3H4N2   ┆ [H]N1C([H ┆ [H]N1C([H ┆ … ┆ 2         ┆ 1         ┆ 0         ┆ 0         │
│           ┆          ┆ ])([H])[C ┆ ])([H])[C ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ @]1([H])C ┆ @]1([H])C ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ #N        ┆ #N        ┆   ┆           ┆           ┆           ┆           │
│ qm9_144   ┆ C3H5NO   ┆ [H]C(=O)N ┆ [H]C(=O)N ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ 0         │
│           ┆          ┆ 1C([H])([ ┆ 1C([H])([ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ H])C1([H] ┆ H])C1([H] ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ )[H…      ┆ )[H…      ┆   ┆           ┆           ┆           ┆           │
│ qm9_149   ┆ C4H8O    ┆ [H]OC([H] ┆ [H]OC([H] ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ 0         │
│           ┆          ┆ )([H])C1( ┆ )([H])C1( ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ [H])C([H] ┆ [H])C([H] ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ )([…      ┆ )([…      ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ qm9_13067 ┆ C4H5F3O2 ┆ [H]C(=O)O ┆ [H]C(=O)O ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ 0         │
│ 7         ┆          ┆ [C@]([H]) ┆ [C@]([H]) ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ (C([H])([ ┆ (C([H])([ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ H])…      ┆ H])…      ┆   ┆           ┆           ┆           ┆           │
│ qm9_13070 ┆ C5H9F3N+ ┆ [H]C([H]) ┆ [H]C([H]) ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ -1        │
│ 1         ┆          ┆ ([H])[N@H ┆ (C(F)(F)F ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ +]1C([H]) ┆ )[C@]1([H ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ ([H…      ┆ ])C…      ┆   ┆           ┆           ┆           ┆           │
│ qm9_13074 ┆ C4H7F3O2 ┆ [H]OC([H] ┆ [H]OC([H] ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ -1        │
│ 3         ┆          ┆ )([H])C([ ┆ )([H])C([ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ H])(C(F)( ┆ H])(C(F)( ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ F)F…      ┆ F)F…      ┆   ┆           ┆           ┆           ┆           │
│ qm9_13076 ┆ C6H9F3   ┆ [H]C([H]) ┆ [H]C([H]) ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ 0         │
│ 1         ┆          ┆ ([H])C([H ┆ ([H])C([H ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ ])([H])[C ┆ ])([H])[C ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ @@]…      ┆ @@]…      ┆   ┆           ┆           ┆           ┆           │
│ qm9_13077 ┆ C4H8F3NO ┆ [H]OC([H] ┆ [H]OC([H] ┆ … ┆ 2         ┆ 2         ┆ 0         ┆ 0         │
│ 8         ┆          ┆ )([H])C([ ┆ )([H])C([ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ H])([H])[ ┆ H])([H])[ ┆   ┆           ┆           ┆           ┆           │
│           ┆          ┆ C@]…      ┆ C@]…      ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [32]:
embedding = np.array(df['morgan_fingerprint'].to_list())
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans_labels = kmeans.fit_predict(embedding)
df = df.with_columns(kmeans_labels=kmeans_labels)

In [33]:
create_chemiscope_viewer(df, embedding, kmeans_labels, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [34]:
average_numeric_by_cluster(df, "kmeans_labels")

shape: (3, 63)
┌───────────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬────────────────────┬──────────────┬─────────────┬──────────────────┬──────────────┬──────────────────┐
│ kmeans_labels ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic ┆ unique_scaffolds ┆ top_scaffold ┆ top_scaffold_pct │
│ ---           ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---                ┆ ---          ┆ ---         ┆ ---              ┆ ---          ┆ ---              │
│ i32           ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64                ┆ f64          ┆ f64         ┆ u32              ┆ str          ┆ f64              │
╞═══════════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪════════════════════╪══════════════╪═════════════╪══════════════════╪══════════════╪══════════════════╡
│ 0             ┆ 830   ┆ 2.1052              ┆ 17.0747   ┆ 123.4386   ┆ -0.0904 ┆ 39.0675 ┆ 0.9103            ┆ 12.8048             ┆ 8.8386          ┆ 1.8530    ┆ 0.0241             ┆ 2.0882       ┆ 1.3651              ┆ 0.0271        ┆ 0.2862        ┆ 0.6867        ┆ 0.8181        ┆ 2.1663           ┆ 6.6795          ┆ 0.1687         ┆ 1.7518          ┆ 4.2880          ┆ 5.8542            ┆ 36.0867         ┆ 1.2751          ┆ 0.0000     ┆ 0.2518     ┆ 0.0024    ┆ 0.0663   ┆ 0.3000   ┆ 0.0012             ┆ 0.1651   ┆ 0.5048    ┆ 0.5012   ┆ 0.0000   ┆ 2.6301     ┆ 3.2754 ┆ 72.4560 ┆ -6.5850 ┆ -0.4919 ┆ 6.0932 ┆ 1088.0795 ┆ 3.7576 ┆ -11503.7800 ┆ -11503.5615 ┆ -11503.5358 ┆ -11504.6726 ┆ 30.1793 ┆ -73.9059 ┆ -74.3455 ┆ -74.7586 ┆ -68.8815 ┆ 3.0154 ┆ 1.5489 ┆ 1.1883 ┆ 1.8819      ┆ 97.5904            ┆ 2.4096       ┆ 0.0000      ┆ 477              ┆ O=C1CCN1     ┆ 3.3735           │
│ 1             ┆ 940   ┆ 1.8654              ┆ 15.6553   ┆ 121.6936   ┆ 0.2500  ┆ 49.7830 ┆ 0.6664            ┆ 12.9728             ┆ 8.7702          ┆ 1.2521    ┆ 0.9394             ┆ 2.0316       ┆ 2.0862              ┆ 0.0316        ┆ 0.6716        ┆ 0.2969        ┆ 1.0809        ┆ 2.8096           ┆ 6.1830          ┆ 0.1819         ┆ 3.4574          ┆ 1.6851          ┆ 6.3543            ┆ 29.5255         ┆ 1.2580          ┆ 0.0160     ┆ 0.1160     ┆ 0.1766    ┆ 0.2479   ┆ 0.0404   ┆ 0.0000             ┆ 0.0064   ┆ 0.0160    ┆ 0.1968   ┆ 0.0160   ┆ 3.4457     ┆ 3.0899 ┆ 72.7623 ┆ -6.1108 ┆ -0.3487 ┆ 5.7620 ┆ 1146.8620 ┆ 3.3392 ┆ -11473.8528 ┆ -11473.6367 ┆ -11473.6110 ┆ -11474.7480 ┆ 29.1699 ┆ -68.2609 ┆ -68.6482 ┆ -69.0249 ┆ -63.6458 ┆ 3.9141 ┆ 1.4422 ┆ 1.0449 ┆ 0.1894      ┆ 10.7447            ┆ 89.2553      ┆ 0.0000      ┆ 330              ┆ c1cc[nH]c1   ┆ 8.5106           │
│ 2             ┆ 3230  ┆ 2.1405              ┆ 18.9647   ┆ 122.9467   ┆ 0.1006  ┆ 32.3913 ┆ 0.8959            ┆ 12.8335             ┆ 8.7765          ┆ 1.6988    ┆ 0.0009             ┆ 2.0615       ┆ 2.6118              ┆ 0.0838        ┆ 0.0962        ┆ 0.8200        ┆ 0.8963        ┆ 1.7591           ┆ 6.5601          ┆ 0.5607         ┆ 0.5923          ┆ 5.4889          ┆ 6.4808            ┆ 40.7529         ┆ 1.2606          ┆ 0.0000     ┆ 0.4245     ┆ 0.0000    ┆ 0.1127   ┆ 0.1068   ┆ 0.0025             ┆ 0.0167   ┆ 0.0557    ┆ 0.6192   ┆ 0.0000   ┆ 2.1347     ┆ 2.4281 ┆ 76.5652 ┆ -6.6473 ┆ 0.6945  ┆ 7.3419 ┆ 1231.4879 ┆ 4.3438 ┆ -11011.3637 ┆ -11011.1246 ┆ -11011.0989 ┆ -11012.2829 ┆ 32.7737 ┆ -78.9750 ┆ -79.4668 ┆ -79.9286 ┆ -73.4415 ┆ 3.3580 ┆ 1.3510 ┆ 1.1200 ┆ 1.9749      ┆ 83.7461            ┆ 0.0929       ┆ 16.1610     ┆ 786              ┆ Acyclic      ┆ 16.1610          │
└───────────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴────────────────────┴──────────────┴─────────────┴──────────────────┴──────────────┴──────────────────┘

shape: (3, 63)
┌────────────┬───────┬────────────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ kmeans_lab ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ pct_acycli ┆ unique_sc ┆ top_scaff ┆ top_scaff │
│ els        ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ c          ┆ affolds   ┆ old       ┆ old_pct   │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ i32        ┆       ┆ f64        ┆           ┆   ┆ f64        ┆ u32       ┆ str       ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 830   ┆ 2.105239   ┆ 17.074699 ┆ … ┆ 0.0        ┆ 477       ┆ O=C1CCN1  ┆ 3.373494  │
│ 1          ┆ 940   ┆ 1.865403   ┆ 15.655319 ┆ … ┆ 0.0        ┆ 330       ┆ c1cc[nH]c ┆ 8.510638  │
│            ┆       ┆            ┆           ┆   ┆            ┆           ┆ 1         ┆           │
│ 2          ┆ 3230  ┆ 2.140506   ┆ 18.964706 ┆ … ┆ 16.160991  ┆ 786       ┆ Acyclic   ┆ 16.160991 │
└────────────┴───────┴────────────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘