In [1]:
import os
os.chdir('../../../../..')

In [2]:
import numpy as np

from sklearn.cluster import AgglomerativeClustering, SpectralClustering, DBSCAN, KMeans
from kmedoids import KMedoids

from src.datasets import QM9Dataset
from src.helper_functions import plot_molecules_with_py3dmol, create_chemiscope_viewer, plot_distance_matrix_projection, evaluate_distance_matrix_clustering_sweep, average_numeric_by_cluster

In [3]:
qm9 = QM9Dataset(limit=5000, sampling_strategy="stratified", stratify_by=["num_atoms", "gap"], add_selfies_transformer=True)
df = qm9.load()

2026-04-21 11:06:33.873 | INFO     | src.datasets:load:496 - Loading cached full QM9 dataset from: data/QM9/dataset_cleaned.parquet
2026-04-21 11:06:34.207 | INFO     | src.datasets:_sample_qm9_df:688 - QM9 sampling complete: strategy=stratified, requested_limit=5000, returned_rows=5000.
2026-04-21 11:06:34.208 | INFO     | src.datasets:_add_requested_descriptors:129 - Applying requested QM9 descriptors to sampled dataframe (rows=5000).
2026-04-21 11:06:34.208 | INFO     | src.features:compute_selfies_transformer:93 - Computing SELFormer Embeddings using HUBioDataLab/SELFormer...
INFO: HTTP Request: HEAD https://huggingface.co/HUBioDataLab/SELFormer/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HUBioDataLab/SELFormer/177d98b158e999a6cb7fc9743dbfe1e8a17c57e5/config.json "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/HUBioDataLab/SELFormer/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING: Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HUBioDataLab/SELFormer/177d98b158e999a6cb7fc9743dbfe1e8a17c57e5/tokenizer_config.json "HTTP/1.1 200 OK"
INFO: HTTP Request: GET https://huggingface.co/api/models/HUBioDataLab/SELFormer/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
INFO: HTTP Request: GET https://huggingface.co/api/models/HUBioDataLab/SELFormer/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/HUBioDataLab/SELFormer/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HUBioDataLab/SELFormer/177d98b158e999a6cb7fc9743dbfe1e8a17c57e5/config.json "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/HUBioDataLab/SELFormer/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

INFO: HTTP Request: GET https://huggingface.co/api/models/HUBioDataLab/SELFormer "HTTP/1.1 200 OK"
INFO: HTTP Request: GET https://huggingface.co/api/models/HUBioDataLab/SELFormer/commits/main "HTTP/1.1 200 OK"
INFO: HTTP Request: GET https://huggingface.co/api/models/HUBioDataLab/SELFormer/discussions?p=0 "HTTP/1.1 200 OK"
INFO: HTTP Request: GET https://huggingface.co/api/models/HUBioDataLab/SELFormer/commits/refs%2Fpr%2F1 "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/HUBioDataLab/SELFormer/resolve/refs%2Fpr%2F1/model.safetensors.index.json "HTTP/1.1 404 Not Found"
INFO: HTTP Request: HEAD https://huggingface.co/HUBioDataLab/SELFormer/resolve/refs%2Fpr%2F1/model.safetensors "HTTP/1.1 302 Found"
2026-04-21 11:07:43.479 | INFO     | src.datasets:_add_requested_descriptors:152 - Added descriptor column(s): ['selfies_transformer']

In [4]:
len(df['selfies_transformer'].to_list()[0])

768

In [5]:
molecules = qm9.get_molecules()

2026-04-21 11:08:19.177 | SUCCESS  | src.datasets:get_molecules:1181 - Saved 5000 molecules to data/QM9/qm9_subset.xyz (failed: 0, requested: 5000).

In [6]:
plot_molecules_with_py3dmol(molecules[0:3])

In [10]:
dist_matrix = qm9.get_distance_matrix(
    descriptor="transformer",
    dist_type="euclidean",
    force_calculate=True,
    pca_variance=60,
)

2026-04-21 11:10:11.009 | INFO     | src.datasets:get_distance_matrix:991 - Applying PCA to retain 60.00% of variance.
2026-04-21 11:10:11.536 | INFO     | src.datasets:get_distance_matrix:1001 - PCA reduced 'selfies_transformer' dimensions from 768 to 5
2026-04-21 11:10:11.549 | INFO     | src.datasets:get_distance_matrix:1012 - Calculating distance matrix for selfies_transformer using euclidean distance.
2026-04-21 11:10:11.747 | SUCCESS  | src.distance:_compute_and_save:79 - Saved distance matrix to data/QM9/dist_selfies_transformer_euclidean_pca0.6.npy

# Determining the best number of clusters for each clustering method

In [11]:
out = evaluate_distance_matrix_clustering_sweep(
    dist_matrix=dist_matrix,
    fingerprint="transformer",
    distance_metric="euclidean",
    dataset_name="qm9",
)

Evaluation k:   0%|          | 0/19 [00:02<?, ?it/s]

KeyboardInterrupt:

In [12]:
# find the n molecules that are not on the diagonal with the smallest distance
n = 10
# Get the indices of the upper triangle (excluding diagonal)
triu_indices = np.triu_indices_from(dist_matrix, k=1)
# Get the distances and corresponding molecule pairs
distances = dist_matrix[triu_indices]
molecule_pairs = list(zip(triu_indices[0], triu_indices[1]))
# Get the indices of the n smallest distances
smallest_indices = np.argsort(distances)[:n]
# Get the corresponding molecule pairs for the n smallest distances
closest_pairs = [molecule_pairs[i] for i in smallest_indices]
print("Closest molecule pairs (indices):", closest_pairs)
mols = [(molecules[idx1], molecules[idx2]) for idx1, idx2 in closest_pairs]

Closest molecule pairs (indices): [(np.int64(4966), np.int64(4967)), (np.int64(1021), np.int64(2358)), (np.int64(2809), np.int64(3979)), (np.int64(4140), np.int64(4201)), (np.int64(2866), np.int64(3237)), (np.int64(4933), np.int64(4958)), (np.int64(2621), np.int64(3375)), (np.int64(3848), np.int64(4607)), (np.int64(848), np.int64(923)), (np.int64(1373), np.int64(4256))]

In [11]:
print(mols[0])

(Atoms(symbols='N2HFC2HC2NC', pbc=False, initial_charges=..., mass=..., partial_charge=...), Atoms(symbols='CNHNCFCHC2N', pbc=False, initial_charges=..., mass=..., partial_charge=...))

In [15]:
plot_molecules_with_py3dmol(mols[1])

# Hiercical Clustering on Distance Matrix

In [ ]:
model_hier = AgglomerativeClustering(metric='precomputed', n_clusters=3, linkage='complete')
labels_hier = model_hier.fit_predict(dist_matrix)
print(np.unique(labels_hier, return_counts=True))
df = df.with_columns(labels_hier=labels_hier)

(array([0, 1, 2]), array([4865,    2,  133]))

In [22]:
create_chemiscope_viewer(df, dist_matrix, labels_hier, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [23]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="transformer",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_hier,
    clustering_method="hierarchical"
)

2026-04-21 11:13:06.287 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/transformer/pca_hierarchical_projection.png

{'coords': array([[  2.3214721 , -58.46608817],
        [ 44.20252122,  61.41668055],
        [ 72.14163397, -58.30720516],
        ...,
        [  7.31243128,  30.99989679],
        [ 15.32269402, -18.02808763],
        [ 15.34732849, -44.20419622]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/transformer/pca_hierarchical_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/transformer'),
 'clustering_method': 'hierarchical'}

In [24]:
average_numeric_by_cluster(df, "labels_hier")

shape: (3, 59)
┌─────────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬────────────────────┬──────────────┬─────────────┐
│ labels_hier ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---         ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---                ┆ ---          ┆ ---         │
│ i64         ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64                ┆ f64          ┆ f64         │
╞═════════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪════════════════════╪══════════════╪═════════════╡
│ 0           ┆ 4865  ┆ 2.0921              ┆ 18.1694   ┆ 122.8769   ┆ 0.0989  ┆ 35.9490 ┆ 0.8652            ┆ 12.8484             ┆ 8.7897          ┆ 1.6518    ┆ 0.1618             ┆ 2.0610       ┆ 2.3348              ┆ 0.0648        ┆ 0.2194        ┆ 0.7158        ┆ 0.9147        ┆ 1.9926           ┆ 6.5482          ┆ 0.4286         ┆ 1.2631          ┆ 4.6867          ┆ 6.3624            ┆ 38.2845         ┆ 1.2623          ┆ 0.0029     ┆ 0.3447     ┆ 0.0306    ┆ 0.1272   ┆ 0.1266   ┆ 0.0018             ┆ 0.0403   ┆ 0.1250    ┆ 0.5297   ┆ 0.0029   ┆ 2.4113     ┆ 2.6787 ┆ 75.3871 ┆ -6.5350 ┆ 0.3483  ┆ 6.8833 ┆ 1197.1501 ┆ 4.1004 ┆ -11163.6330 ┆ -11163.4005 ┆ -11163.3748 ┆ -11164.5445 ┆ 31.8241 ┆ -76.6182 ┆ -77.0860 ┆ -77.5273 ┆ -71.3027 ┆ 3.3868 ┆ 1.3928 ┆ 1.1154 ┆ 73.6280            ┆ 15.7862      ┆ 10.5858     │
│ 1           ┆ 2     ┆ 2.3077              ┆ 13.0000   ┆ 121.0000   ┆ -2.0000 ┆ 45.0000 ┆ 0.7146            ┆ 12.7314             ┆ 9.0000          ┆ 3.0000    ┆ 0.0000             ┆ 2.2857       ┆ 0.0000              ┆ 0.1667        ┆ 0.1667        ┆ 0.6667        ┆ 1.0000        ┆ 2.0000           ┆ 6.0000          ┆ 1.0000         ┆ 1.0000          ┆ 4.0000          ┆ 5.0000            ┆ 30.0000         ┆ 1.3013          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 1.0000    ┆ 0.0000   ┆ 0.0000   ┆ 3.0000     ┆ 3.9714 ┆ 68.2600 ┆ -7.5171 ┆ -1.2490 ┆ 6.2681 ┆ 991.8650  ┆ 2.4492 ┆ -11308.2505 ┆ -11308.0664 ┆ -11308.0405 ┆ -11309.1035 ┆ 25.6230 ┆ -61.4032 ┆ -61.7199 ┆ -62.0282 ┆ -57.4969 ┆ 3.7886 ┆ 1.4597 ┆ 1.1769 ┆ 100.0000           ┆ 0.0000       ┆ 0.0000      │
│ 2           ┆ 133   ┆ 1.7428              ┆ 12.9624   ┆ 119.7444   ┆ 0.0602  ┆ 66.6466 ┆ 0.4901            ┆ 13.0949             ┆ 8.6316          ┆ 1.2030    ┆ 0.8947             ┆ 2.0315       ┆ 1.2857              ┆ 0.0538        ┆ 0.8399        ┆ 0.1063        ┆ 1.0376        ┆ 3.1805           ┆ 5.0827          ┆ 0.2632         ┆ 3.5338          ┆ 0.4737          ┆ 6.0301            ┆ 22.7368         ┆ 1.2679          ┆ 0.0075     ┆ 0.0902     ┆ 0.1429    ┆ 0.2481   ┆ 0.1203   ┆ 0.0000             ┆ 0.0075   ┆ 0.0301    ┆ 0.1805   ┆ 0.0075   ┆ 4.3609     ┆ 3.2026 ┆ 67.2634 ┆ -6.5611 ┆ -1.3887 ┆ 5.1725 ┆ 998.0684  ┆ 2.5190 ┆ -11778.7440 ┆ -11778.5531 ┆ -11778.5274 ┆ -11779.6068 ┆ 25.9586 ┆ -58.0914 ┆ -58.4001 ┆ -58.7075 ┆ -54.2274 ┆ 4.0927 ┆ 1.7014 ┆ 1.1839 ┆ 24.0602            ┆ 70.6767      ┆ 5.2632      │
└─────────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴────────────────────┴──────────────┴─────────────┘

shape: (3, 59)
┌────────────┬───────┬────────────┬───────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ labels_hie ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ C        ┆ pct_alipha ┆ pct_aromat ┆ pct_acycl │
│ r          ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ---      ┆ tic_ring   ┆ ic         ┆ ic        │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ f64      ┆ ---        ┆ ---        ┆ ---       │
│ i64        ┆       ┆ f64        ┆           ┆   ┆          ┆ f64        ┆ f64        ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 0          ┆ 4865  ┆ 2.092139   ┆ 18.169373 ┆ … ┆ 1.115361 ┆ 73.627955  ┆ 15.786228  ┆ 10.585817 │
│ 1          ┆ 2     ┆ 2.307692   ┆ 13.0      ┆ … ┆ 1.176935 ┆ 100.0      ┆ 0.0        ┆ 0.0       │
│ 2          ┆ 133   ┆ 1.742798   ┆ 12.962406 ┆ … ┆ 1.183896 ┆ 24.06015   ┆ 70.676692  ┆ 5.263158  │
└────────────┴───────┴────────────┴───────────┴───┴──────────┴────────────┴────────────┴───────────┘

# KMedoids

In [25]:
model_km = KMedoids(n_clusters=3, metric="precomputed")
labels_km = model_km.fit_predict(dist_matrix)
print(np.unique(labels_km, return_counts=True))
df = df.with_columns(labels_km=labels_km)

(array([0, 1, 2], dtype=uint64), array([1360, 1443, 2197]))

In [26]:
create_chemiscope_viewer(df, dist_matrix, labels_km, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [27]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="transformer",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_km,
    clustering_method="kmedoids"
)

2026-04-21 11:16:40.276 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/transformer/pca_kmedoids_projection.png

{'coords': array([[  2.3214721 , -58.46608817],
        [ 44.20252122,  61.41668055],
        [ 72.14163397, -58.30720516],
        ...,
        [  7.31243128,  30.99989679],
        [ 15.32269402, -18.02808763],
        [ 15.34732849, -44.20419622]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/transformer/pca_kmedoids_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/transformer'),
 'clustering_method': 'kmedoids'}

In [28]:
average_numeric_by_cluster(df, "labels_km")

shape: (3, 60)
┌───────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬────────────────────┬──────────────┬─────────────┐
│ labels_km ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---       ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---                ┆ ---          ┆ ---         │
│ u64       ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64                ┆ f64          ┆ f64         │
╞═══════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪════════════════════╪══════════════╪═════════════╡
│ 0         ┆ 1360  ┆ 2.1588              ┆ 17.5735   ┆ 121.8809   ┆ -0.1544 ┆ 33.0287 ┆ 0.8992            ┆ 12.7879             ┆ 8.7809          ┆ 2.6426    ┆ 0.0279             ┆ 2.1602       ┆ 1.4684              ┆ 0.0536        ┆ 0.1111        ┆ 0.8354        ┆ 1.0059        ┆ 1.8735           ┆ 6.7404          ┆ 0.3566         ┆ 0.6860          ┆ 5.5096          ┆ 6.0022            ┆ 38.0662         ┆ 1.2782          ┆ 0.0000     ┆ 0.4699     ┆ 0.0022    ┆ 0.0551   ┆ 0.0456   ┆ 0.0007             ┆ 0.0338   ┆ 0.1118    ┆ 0.6654   ┆ 0.0000   ┆ 2.2287     ┆ 2.4536 ┆ 73.2024 ┆ -6.5167 ┆ 0.6569  ┆ 7.1736 ┆ 1040.9474 ┆ 3.9366 ┆ -11055.1855 ┆ -11054.9775 ┆ -11054.9518 ┆ -11056.0599 ┆ 29.6810 ┆ -74.5858 ┆ -75.0552 ┆ -75.4811 ┆ -69.4093 ┆ 3.2706 ┆ 1.6214 ┆ 1.3295 ┆ 0.0382      ┆ 96.8382            ┆ 2.4265       ┆ 0.7353      │
│ 1         ┆ 1443  ┆ 1.8964              ┆ 15.5502   ┆ 122.0305   ┆ -0.0256 ┆ 52.5385 ┆ 0.7398            ┆ 12.9428             ┆ 8.7318          ┆ 1.0035    ┆ 0.5572             ┆ 2.0003       ┆ 2.2273              ┆ 0.0855        ┆ 0.5263        ┆ 0.3882        ┆ 1.0825        ┆ 2.7699           ┆ 5.7013          ┆ 0.5135         ┆ 2.6653          ┆ 2.0929          ┆ 6.3957            ┆ 29.7006         ┆ 1.2576          ┆ 0.0069     ┆ 0.1968     ┆ 0.1123    ┆ 0.2606   ┆ 0.2391   ┆ 0.0021             ┆ 0.0575   ┆ 0.1130    ┆ 0.3354   ┆ 0.0104   ┆ 3.4602     ┆ 3.2376 ┆ 71.2136 ┆ -6.4518 ┆ -0.5814 ┆ 5.8703 ┆ 1185.4283 ┆ 3.2820 ┆ -11651.2924 ┆ -11651.0656 ┆ -11651.0400 ┆ -11652.2053 ┆ 30.0113 ┆ -67.6306 ┆ -68.0031 ┆ -68.3771 ┆ -63.0684 ┆ 3.8020 ┆ 1.3757 ┆ 1.0244 ┆ 0.1497      ┆ 30.3534            ┆ 53.0146      ┆ 16.6320     │
│ 2         ┆ 2197  ┆ 2.1585              ┆ 19.9386   ┆ 123.8580   ┆ 0.3332  ┆ 28.7274 ┆ 0.9036            ┆ 12.8386             ┆ 8.8239          ┆ 1.4383    ┆ 0.0291             ┆ 2.0380       ┆ 2.8762              ┆ 0.0577        ┆ 0.1224        ┆ 0.8200        ┆ 0.7556        ┆ 1.6277           ┆ 6.8962          ┆ 0.4078         ┆ 0.8366          ┆ 5.6254          ┆ 6.5421            ┆ 43.1088         ┆ 1.2560          ┆ 0.0023     ┆ 0.3487     ┆ 0.0014    ┆ 0.0915   ┆ 0.1024   ┆ 0.0023             ┆ 0.0310   ┆ 0.1361    ┆ 0.5517   ┆ 0.0000   ┆ 1.9540     ┆ 2.4839 ┆ 78.9823 ┆ -6.6035 ┆ 0.6614  ┆ 7.2649 ┆ 1289.3039 ┆ 4.6420 ┆ -10947.8365 ┆ -10947.5876 ┆ -10947.5619 ┆ -10948.7671 ┆ 33.9806 ┆ -82.6440 ┆ -83.1635 ┆ -83.6503 ┆ -76.8369 ┆ 3.2291 ┆ 1.2811 ┆ 1.0468 ┆ 0.0000      ┆ 84.7064            ┆ 2.9131       ┆ 12.3805     │
└───────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴────────────────────┴──────────────┴─────────────┘

shape: (3, 60)
┌───────────┬───────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ labels_km ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_hie ┆ pct_alipha ┆ pct_aroma ┆ pct_acycl │
│ ---       ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ r          ┆ tic_ring   ┆ tic       ┆ ic        │
│ u64       ┆ u32   ┆ ---        ┆ f64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆       ┆ f64        ┆           ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞═══════════╪═══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0         ┆ 1360  ┆ 2.158816   ┆ 17.573529 ┆ … ┆ 0.038235   ┆ 96.838235  ┆ 2.426471  ┆ 0.735294  │
│ 1         ┆ 1443  ┆ 1.89637    ┆ 15.550243 ┆ … ┆ 0.149688   ┆ 30.35343   ┆ 53.014553 ┆ 16.632017 │
│ 2         ┆ 2197  ┆ 2.158494   ┆ 19.938553 ┆ … ┆ 0.0        ┆ 84.706418  ┆ 2.913063  ┆ 12.380519 │
└───────────┴───────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

# Spectral

In [29]:
model_spectral = SpectralClustering(
                n_clusters=3,
                affinity="precomputed",
                assign_labels='kmeans',
                random_state=42,
            )

labels_spectral = model_spectral.fit_predict(dist_matrix)
df = df.with_columns(labels_spectral=labels_spectral)

In [30]:
create_chemiscope_viewer(df, dist_matrix, labels_spectral, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [33]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="transformer",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_spectral,
    clustering_method="spectral"
)

2026-04-21 11:23:09.020 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/transformer/pca_spectral_projection.png

{'coords': array([[  2.3214721 , -58.46608817],
        [ 44.20252122,  61.41668055],
        [ 72.14163397, -58.30720516],
        ...,
        [  7.31243128,  30.99989679],
        [ 15.32269402, -18.02808763],
        [ 15.34732849, -44.20419622]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/transformer/pca_spectral_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/transformer'),
 'clustering_method': 'spectral'}

In [35]:
average_numeric_by_cluster(df, "labels_spectral")

shape: (3, 61)
┌─────────────────┬───────┬─────────────────────┬───────────┬────────────┬────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────┬────────────────────┬──────────────┬─────────────┐
│ labels_spectral ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp   ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---             ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---    ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---                ┆ ---          ┆ ---         │
│ i32             ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64    ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64                ┆ f64          ┆ f64         │
╞═════════════════╪═══════╪═════════════════════╪═══════════╪════════════╪════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════╪════════════════════╪══════════════╪═════════════╡
│ 0               ┆ 4998  ┆ 2.0829              ┆ 18.0278   ┆ 122.7921   ┆ 0.0966 ┆ 36.7703 ┆ 0.8552            ┆ 12.8549             ┆ 8.7855          ┆ 1.6409    ┆ 0.1811             ┆ 2.0604       ┆ 2.3051              ┆ 0.0646        ┆ 0.2359        ┆ 0.6996        ┆ 0.9182        ┆ 2.0244           ┆ 6.5088          ┆ 0.4244         ┆ 1.3231          ┆ 4.5744          ┆ 6.3527            ┆ 37.8657         ┆ 1.2625          ┆ 0.0030     ┆ 0.3379     ┆ 0.0336    ┆ 0.1305   ┆ 0.1265   ┆ 0.0018             ┆ 0.0394   ┆ 0.1228    ┆ 0.5204   ┆ 0.0030   ┆ 2.4636     ┆ 2.6930 ┆ 75.1649 ┆ -6.5362 ┆ 0.3016  ┆ 6.8377 ┆ 1191.5418 ┆ 4.0574 ┆ -11180.2445 ┆ -11180.0131 ┆ -11179.9875 ┆ -11181.1547 ┆ 31.6641 ┆ -76.1153 ┆ -76.5788 ┆ -77.0164 ┆ -70.8393 ┆ 3.4054 ┆ 1.4013 ┆ 1.1174 ┆ 0.0536      ┆ 1.1671    ┆ 72.3489            ┆ 17.2269      ┆ 10.4242     │
│ 1               ┆ 1     ┆ 2.1000              ┆ 20.0000   ┆ 125.0000   ┆ 1.0000 ┆ 40.0000 ┆ 0.8596            ┆ 12.8278             ┆ 9.0000          ┆ 0.0000    ┆ 0.0000             ┆ 1.9000       ┆ 5.0000              ┆ 0.1429        ┆ 0.1429        ┆ 0.7143        ┆ 0.0000        ┆ 2.0000           ┆ 6.0000          ┆ 1.0000         ┆ 1.0000          ┆ 5.0000          ┆ 7.0000            ┆ 42.0000         ┆ 1.2456          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 2.0000     ┆ 2.6910 ┆ 81.3900 ┆ -6.9906 ┆ -0.8299 ┆ 6.1579 ┆ 2057.5288 ┆ 4.5825 ┆ -10971.1348 ┆ -10970.8438 ┆ -10970.8184 ┆ -10972.1602 ┆ 36.3020 ┆ -84.4343 ┆ -84.9145 ┆ -85.4029 ┆ -78.6845 ┆ 4.5021 ┆ 0.5523 ┆ 0.5140 ┆ 0.0000      ┆ 2.0000    ┆ 0.0000             ┆ 0.0000       ┆ 100.0000    │
│ 2               ┆ 1     ┆ 2.0476              ┆ 21.0000   ┆ 124.0000   ┆ 1.0000 ┆ 28.0000 ┆ 0.7183            ┆ 12.9082             ┆ 9.0000          ┆ 1.0000    ┆ 1.0000             ┆ 2.0000       ┆ 4.0000              ┆ 0.0000        ┆ 0.4286        ┆ 0.5714        ┆ 1.0000        ┆ 1.0000           ┆ 8.0000          ┆ 0.0000         ┆ 3.0000          ┆ 4.0000          ┆ 7.0000            ┆ 43.0000         ┆ 1.2394          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 2.0000     ┆ 3.7011 ┆ 85.0500 ┆ -5.8096 ┆ 0.9252  ┆ 6.7375 ┆ 1478.9646 ┆ 5.0015 ┆ -10430.7354 ┆ -10430.4834 ┆ -10430.4580 ┆ -10431.6807 ┆ 34.4560 ┆ -87.7309 ┆ -88.2884 ┆ -88.8025 ┆ -81.6086 ┆ 4.0422 ┆ 0.9026 ┆ 0.8134 ┆ 0.0000      ┆ 2.0000    ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
└─────────────────┴───────┴─────────────────────┴───────────┴────────────┴────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴───────────┴────────────────────┴──────────────┴─────────────┘

shape: (3, 61)
┌────────────┬───────┬────────────┬───────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ labels_spe ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_km ┆ pct_alipha ┆ pct_aroma ┆ pct_acycl │
│ ctral      ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ---       ┆ tic_ring   ┆ tic       ┆ ic        │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ f64       ┆ ---        ┆ ---       ┆ ---       │
│ i32        ┆       ┆ f64        ┆           ┆   ┆           ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 4998  ┆ 2.082936   ┆ 18.027811 ┆ … ┆ 1.167067  ┆ 72.34894   ┆ 17.226891 ┆ 10.42417  │
│ 1          ┆ 1     ┆ 2.1        ┆ 20.0      ┆ … ┆ 2.0       ┆ 0.0        ┆ 0.0       ┆ 100.0     │
│ 2          ┆ 1     ┆ 2.047619   ┆ 21.0      ┆ … ┆ 2.0       ┆ 0.0        ┆ 100.0     ┆ 0.0       │
└────────────┴───────┴────────────┴───────────┴───┴───────────┴────────────┴───────────┴───────────┘

# DBSCAN

In [40]:
model_db = DBSCAN(
    eps=2,
    min_samples=3,
    metric='precomputed',
)

labels_db = model_db.fit_predict(dist_matrix)
df = df.with_columns(labels_db=labels_db)
print(np.unique(labels_db,return_counts=True))

(array([-1,  0,  1,  2]), array([  49, 4945,    3,    3]))

In [41]:
create_chemiscope_viewer(df, dist_matrix, labels_db, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [44]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="transformer",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="qm9",
    labels=labels_db,
    clustering_method="dbscan"
)

2026-04-21 11:33:20.092 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/qm9/clustering/euclidean/transformer/pca_dbscan_projection.png

{'coords': array([[  2.3214721 , -58.46608817],
        [ 44.20252122,  61.41668055],
        [ 72.14163397, -58.30720516],
        ...,
        [  7.31243128,  30.99989679],
        [ 15.32269402, -18.02808763],
        [ 15.34732849, -44.20419622]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/qm9/clustering/euclidean/transformer/pca_dbscan_projection.png'),
 'output_dir': PosixPath('figures/qm9/clustering/euclidean/transformer'),
 'clustering_method': 'dbscan'}

In [43]:
average_numeric_by_cluster(df, "labels_db")

shape: (4, 62)
┌───────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────┬─────────────────┬────────────────────┬──────────────┬─────────────┐
│ labels_db ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ labels_spectral ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---       ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---             ┆ ---                ┆ ---          ┆ ---         │
│ i64       ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64             ┆ f64                ┆ f64          ┆ f64         │
╞═══════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════╪═════════════════╪════════════════════╪══════════════╪═════════════╡
│ -1        ┆ 49    ┆ 1.9654              ┆ 13.7551   ┆ 117.3469   ┆ -0.3878 ┆ 53.2857 ┆ 0.5891            ┆ 13.0064             ┆ 8.5102          ┆ 1.8163    ┆ 0.3673             ┆ 2.0962       ┆ 0.9796              ┆ 0.1202        ┆ 0.4587        ┆ 0.4211        ┆ 1.1020        ┆ 2.4694           ┆ 5.3673          ┆ 0.6735         ┆ 1.8367          ┆ 2.4694          ┆ 5.7347            ┆ 27.5510         ┆ 1.2746          ┆ 0.0204     ┆ 0.1020     ┆ 0.1020    ┆ 0.1633   ┆ 0.0612   ┆ 0.0000             ┆ 0.0000   ┆ 0.0816    ┆ 0.1633   ┆ 0.0000   ┆ 3.5306     ┆ 3.4128 ┆ 67.0851 ┆ -6.8272 ┆ -0.5729 ┆ 6.2543 ┆ 947.9605  ┆ 2.7694 ┆ -11130.0956 ┆ -11129.9029 ┆ -11129.8772 ┆ -11130.9544 ┆ 26.5027 ┆ -60.6057 ┆ -60.9433 ┆ -61.2711 ┆ -56.5314 ┆ 3.7726 ┆ 1.8066 ┆ 1.3313 ┆ 0.9388      ┆ 0.4082    ┆ 0.0000          ┆ 67.3469            ┆ 28.5714      ┆ 4.0816      │
│ 0         ┆ 4945  ┆ 2.0844              ┆ 18.0726   ┆ 122.8467   ┆ 0.1009  ┆ 36.6089 ┆ 0.8578            ┆ 12.8535             ┆ 8.7881          ┆ 1.6394    ┆ 0.1784             ┆ 2.0601       ┆ 2.3201              ┆ 0.0640        ┆ 0.2330        ┆ 0.7030        ┆ 0.9159        ┆ 2.0200           ┆ 6.5195          ┆ 0.4220         ┆ 1.3132          ┆ 4.5998          ┆ 6.3587            ┆ 37.9784         ┆ 1.2624          ┆ 0.0028     ┆ 0.3399     ┆ 0.0330    ┆ 0.1302   ┆ 0.1272   ┆ 0.0018             ┆ 0.0398   ┆ 0.1234    ┆ 0.5244   ┆ 0.0030   ┆ 2.4530     ┆ 2.6865 ┆ 75.2425 ┆ -6.5344 ┆ 0.3107  ┆ 6.8451 ┆ 1194.2221 ┆ 4.0709 ┆ -11180.5694 ┆ -11180.3376 ┆ -11180.3120 ┆ -11181.4802 ┆ 31.7184 ┆ -76.2757 ┆ -76.7404 ┆ -77.1792 ┆ -70.9871 ┆ 3.4025 ┆ 1.3969 ┆ 1.1152 ┆ 0.0425      ┆ 1.1763    ┆ 0.0006          ┆ 72.4570            ┆ 17.0273      ┆ 10.5157     │
│ 1         ┆ 3     ┆ 1.8453              ┆ 17.3333   ┆ 119.6667   ┆ 1.3333  ┆ 23.6667 ┆ 0.7600            ┆ 12.7009             ┆ 9.0000          ┆ 1.0000    ┆ 1.0000             ┆ 2.0000       ┆ 0.0000              ┆ 0.0000        ┆ 1.0000        ┆ 0.0000        ┆ 1.0000        ┆ 0.6667           ┆ 8.3333          ┆ 0.0000         ┆ 7.3333          ┆ 0.0000          ┆ 6.0000            ┆ 32.0000         ┆ 1.2390          ┆ 0.0000     ┆ 0.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 1.6667     ┆ 2.0326 ┆ 89.0933 ┆ -5.3969 ┆ -0.9651 ┆ 4.4309 ┆ 1050.3665 ┆ 3.8740 ┆ -10217.5534 ┆ -10217.3493 ┆ -10217.3239 ┆ -10218.4157 ┆ 29.7550 ┆ -76.2769 ┆ -76.7413 ┆ -77.1610 ┆ -71.1391 ┆ 2.5159 ┆ 1.8219 ┆ 1.1564 ┆ 2.0000      ┆ 0.0000    ┆ 0.0000          ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
│ 2         ┆ 3     ┆ 1.8162              ┆ 16.3333   ┆ 126.0000   ┆ 0.3333  ┆ 44.3333 ┆ 0.9517            ┆ 12.7806             ┆ 9.0000          ┆ 1.0000    ┆ 1.0000             ┆ 2.0000       ┆ 3.0000              ┆ 0.0952        ┆ 0.6127        ┆ 0.2921        ┆ 1.3333        ┆ 3.0000           ┆ 6.0000          ┆ 0.6667         ┆ 3.6667          ┆ 1.6667          ┆ 7.3333            ┆ 29.6667         ┆ 1.2448          ┆ 0.0000     ┆ 1.0000     ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 0.0000             ┆ 0.0000   ┆ 0.0000    ┆ 0.0000   ┆ 0.0000   ┆ 3.0000     ┆ 2.6392 ┆ 70.6733 ┆ -5.7870 ┆ 0.5832  ┆ 6.3711 ┆ 1277.5474 ┆ 3.4959 ┆ -12106.9320 ┆ -12106.7048 ┆ -12106.6794 ┆ -12107.8509 ┆ 30.8307 ┆ -71.6294 ┆ -72.0317 ┆ -72.4257 ┆ -66.8251 ┆ 3.6195 ┆ 1.0828 ┆ 0.8844 ┆ 2.0000      ┆ 0.0000    ┆ 0.0000          ┆ 0.0000             ┆ 100.0000     ┆ 0.0000      │
└───────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴───────────┴─────────────────┴────────────────────┴──────────────┴─────────────┘

shape: (4, 62)
┌───────────┬───────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ labels_db ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_spe ┆ pct_alipha ┆ pct_aroma ┆ pct_acycl │
│ ---       ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ctral      ┆ tic_ring   ┆ tic       ┆ ic        │
│ i64       ┆ u32   ┆ ---        ┆ f64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│           ┆       ┆ f64        ┆           ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞═══════════╪═══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ -1        ┆ 49    ┆ 1.965449   ┆ 13.755102 ┆ … ┆ 0.0        ┆ 67.346939  ┆ 28.571429 ┆ 4.081633  │
│ 0         ┆ 4945  ┆ 2.084403   ┆ 18.072599 ┆ … ┆ 0.000607   ┆ 72.457027  ┆ 17.0273   ┆ 10.515672 │
│ 1         ┆ 3     ┆ 1.845316   ┆ 17.333333 ┆ … ┆ 0.0        ┆ 0.0        ┆ 100.0     ┆ 0.0       │
│ 2         ┆ 3     ┆ 1.816176   ┆ 16.333333 ┆ … ┆ 0.0        ┆ 0.0        ┆ 100.0     ┆ 0.0       │
└───────────┴───────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

# KMeans on Raw Embeddings

In [47]:
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

X_raw = np.array(df["selfies_transformer"].to_list(), dtype=np.float32)
pca = PCA(n_components=4)
X_pca = pca.fit_transform(X_raw)

kmeans_raw = KMeans(n_clusters=3, random_state=42, n_init=10)
labels_kmeans_raw = kmeans_raw.fit_predict(X_pca)
df = df.with_columns(labels_kmeans_raw=labels_kmeans_raw)

In [48]:
average_numeric_by_cluster(df, "labels_kmeans_raw")

shape: (3, 63)
┌───────────────────┬───────┬─────────────────────┬───────────┬────────────┬─────────┬─────────┬───────────────────┬─────────────────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬────────────────┬─────────────────┬─────────────────┬───────────────────┬─────────────────┬─────────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬────────────────────┬──────────┬───────────┬──────────┬──────────┬────────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬────────┬────────┬────────┬─────────────┬───────────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────┐
│ labels_kmeans_raw ┆ count ┆ token_to_atom_ratio ┆ num_atoms ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_affinity ┆ ionization_energies ┆ num_heavy_atoms ┆ num_rings ┆ num_aromatic_rings ┆ coordination ┆ num_rotatable_bonds ┆ fraction_csp1 ┆ fraction_csp2 ┆ fraction_csp3 ┆ h_bond_donors ┆ h_bond_acceptors ┆ branching_index ┆ num_sp_carbons ┆ num_sp2_carbons ┆ num_sp3_carbons ┆ main_chain_length ┆ raw_token_count ┆ avg_bond_length ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxylic_acid ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ fr_halogen ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A      ┆ B      ┆ C      ┆ labels_hier ┆ labels_km ┆ labels_spectral ┆ labels_db ┆ pct_aliphatic_ring ┆ pct_aromatic ┆ pct_acyclic │
│ ---               ┆ ---   ┆ ---                 ┆ ---       ┆ ---        ┆ ---     ┆ ---     ┆ ---               ┆ ---                 ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---                 ┆ ---           ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---            ┆ ---             ┆ ---             ┆ ---               ┆ ---             ┆ ---             ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ---                ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---        ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---         ┆ ---       ┆ ---             ┆ ---       ┆ ---                ┆ ---          ┆ ---         │
│ i32               ┆ u32   ┆ f64                 ┆ f64       ┆ f64        ┆ f64     ┆ f64     ┆ f64               ┆ f64                 ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64                 ┆ f64           ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64            ┆ f64             ┆ f64             ┆ f64               ┆ f64             ┆ f64             ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ f64                ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64        ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64    ┆ f64    ┆ f64    ┆ f64         ┆ f64       ┆ f64             ┆ f64       ┆ f64                ┆ f64          ┆ f64         │
╞═══════════════════╪═══════╪═════════════════════╪═══════════╪════════════╪═════════╪═════════╪═══════════════════╪═════════════════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪══════════════════╪═════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════════════╪═════════════════╪═════════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪════════════════════╪══════════╪═══════════╪══════════╪══════════╪════════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪════════╪════════╪════════╪═════════════╪═══════════╪═════════════════╪═══════════╪════════════════════╪══════════════╪═════════════╡
│ 0                 ┆ 1121  ┆ 1.8533              ┆ 14.9581   ┆ 121.5691   ┆ -0.0277 ┆ 55.0696 ┆ 0.7199            ┆ 12.9530             ┆ 8.7074          ┆ 0.9884    ┆ 0.6137             ┆ 1.9991       ┆ 2.0981              ┆ 0.1008        ┆ 0.5644        ┆ 0.3348        ┆ 1.0990        ┆ 2.9063           ┆ 5.4246          ┆ 0.5995         ┆ 2.7502          ┆ 1.7529          ┆ 6.4130            ┆ 27.8992         ┆ 1.2586          ┆ 0.0062     ┆ 0.1971     ┆ 0.1347    ┆ 0.2756   ┆ 0.1873   ┆ 0.0009             ┆ 0.0562   ┆ 0.0874    ┆ 0.3622   ┆ 0.0134   ┆ 3.6048     ┆ 3.2354 ┆ 70.1887 ┆ -6.4894 ┆ -0.6810 ┆ 5.8084 ┆ 1169.8788 ┆ 3.1014 ┆ -11707.6138 ┆ -11707.3921 ┆ -11707.3664 ┆ -11708.5205 ┆ 29.3431 ┆ -65.5249 ┆ -65.8796 ┆ -66.2383 ┆ -61.1289 ┆ 3.9406 ┆ 1.4002 ┆ 1.0312 ┆ 0.2230      ┆ 0.9866    ┆ 0.0000          ┆ -0.0143   ┆ 25.6913            ┆ 57.4487      ┆ 16.8599     │
│ 1                 ┆ 2483  ┆ 2.1385              ┆ 19.5215   ┆ 123.8474   ┆ 0.2759  ┆ 31.3347 ┆ 0.8878            ┆ 12.8498             ┆ 8.8244          ┆ 1.3713    ┆ 0.0785             ┆ 2.0324       ┆ 2.8304              ┆ 0.0555        ┆ 0.1661        ┆ 0.7783        ┆ 0.7825        ┆ 1.7471           ┆ 6.8264          ┆ 0.3870         ┆ 1.0757          ┆ 5.2348          ┆ 6.5091            ┆ 41.8518         ┆ 1.2559          ┆ 0.0032     ┆ 0.3186     ┆ 0.0064    ┆ 0.1108   ┆ 0.1450   ┆ 0.0028             ┆ 0.0366   ┆ 0.1502    ┆ 0.5167   ┆ 0.0000   ┆ 2.1269     ┆ 2.6255 ┆ 78.2055 ┆ -6.5736 ┆ 0.4892  ┆ 7.0628 ┆ 1280.0387 ┆ 4.5104 ┆ -11041.5726 ┆ -11041.3247 ┆ -11041.2991 ┆ -11042.5034 ┆ 33.6685 ┆ -81.2675 ┆ -81.7721 ┆ -82.2481 ┆ -75.5793 ┆ 3.2455 ┆ 1.2840 ┆ 1.0405 ┆ 0.0000      ┆ 1.8296    ┆ 0.0012          ┆ -0.0020   ┆ 79.0979            ┆ 7.8534       ┆ 13.0487     │
│ 2                 ┆ 1396  ┆ 2.1685              ┆ 17.8395   ┆ 121.8997   ┆ -0.1211 ┆ 31.7400 ┆ 0.9057            ┆ 12.7851             ┆ 8.7794          ┆ 2.6426    ┆ 0.0165             ┆ 2.1592       ┆ 1.5401              ┆ 0.0516        ┆ 0.0962        ┆ 0.8523        ┆ 1.0136        ┆ 1.8087           ┆ 6.8152          ┆ 0.3503         ┆ 0.6182          ┆ 5.6655          ┆ 6.0272            ┆ 38.7858         ┆ 1.2773          ┆ 0.0000     ┆ 0.4850     ┆ 0.0007    ┆ 0.0487   ┆ 0.0444   ┆ 0.0007             ┆ 0.0308   ┆ 0.1024    ┆ 0.6533   ┆ 0.0000   ┆ 2.1454     ┆ 2.3780 ┆ 73.7641 ┆ -6.5070 ┆ 0.7564  ┆ 7.2634 ┆ 1052.3581 ┆ 4.0202 ┆ -11002.7251 ┆ -11002.5152 ┆ -11002.4895 ┆ -11003.6013 ┆ 29.9680 ┆ -75.4699 ┆ -75.9476 ┆ -76.3804 ┆ -70.2193 ┆ 3.2611 ┆ 1.6098 ┆ 1.3228 ┆ 0.0129      ┆ 0.1347    ┆ 0.0000          ┆ -0.0136   ┆ 97.7077            ┆ 1.6476       ┆ 0.6447      │
└───────────────────┴───────┴─────────────────────┴───────────┴────────────┴─────────┴─────────┴───────────────────┴─────────────────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴──────────────────┴─────────────────┴────────────────┴─────────────────┴─────────────────┴───────────────────┴─────────────────┴─────────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴────────────────────┴──────────┴───────────┴──────────┴──────────┴────────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴────────┴────────┴────────┴─────────────┴───────────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────┘

shape: (3, 63)
┌────────────┬───────┬────────────┬───────────┬───┬───────────┬────────────┬───────────┬───────────┐
│ labels_kme ┆ count ┆ token_to_a ┆ num_atoms ┆ … ┆ labels_db ┆ pct_alipha ┆ pct_aroma ┆ pct_acycl │
│ ans_raw    ┆ ---   ┆ tom_ratio  ┆ ---       ┆   ┆ ---       ┆ tic_ring   ┆ tic       ┆ ic        │
│ ---        ┆ u32   ┆ ---        ┆ f64       ┆   ┆ f64       ┆ ---        ┆ ---       ┆ ---       │
│ i32        ┆       ┆ f64        ┆           ┆   ┆           ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪═══════╪════════════╪═══════════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 1121  ┆ 1.853263   ┆ 14.958073 ┆ … ┆ -0.014273 ┆ 25.691347  ┆ 57.448707 ┆ 16.859946 │
│ 1          ┆ 2483  ┆ 2.138521   ┆ 19.521547 ┆ … ┆ -0.002014 ┆ 79.097865  ┆ 7.853403  ┆ 13.048731 │
│ 2          ┆ 1396  ┆ 2.168486   ┆ 17.839542 ┆ … ┆ -0.01361  ┆ 97.707736  ┆ 1.647564  ┆ 0.644699  │
└────────────┴───────┴────────────┴───────────┴───┴───────────┴────────────┴───────────┴───────────┘

In [32]:

create_chemiscope_viewer(df, X_raw, labels_kmeans_raw, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…