In [1]:
import os
os.chdir('../../..')

In [2]:
import polars as pl

from src.helper_functions import create_chemiscope_viewer, average_numeric_by_cluster
from src.datasets import QM9Dataset
from src.outlier_detection import hdbscan_outliers, ocsvm_outliers, lof_outliers

INFO: Enabling RDKit 2025.09.4 jupyter extensions

In [3]:
descriptor = "soap"
outliers = pl.read_parquet('data/QM9/outliers/synthetic_outliers.parquet')

In [4]:
qm9 = QM9Dataset(limit=5000, 
                 sampling_strategy="stratified",
                 stratify_by=["num_atoms", "gap"], 
                 injected_molecules = outliers,
                 descriptors=[descriptor],
                 )
df = qm9.load()

2026-04-23 16:00:28.963 | INFO     | src.datasets:load:796 - Loading cached full QM9 dataset from: data/QM9/dataset_cleaned.parquet
2026-04-23 16:00:29.162 | INFO     | src.datasets:_sample_qm9_df:998 - QM9 sampling complete: strategy=stratified, requested_limit=5500, returned_rows=5500.
2026-04-23 16:00:31.524 | INFO     | src.datasets:_add_requested_descriptors:188 - Applying requested QM9 descriptors to sampled dataframe (rows=5519).
2026-04-23 16:00:31.847 | INFO     | src.features:compute_soap:176 - Computing SOAP (rcut=6.0, nmax=8, lmax=6)...
2026-04-23 16:01:07.371 | SUCCESS  | src.datasets:add_soap:1150 - Added SOAP embeddings.
2026-04-23 16:01:07.372 | INFO     | src.datasets:_add_requested_descriptors:213 - Added descriptor column(s): ['soap_embedding']
2026-04-23 16:01:07.372 | WARNING  | src.datasets:inject_outliers:779 - Some injected SMILES were skipped because parsing or 3D embedding failed: ['C1#CC#CC#C1']
2026-04-23 16:01:07.372 | INFO     | src.datasets:inject_outliers:784 - Injected custom outliers into QM9 dataframe: requested=20, injected=19, total_rows=5519.
2026-04-23 16:01:07.372 | INFO     | src.datasets:_add_requested_descriptors:188 - Applying requested QM9 descriptors to sampled dataframe (rows=5519).
2026-04-23 16:01:07.376 | INFO     | src.features:compute_soap:176 - Computing SOAP (rcut=6.0, nmax=8, lmax=6)...
2026-04-23 16:01:11.342 | SUCCESS  | src.datasets:add_soap:1150 - Added SOAP embeddings.
2026-04-23 16:01:11.343 | INFO     | src.datasets:_add_requested_descriptors:215 - No new descriptor columns added (already present or none requested).
2026-04-23 16:01:11.379 | INFO     | src.datasets:_drop_rows_with_null_required_descriptors:891 - Dropped QM9 rows with null/empty descriptor vectors: dropped=14, remaining=5505, descriptor_cols=['soap_embedding'].
2026-04-23 16:01:11.385 | INFO     | src.datasets:load:835 - QM9 descriptor null-filtering complete: attempts=1, requested_limit=5000, returned_rows=5019, base_rows=5486.

In [5]:
df.filter(pl.col("is_injected") == 1)

shape: (19, 69)
┌────────────┬───────────┬────────────┬────────────┬───┬──────┬────────────┬───────────┬───────────┐
│ mol_id     ┆ formula   ┆ smiles     ┆ canonical_ ┆ … ┆ C    ┆ is_injecte ┆ outlier_c ┆ soap_embe │
│ ---        ┆ ---       ┆ ---        ┆ smiles     ┆   ┆ ---  ┆ d          ┆ ategory   ┆ dding     │
│ str        ┆ str       ┆ str        ┆ ---        ┆   ┆ f64  ┆ ---        ┆ ---       ┆ ---       │
│            ┆           ┆            ┆ str        ┆   ┆      ┆ i64        ┆ str       ┆ list[f64] │
╞════════════╪═══════════╪════════════╪════════════╪═══╪══════╪════════════╪═══════════╪═══════════╡
│ injected_0 ┆ C12H10    ┆ c1ccccc1-c ┆ [H]c1c([H] ┆ … ┆ null ┆ 1          ┆ size_outl ┆ [0.088123 │
│            ┆           ┆ 2ccccc2    ┆ )c([H])c(- ┆   ┆      ┆            ┆ iers      ┆ ,         │
│            ┆           ┆            ┆ c2c([H])c( ┆   ┆      ┆            ┆           ┆ 0.241011, │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_1 ┆ C9H8O4    ┆ CC(=O)Oc1c ┆ [H]OC(=O)c ┆ … ┆ null ┆ 1          ┆ size_outl ┆ [0.074392 │
│            ┆           ┆ cccc1C(=O) ┆ 1c([H])c([ ┆   ┆      ┆            ┆ iers      ┆ ,         │
│            ┆           ┆ O          ┆ H])c([H])c ┆   ┆      ┆            ┆           ┆ 0.20155,  │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_2 ┆ C13H18O2  ┆ CC(C)Cc1cc ┆ [H]OC(=O)C ┆ … ┆ null ┆ 1          ┆ size_outl ┆ [0.105975 │
│            ┆           ┆ c(cc1)C(C) ┆ ([H])(c1c( ┆   ┆      ┆            ┆ iers      ┆ ,         │
│            ┆           ┆ C(=O)O     ┆ [H])c([H]) ┆   ┆      ┆            ┆           ┆ 0.290581, │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_3 ┆ C10H16    ┆ C1C2CC3CC1 ┆ [H]C1([H]) ┆ … ┆ null ┆ 1          ┆ size_outl ┆ [0.117899 │
│            ┆           ┆ CC(C2)C3   ┆ C2([H])C([ ┆   ┆      ┆            ┆ iers      ┆ ,         │
│            ┆           ┆            ┆ H])([H])C3 ┆   ┆      ┆            ┆           ┆ 0.328894, │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_4 ┆ C9H10N2O4 ┆ O=C1CCC(=O ┆ [H]N1C(=O) ┆ … ┆ null ┆ 1          ┆ size_outl ┆ [0.077527 │
│            ┆           ┆ )N1C2CCC(= ┆ C([H])([H] ┆   ┆      ┆            ┆ iers      ┆ ,         │
│            ┆           ┆ O)NC2=O    ┆ )C([H])([H ┆   ┆      ┆            ┆           ┆ 0.210961, │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ …          ┆ …         ┆ …          ┆ …          ┆ … ┆ …    ┆ …          ┆ …         ┆ …         │
│ injected_1 ┆ H4N2O4    ┆ ON(O)N(O)O ┆ [H]ON(O[H] ┆ … ┆ null ┆ 1          ┆ topology_ ┆ [0.082997 │
│ 4          ┆           ┆            ┆ )N(O[H])O[ ┆   ┆      ┆            ┆ outliers  ┆ ,         │
│            ┆           ┆            ┆ H]         ┆   ┆      ┆            ┆           ┆ 0.231989, │
│            ┆           ┆            ┆            ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_1 ┆ C8H10N4O2 ┆ CN1C=NC2=C ┆ [H]c1nc2c( ┆ … ┆ null ┆ 1          ┆ extreme_o ┆ [0.080487 │
│ 5          ┆           ┆ 1C(=O)N(C( ┆ c(=O)n(C([ ┆   ┆      ┆            ┆ utliers   ┆ ,         │
│            ┆           ┆ =O)N2C)C   ┆ H])([H])[H ┆   ┆      ┆            ┆           ┆ 0.214278, │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_1 ┆ C6H7NO2S  ┆ C1=CC=C(C= ┆ [H]c1c([H] ┆ … ┆ null ┆ 1          ┆ extreme_o ┆ [0.081521 │
│ 6          ┆           ┆ C1)S(=O)(= ┆ )c([H])c(S ┆   ┆      ┆            ┆ utliers   ┆ ,         │
│            ┆           ┆ O)N        ┆ (=O)(=O)N( ┆   ┆      ┆            ┆           ┆ 0.222566, │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_1 ┆ C3H7NO2   ┆ NC(C)C(=O) ┆ [H]OC(=O)C ┆ … ┆ null ┆ 1          ┆ extreme_o ┆ [0.105577 │
│ 7          ┆           ┆ O          ┆ ([H])(N([H ┆   ┆      ┆            ┆ utliers   ┆ ,         │
│            ┆           ┆            ┆ ])[H])C([H ┆   ┆      ┆            ┆           ┆ 0.294946, │
│            ┆           ┆            ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
│ injected_1 ┆ C18H15P   ┆ C1=CC=C(C= ┆ [H]c1c([H] ┆ … ┆ null ┆ 1          ┆ extreme_o ┆ [0.085777 │
│ 8          ┆           ┆ C1)P(C2=CC ┆ )c([H])c(P ┆   ┆      ┆            ┆ utliers   ┆ ,         │
│            ┆           ┆ =CC=C2)C3= ┆ (c2c([H])c ┆   ┆      ┆            ┆           ┆ 0.235783, │
│            ┆           ┆ …          ┆ …          ┆   ┆      ┆            ┆           ┆ … 0.0]    │
└────────────┴───────────┴────────────┴────────────┴───┴──────┴────────────┴───────────┴───────────┘

In [6]:
if descriptor == "soap":
    dist_matrix = qm9.get_distance_matrix(descriptor, "soap_kernel",force_calculate=True)
else:
    dist_matrix = qm9.get_distance_matrix(descriptor, "euclidean",force_calculate=True)

2026-04-23 16:01:11.414 | INFO     | src.datasets:get_distance_matrix:1342 - Calculating distance matrix for soap using soap_kernel distance.
2026-04-23 16:01:12.860 | SUCCESS  | src.distance:_compute_and_save:74 - Saved distance matrix to data/QM9/dist_soap_soap_kernel.npy

In [7]:
df = hdbscan_outliers(df, dist_matrix)
df = ocsvm_outliers(df, dist_matrix)
df = lof_outliers(df, dist_matrix)

/Users/karlfindhansen/thesis/Anomaly-Detection-in-Molecular-and-Materials-Datasets/.venv/lib/python3.12/site-packages/sklearn/cluster/_hdbscan/hdbscan.py:722: FutureWarning: The default value of `copy` will change from False to True in 1.10. Explicitly set a value for `copy` to silence this warning.
  warn(

HDBSCAN — 6 distinct: -1: 2929, 0: 204, 1: 336, 2: 1148, 3: 191, 4: 211
OCSVM — 2 distinct: -1: 502, 1: 4517
LOF — 2 distinct: -1: 33, 1: 4986

In [8]:
df = df.with_columns([
    (pl.col("hdbscan_labels") == -1).cast(pl.Int8).alias("is_outlier_hdbscan"),
    (pl.col("ocsvm_label") == -1).cast(pl.Int8).alias("is_outlier_ocsvm"),
    (pl.col("lof_label") == -1).cast(pl.Int8).alias("is_outlier_lof"),
])

# 2. Create a "consensus score" (0 to 3)
df = df.with_columns(
    (pl.col("is_outlier_hdbscan") + 
        pl.col("is_outlier_ocsvm") + 
        pl.col("is_outlier_lof")).alias("outlier_votes")
)

# 3. Analyze the overlap
vote_counts = df["outlier_votes"].value_counts().sort("outlier_votes")
print("\n--- Outlier Consensus Summary ---")
print(vote_counts)

# 4. Extract the exact overlapping groups
overlap_all_three = df.filter(pl.col("outlier_votes") == 3)
overlap_at_least_two = df.filter(pl.col("outlier_votes") >= 2)

df = df.with_row_index("original_index")
consensus_indices = df.filter(pl.col("outlier_votes") == 3)["original_index"].to_list()

--- Outlier Consensus Summary ---
shape: (4, 2)
┌───────────────┬───────┐
│ outlier_votes ┆ count │
│ ---           ┆ ---   │
│ i8            ┆ u32   │
╞═══════════════╪═══════╡
│ 0             ┆ 1933  │
│ 1             ┆ 2736  │
│ 2             ┆ 322   │
│ 3             ┆ 28    │
└───────────────┴───────┘

In [9]:
create_chemiscope_viewer(df, dist_matrix, df["outlier_votes"].to_numpy(), 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: qm9_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show qm9_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'QM9 - PCA Clustering'}, settings={'map': {'x': {'property': 'PCA_1'}, 'y': {'…

In [10]:
average_numeric_by_cluster(df, "outlier_votes")

shape: (4, 80)
┌─────────────┬───────┬─────────────┬─────────────┬────────────┬─────────┬─────────┬─────────────┬─────────────┬─────────────┬───────────┬─────────────┬─────────────┬─────────────┬───────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬───────────┬──────────┬──────────┬─────────────┬──────────┬───────────┬──────────┬──────────┬────────┬─────────┬─────────┬─────────┬────────┬───────────┬────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────┬──────────┬──────────┬──────────┬──────────┬─────────┬────────┬────────┬─────────────┬─────────────┬────────────┬────────────┬───────────┬───────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ outlier_vot ┆ count ┆ token_to_at ┆ original_in ┆ mol_weight ┆ logp    ┆ tpsa    ┆ election_af ┆ ionization_ ┆ num_heavy_a ┆ num_rings ┆ num_aromati ┆ num_fluorin ┆ num_heteroa ┆ num_atoms ┆ coordinatio ┆ num_rotatab ┆ fraction_cs ┆ fraction_cs ┆ fraction_cs ┆ h_bond_dono ┆ h_bond_acce ┆ branching_i ┆ num_sp_carb ┆ num_sp2_car ┆ num_sp3_car ┆ main_chain_ ┆ raw_token_c ┆ avg_bond_le ┆ fr_benzene ┆ fr_alcohol ┆ fr_phenol ┆ fr_amine ┆ fr_amide ┆ fr_carboxyl ┆ fr_ester ┆ fr_ketone ┆ fr_ether ┆ fr_nitro ┆ mu     ┆ alpha   ┆ homo    ┆ lumo    ┆ gap    ┆ r2        ┆ zpve   ┆ u0          ┆ u           ┆ h           ┆ g           ┆ cv      ┆ u0_atom  ┆ u_atom   ┆ h_atom   ┆ g_atom   ┆ A       ┆ B      ┆ C      ┆ is_injected ┆ hdbscan_lab ┆ ocsvm_labe ┆ ocsvm_scor ┆ lof_label ┆ lof_score ┆ is_outlier ┆ is_outlier ┆ is_outlier ┆ pct_alipha ┆ pct_aromat ┆ pct_acycli ┆ avg_len_se ┆ unique_sca ┆ top_scaffo ┆ top_scaffo ┆ unique_gen ┆ top_generi ┆ top_generi ┆ unique_out ┆ top_outlie ┆ top_outlie │
│ es          ┆ ---   ┆ om_ratio    ┆ dex         ┆ ---        ┆ ---     ┆ ---     ┆ finity      ┆ energies    ┆ toms        ┆ ---       ┆ c_rings     ┆ e           ┆ toms        ┆ ---       ┆ n           ┆ le_bonds    ┆ p1          ┆ p2          ┆ p3          ┆ rs          ┆ ptors       ┆ ndex        ┆ ons         ┆ bons        ┆ bons        ┆ length      ┆ ount        ┆ ngth        ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ ic_acid     ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---    ┆ ---       ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---     ┆ ---    ┆ ---    ┆ ---         ┆ els         ┆ l          ┆ e          ┆ ---       ┆ ---       ┆ _hdbscan   ┆ _ocsvm     ┆ _lof       ┆ tic_ring   ┆ ic         ┆ c          ┆ lfies      ┆ ffolds     ┆ ld         ┆ ld_pct     ┆ eric_scaff ┆ c_scaffold ┆ c_scaffold ┆ lier_categ ┆ r_category ┆ r_category │
│ ---         ┆ u32   ┆ ---         ┆ ---         ┆ f64        ┆ f64     ┆ f64     ┆ ---         ┆ ---         ┆ ---         ┆ f64       ┆ ---         ┆ ---         ┆ ---         ┆ f64       ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ f64        ┆ f64        ┆ f64       ┆ f64      ┆ f64      ┆ ---         ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64    ┆ f64       ┆ f64    ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64     ┆ f64    ┆ f64    ┆ f64         ┆ ---         ┆ ---        ┆ ---        ┆ f64       ┆ f32       ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ olds       ┆ ---        ┆ _pct       ┆ ories      ┆ ---        ┆ _pct       │
│ i8          ┆       ┆ f64         ┆ f64         ┆            ┆         ┆         ┆ f64         ┆ f64         ┆ f64         ┆           ┆ f64         ┆ f64         ┆ f64         ┆           ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆            ┆            ┆           ┆          ┆          ┆ f64         ┆          ┆           ┆          ┆          ┆        ┆         ┆         ┆         ┆        ┆           ┆        ┆             ┆             ┆             ┆             ┆         ┆          ┆          ┆          ┆          ┆         ┆        ┆        ┆             ┆ f64         ┆ f64        ┆ f64        ┆           ┆           ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ u32        ┆ str        ┆ f64        ┆ ---        ┆ str        ┆ ---        ┆ ---        ┆ str        ┆ ---        │
│             ┆       ┆             ┆             ┆            ┆         ┆         ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆            ┆            ┆           ┆          ┆          ┆             ┆          ┆           ┆          ┆          ┆        ┆         ┆         ┆         ┆        ┆           ┆        ┆             ┆             ┆             ┆             ┆         ┆          ┆          ┆          ┆          ┆         ┆        ┆        ┆             ┆             ┆            ┆            ┆           ┆           ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆ u32        ┆            ┆ f64        ┆ u32        ┆            ┆ f64        │
╞═════════════╪═══════╪═════════════╪═════════════╪════════════╪═════════╪═════════╪═════════════╪═════════════╪═════════════╪═══════════╪═════════════╪═════════════╪═════════════╪═══════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╪═════════════╪══════════╪═══════════╪══════════╪══════════╪════════╪═════════╪═════════╪═════════╪════════╪═══════════╪════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════╪══════════╪══════════╪══════════╪══════════╪═════════╪════════╪════════╪═════════════╪═════════════╪════════════╪════════════╪═══════════╪═══════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 0           ┆ 1933  ┆ 2.1522      ┆ 3130.3451   ┆ 125.4035   ┆ 0.1340  ┆ 29.1304 ┆ 0.9038      ┆ 12.8263     ┆ 8.9540      ┆ 2.0062    ┆ 0.0103      ┆ 0.0000      ┆ 1.9933      ┆ 20.2478   ┆ 2.0891      ┆ 2.4252      ┆ 0.0268      ┆ 0.1135      ┆ 0.8597      ┆ 0.8996      ┆ 1.6296      ┆ 7.2773      ┆ 0.1862      ┆ 0.7770      ┆ 5.9974      ┆ 6.3280      ┆ 43.6425     ┆ 1.2638      ┆ 0.0000     ┆ 0.4149     ┆ 0.0021    ┆ 0.0693   ┆ 0.1061   ┆ 0.0016      ┆ 0.0171   ┆ 0.1112    ┆ 0.5717   ┆ 0.0000   ┆ 2.4350 ┆ 78.7881 ┆ -6.4840 ┆ 0.8048  ┆ 7.2888 ┆ 1206.4479 ┆ 4.6270 ┆ -11106.5094 ┆ -11106.2720 ┆ -11106.2463 ┆ -11107.4212 ┆ 33.2235 ┆ -82.7259 ┆ -83.2555 ┆ -83.7414 ┆ -76.8961 ┆ 2.9754  ┆ 1.3648 ┆ 1.1187 ┆ 0.0000      ┆ 1.9405      ┆ 1.0000     ┆ 11.9288    ┆ 1.0000    ┆ 1.0343    ┆ 0.0000     ┆ 0.0000     ┆ 0.0000     ┆ 94.3611    ┆ 1.0347     ┆ 4.6042     ┆ 43.6425    ┆ 832        ┆ Acyclic    ┆ 4.6042     ┆ 228        ┆ C1CC1      ┆ 8.3290     ┆ 1          ┆ null       ┆ 0.0000     │
│ 1           ┆ 2736  ┆ 2.0288      ┆ 2179.2752   ┆ 121.2551   ┆ 0.0629  ┆ 38.4974 ┆ 0.8703      ┆ 12.8298     ┆ 8.6904      ┆ 1.4978    ┆ 0.1418      ┆ 0.0011      ┆ 2.4656      ┆ 17.7537   ┆ 2.0490      ┆ 2.2895      ┆ 0.0927      ┆ 0.2317      ┆ 0.6756      ┆ 0.9349      ┆ 2.0753      ┆ 6.2171      ┆ 0.6107      ┆ 1.3600      ┆ 4.2540      ┆ 6.3651      ┆ 36.2295     ┆ 1.2615      ┆ 0.0029     ┆ 0.3512     ┆ 0.0318    ┆ 0.1626   ┆ 0.1499   ┆ 0.0029      ┆ 0.0515   ┆ 0.1462    ┆ 0.5534   ┆ 0.0000   ┆ 2.7831 ┆ 74.1205 ┆ -6.5546 ┆ 0.1862  ┆ 6.7409 ┆ 1185.6985 ┆ 3.9013 ┆ -11097.0531 ┆ -11096.8213 ┆ -11096.7956 ┆ -11097.9658 ┆ 31.4172 ┆ -74.3825 ┆ -74.8254 ┆ -75.2496 ┆ -69.2702 ┆ 3.4694  ┆ 1.4064 ┆ 1.1198 ┆ 0.0004      ┆ -0.8337     ┆ 0.8852     ┆ 11.6706    ┆ 1.0000    ┆ 1.0754    ┆ 0.9426     ┆ 0.0574     ┆ 0.0000     ┆ 72.1126    ┆ 13.9985    ┆ 13.8889    ┆ 36.2295    ┆ 827        ┆ Acyclic    ┆ 13.8889    ┆ 222        ┆ Acyclic    ┆ 13.8889    ┆ 2          ┆ extreme_ou ┆ 0.0365     │
│             ┆       ┆             ┆             ┆            ┆         ┆         ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆            ┆            ┆           ┆          ┆          ┆             ┆          ┆           ┆          ┆          ┆        ┆         ┆         ┆         ┆        ┆           ┆        ┆             ┆             ┆             ┆             ┆         ┆          ┆          ┆          ┆          ┆         ┆        ┆        ┆             ┆             ┆            ┆            ┆           ┆           ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆ tliers     ┆            │
│ 2           ┆ 322   ┆ 1.8222      ┆ 1558.3944   ┆ 118.5963   ┆ -0.1211 ┆ 52.8230 ┆ 0.7539      ┆ 12.8901     ┆ 8.5093      ┆ 1.0839    ┆ 0.4814      ┆ 0.0155      ┆ 3.3540      ┆ 14.7950   ┆ 2.0065      ┆ 1.7516      ┆ 0.1326      ┆ 0.4959      ┆ 0.3714      ┆ 1.0093      ┆ 2.8199      ┆ 5.0994      ┆ 0.7919      ┆ 2.2733      ┆ 2.0901      ┆ 6.2391      ┆ 27.5901     ┆ 1.2618      ┆ 0.0093     ┆ 0.2888     ┆ 0.0807    ┆ 0.2640   ┆ 0.1366   ┆ 0.0062      ┆ 0.0994   ┆ 0.1491    ┆ 0.3758   ┆ 0.0000   ┆ 3.1610 ┆ 68.4658 ┆ -6.6955 ┆ -0.6718 ┆ 6.0236 ┆ 1112.4319 ┆ 2.9826 ┆ -11306.7753 ┆ -11306.5615 ┆ -11306.5359 ┆ -11307.6692 ┆ 28.3313 ┆ -63.6470 ┆ -63.9903 ┆ -64.3361 ┆ -59.4147 ┆ 4.4589  ┆ 1.5160 ┆ 1.1529 ┆ 0.0155      ┆ -1.0000     ┆ -0.9689    ┆ -15.7863   ┆ 0.9689    ┆ 1.1550    ┆ 1.0000     ┆ 0.9845     ┆ 0.0155     ┆ 33.5404    ┆ 44.4099    ┆ 22.0497    ┆ 27.5901    ┆ 154        ┆ Acyclic    ┆ 22.0497    ┆ 55         ┆ C1CCCC1    ┆ 26.0870    ┆ 4          ┆ extreme_ou ┆ 0.6211     │
│             ┆       ┆             ┆             ┆            ┆         ┆         ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆            ┆            ┆           ┆          ┆          ┆             ┆          ┆           ┆          ┆          ┆        ┆         ┆         ┆         ┆        ┆           ┆        ┆             ┆             ┆             ┆             ┆         ┆          ┆          ┆          ┆          ┆         ┆        ┆        ┆             ┆             ┆            ┆            ┆           ┆           ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆ tliers     ┆            │
│ 3           ┆ 28    ┆ 1.7992      ┆ 2764.7857   ┆ 113.8214   ┆ 0.4643  ┆ 32.0714 ┆ 0.9702      ┆ 13.0100     ┆ 7.3214      ┆ 0.9286    ┆ 0.4643      ┆ 0.5357      ┆ 2.8214      ┆ 12.7143   ┆ 1.9332      ┆ 1.2857      ┆ 0.1190      ┆ 0.3919      ┆ 0.4177      ┆ 0.5714      ┆ 1.8929      ┆ 4.5357      ┆ 0.4643      ┆ 2.3214      ┆ 1.7143      ┆ 5.0357      ┆ 24.1429     ┆ 1.2897      ┆ 0.2143     ┆ 0.1071     ┆ 0.0357    ┆ 0.1071   ┆ 0.0000   ┆ 0.0714      ┆ 0.0357   ┆ 0.0357    ┆ 0.0714   ┆ 0.0357   ┆ 3.0596 ┆ 50.6553 ┆ -7.2435 ┆ -0.6748 ┆ 6.5688 ┆ 782.8830  ┆ 2.1877 ┆ -11034.2540 ┆ -11034.0748 ┆ -11034.0493 ┆ -11035.0969 ┆ 23.0099 ┆ -49.1013 ┆ -49.3615 ┆ -49.6288 ┆ -45.8394 ┆ 11.8795 ┆ 2.2280 ┆ 1.8530 ┆ 0.4643      ┆ -1.0000     ┆ -1.0000    ┆ -72.6406   ┆ -1.0000   ┆ 2.1775    ┆ 1.0000     ┆ 1.0000     ┆ 1.0000     ┆ 21.4286    ┆ 35.7143    ┆ 42.8571    ┆ 24.1429    ┆ 17         ┆ Acyclic    ┆ 42.8571    ┆ 11         ┆ Acyclic    ┆ 42.8571    ┆ 5          ┆ element_ou ┆ 17.8571    │
│             ┆       ┆             ┆             ┆            ┆         ┆         ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆           ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆            ┆            ┆           ┆          ┆          ┆             ┆          ┆           ┆          ┆          ┆        ┆         ┆         ┆         ┆        ┆           ┆        ┆             ┆             ┆             ┆             ┆         ┆          ┆          ┆          ┆          ┆         ┆        ┆        ┆             ┆             ┆            ┆            ┆           ┆           ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆            ┆ tliers     ┆            │
└─────────────┴───────┴─────────────┴─────────────┴────────────┴─────────┴─────────┴─────────────┴─────────────┴─────────────┴───────────┴─────────────┴─────────────┴─────────────┴───────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴───────────┴──────────┴──────────┴─────────────┴──────────┴───────────┴──────────┴──────────┴────────┴─────────┴─────────┴─────────┴────────┴───────────┴────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────┴──────────┴──────────┴──────────┴──────────┴─────────┴────────┴────────┴─────────────┴─────────────┴────────────┴────────────┴───────────┴───────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

shape: (4, 80)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ outlier_vo ┆ count ┆ token_to_a ┆ original_i ┆ … ┆ top_gener ┆ unique_ou ┆ top_outli ┆ top_outli │
│ tes        ┆ ---   ┆ tom_ratio  ┆ ndex       ┆   ┆ ic_scaffo ┆ tlier_cat ┆ er_catego ┆ er_catego │
│ ---        ┆ u32   ┆ ---        ┆ ---        ┆   ┆ ld_pct    ┆ egories   ┆ ry        ┆ ry_pct    │
│ i8         ┆       ┆ f64        ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆       ┆            ┆            ┆   ┆ f64       ┆ u32       ┆ str       ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 1933  ┆ 2.152199   ┆ 3130.34505 ┆ … ┆ 8.329022  ┆ 1         ┆ null      ┆ 0.0       │
│            ┆       ┆            ┆ 9          ┆   ┆           ┆           ┆           ┆           │
│ 1          ┆ 2736  ┆ 2.02875    ┆ 2179.27521 ┆ … ┆ 13.888889 ┆ 2         ┆ extreme_o ┆ 0.03655   │
│            ┆       ┆            ┆ 9          ┆   ┆           ┆           ┆ utliers   ┆           │
│ 2          ┆ 322   ┆ 1.822156   ┆ 1558.39441 ┆ … ┆ 26.086957 ┆ 4         ┆ extreme_o ┆ 0.621118  │
│            ┆       ┆            ┆            ┆   ┆           ┆           ┆ utliers   ┆           │
│ 3          ┆ 28    ┆ 1.799181   ┆ 2764.78571 ┆ … ┆ 42.857143 ┆ 5         ┆ element_o ┆ 17.857143 │
│            ┆       ┆            ┆ 4          ┆   ┆           ┆           ┆ utliers   ┆           │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘