In [1]:
import os
os.chdir('../../../../..')

In [2]:
from src.datasets import MaterialsProject

In [3]:
import numpy as np
import polars as pl

from sklearn.cluster import AgglomerativeClustering, SpectralClustering, DBSCAN, KMeans
from kmedoids import KMedoids

from src.helper_functions import create_chemiscope_viewer, plot_distance_matrix_projection, evaluate_distance_matrix_clustering_sweep, average_numeric_by_cluster

In [4]:
mp = MaterialsProject(limit=5000, sampling_strategy="stratified", stratify_on=["band_gap", "energy_above_hull"], add_coulomb=True)
df = mp.load()

2026-04-21 14:18:00.067 | INFO     | src.datasets:load:1322 - Loading full cached Parquet data from data/Materials Project/materials.parquet...
2026-04-21 14:18:00.971 | INFO     | src.datasets:_add_descriptors:1671 - Ignoring output_tag=sample_n6000_seed40_stratified since descriptors are attached directly to dataframe.
2026-04-21 14:18:00.972 | INFO     | src.datasets:_add_descriptors:1705 - Calculating max atoms for Coulomb Matrix padding...
2026-04-21 14:18:01.256 | INFO     | src.datasets:_add_descriptors:1752 - Computing Coulomb Matrix chunk 0 (0 to 1000)...
2026-04-21 14:18:01.763 | INFO     | src.datasets:_add_descriptors:1752 - Computing Coulomb Matrix chunk 1 (1000 to 2000)...
2026-04-21 14:18:02.258 | INFO     | src.datasets:_add_descriptors:1752 - Computing Coulomb Matrix chunk 2 (2000 to 3000)...
2026-04-21 14:18:02.796 | INFO     | src.datasets:_add_descriptors:1752 - Computing Coulomb Matrix chunk 3 (3000 to 4000)...
2026-04-21 14:18:03.676 | INFO     | src.datasets:_add_descriptors:1752 - Computing Coulomb Matrix chunk 4 (4000 to 5000)...
2026-04-21 14:18:04.362 | INFO     | src.datasets:_add_descriptors:1752 - Computing Coulomb Matrix chunk 5 (5000 to 6000)...
2026-04-21 14:18:06.392 | SUCCESS  | src.datasets:_add_descriptors:1777 - All requested descriptors successfully added to dataframe.
2026-04-21 14:18:06.883 | INFO     | src.datasets:_drop_rows_with_null_required_descriptors:1292 - Dropped 254 materials due to failed descriptor calculations. Remaining valid candidates: 5746
2026-04-21 14:18:06.884 | SUCCESS  | src.datasets:load:1362 - Successfully reached requested limit of 5000 valid rows (Attempt 1).

In [5]:
dist_matrix = mp.get_distance_matrix(
    descriptor="coulomb",
    dist_type="euclidean",
    pca_variance=95,
    force_calculate=True,
)

2026-04-21 14:18:06.891 | INFO     | src.datasets:get_distance_matrix:1933 - Applying PCA to retain 95.00% of variance.
2026-04-21 14:18:42.414 | INFO     | src.datasets:get_distance_matrix:1942 - PCA reduced 'coulomb_matrix' dimensions from 10000 to 10
2026-04-21 14:18:42.433 | INFO     | src.datasets:get_distance_matrix:1953 - Calculating distance matrix for coulomb_matrix using euclidean distance.
2026-04-21 14:18:42.584 | SUCCESS  | src.distance:_compute_and_save:79 - Saved distance matrix to data/Materials Project/dist_coulomb_matrix_euclidean_pca0.95.npy

# Hierarchical Clustering on Distance Matrix

In [6]:
model_hier = AgglomerativeClustering(metric='precomputed', n_clusters=3, linkage='complete')
labels_hier = model_hier.fit_predict(dist_matrix)
print(np.unique(labels_hier, return_counts=True))
df = df.with_columns(labels_hier=labels_hier)

(array([0, 1, 2]), array([ 132,    3, 4865]))

In [7]:
average_numeric_by_cluster(df, "labels_hier")

shape: (3, 19)
┌─────────────┬───────┬─────────────┬─────────────────┬───────────────────────────┬──────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────────┬───────────┬───────────────────┬─────────────────┬─────────────────┬───────────┐
│ labels_hier ┆ count ┆ max_en_diff ┆ energy_per_atom ┆ formation_energy_per_atom ┆ band_gap ┆ density ┆ a       ┆ b       ┆ c       ┆ alpha   ┆ beta    ┆ gamma   ┆ volume    ┆ num_sites ┆ energy_above_hull ┆ avg_bond_length ┆ max_bond_length ┆ pct_metal │
│ ---         ┆ ---   ┆ ---         ┆ ---             ┆ ---                       ┆ ---      ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---       ┆ ---       ┆ ---               ┆ ---             ┆ ---             ┆ ---       │
│ i64         ┆ u32   ┆ f64         ┆ f64             ┆ f64                       ┆ f64      ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64       ┆ f64       ┆ f64               ┆ f64             ┆ f64             ┆ f64       │
╞═════════════╪═══════╪═════════════╪═════════════════╪═══════════════════════════╪══════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═══════════╪═══════════╪═══════════════════╪═════════════════╪═════════════════╪═══════════╡
│ 0           ┆ 132   ┆ 1.1562      ┆ -27.4551        ┆ -0.8830                   ┆ 0.2373   ┆ 10.7486 ┆ 8.6028  ┆ 9.2212  ┆ 11.8250 ┆ 88.7500 ┆ 88.8573 ┆ 93.7359 ┆ 787.1553  ┆ 36.5682   ┆ 0.0328            ┆ 2.6014          ┆ 2.7736          ┆ 74.2424   │
│ 1           ┆ 3     ┆ 1.0767      ┆ -6.9775         ┆ -1.0415                   ┆ 0.0000   ┆ 14.4713 ┆ 10.5482 ┆ 10.7723 ┆ 16.1856 ┆ 80.0000 ┆ 80.1754 ┆ 90.0000 ┆ 1223.3538 ┆ 73.3333   ┆ 0.0166            ┆ 2.4479          ┆ 2.5563          ┆ 100.0000  │
│ 2           ┆ 4865  ┆ 1.6060      ┆ -13.0491        ┆ -1.3130                   ┆ 0.6723   ┆ 6.0776  ┆ 6.6454  ┆ 7.0811  ┆ 9.0429  ┆ 86.0359 ┆ 86.7377 ┆ 88.5444 ┆ 367.3871  ┆ 21.9786   ┆ 0.0831            ┆ 2.2895          ┆ 2.5725          ┆ 58.2323   │
└─────────────┴───────┴─────────────┴─────────────────┴───────────────────────────┴──────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────────┴───────────┴───────────────────┴─────────────────┴─────────────────┴───────────┘

shape: (3, 19)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ labels_hie ┆ count ┆ max_en_dif ┆ energy_per ┆ … ┆ energy_ab ┆ avg_bond_ ┆ max_bond_ ┆ pct_metal │
│ r          ┆ ---   ┆ f          ┆ _atom      ┆   ┆ ove_hull  ┆ length    ┆ length    ┆ ---       │
│ ---        ┆ u32   ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│ i64        ┆       ┆ f64        ┆ f64        ┆   ┆ f64       ┆ f64       ┆ f64       ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 132   ┆ 1.156212   ┆ -27.455127 ┆ … ┆ 0.032775  ┆ 2.60136   ┆ 2.77358   ┆ 74.242424 │
│ 1          ┆ 3     ┆ 1.076667   ┆ -6.977507  ┆ … ┆ 0.016619  ┆ 2.447902  ┆ 2.556311  ┆ 100.0     │
│ 2          ┆ 4865  ┆ 1.605998   ┆ -13.049132 ┆ … ┆ 0.08313   ┆ 2.289464  ┆ 2.572538  ┆ 58.232271 │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="coulomb",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="materials_project",
    labels=labels_hier,
    clustering_method="hierarchical"
)

2026-04-21 14:18:43.643 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/materials_project/clustering/euclidean/coulomb/pca_hierarchical_projection.png

{'coords': array([[2697726.16495534,  775134.52071925],
        [  39375.95691272, -340167.10652317],
        [-608319.89685587,  343663.50306851],
        ...,
        [-345752.62596215, -178330.17083463],
        [2206619.52091025,  397226.89582632],
        [-142499.22178026,  -89199.2631573 ]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/materials_project/clustering/euclidean/coulomb/pca_hierarchical_projection.png'),
 'output_dir': PosixPath('figures/materials_project/clustering/euclidean/coulomb'),
 'clustering_method': 'hierarchical'}

In [9]:
create_chemiscope_viewer(df, dist_matrix, labels_hier, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: materials_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show materials_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'Materials Project - PCA Clustering'}, settings={'map': {'x': {'property': 'PC…

# KMedoids

In [10]:
model_km = KMedoids(n_clusters=3, metric="precomputed")
labels_km = model_km.fit_predict(dist_matrix)
print(np.unique(labels_km, return_counts=True))
df = df.with_columns(labels_km=labels_km)

(array([0, 1, 2], dtype=uint64), array([1431, 1366, 2203]))

In [11]:
average_numeric_by_cluster(df, "labels_km")

shape: (3, 20)
┌───────────┬───────┬─────────────┬─────────────────┬───────────────────────────┬──────────┬─────────┬────────┬────────┬─────────┬─────────┬─────────┬─────────┬──────────┬───────────┬───────────────────┬─────────────────┬─────────────────┬─────────────┬───────────┐
│ labels_km ┆ count ┆ max_en_diff ┆ energy_per_atom ┆ formation_energy_per_atom ┆ band_gap ┆ density ┆ a      ┆ b      ┆ c       ┆ alpha   ┆ beta    ┆ gamma   ┆ volume   ┆ num_sites ┆ energy_above_hull ┆ avg_bond_length ┆ max_bond_length ┆ labels_hier ┆ pct_metal │
│ ---       ┆ ---   ┆ ---         ┆ ---             ┆ ---                       ┆ ---      ┆ ---     ┆ ---    ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---      ┆ ---       ┆ ---               ┆ ---             ┆ ---             ┆ ---         ┆ ---       │
│ u64       ┆ u32   ┆ f64         ┆ f64             ┆ f64                       ┆ f64      ┆ f64     ┆ f64    ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64      ┆ f64       ┆ f64               ┆ f64             ┆ f64             ┆ f64         ┆ f64       │
╞═══════════╪═══════╪═════════════╪═════════════════╪═══════════════════════════╪══════════╪═════════╪════════╪════════╪═════════╪═════════╪═════════╪═════════╪══════════╪═══════════╪═══════════════════╪═════════════════╪═════════════════╪═════════════╪═══════════╡
│ 0         ┆ 1431  ┆ 1.5055      ┆ -14.5663        ┆ -1.2269                   ┆ 0.5291   ┆ 6.9568  ┆ 6.0767 ┆ 6.2985 ┆ 8.2092  ┆ 84.6219 ┆ 84.8379 ┆ 85.5341 ┆ 245.7298 ┆ 13.3746   ┆ 0.0815            ┆ 2.4343          ┆ 2.7009          ┆ 2.0000      ┆ 67.3655   │
│ 1         ┆ 1366  ┆ 1.3662      ┆ -20.6859        ┆ -1.1207                   ┆ 0.4926   ┆ 8.5749  ┆ 7.5040 ┆ 8.1294 ┆ 10.2389 ┆ 88.0335 ┆ 88.5614 ┆ 93.6980 ┆ 519.2220 ┆ 25.2350   ┆ 0.0379            ┆ 2.5064          ┆ 2.7475          ┆ 1.8045      ┆ 67.2035   │
│ 2         ┆ 2203  ┆ 1.7923      ┆ -8.1833         ┆ -1.4621                   ┆ 0.8498   ┆ 4.2493  ┆ 6.6051 ┆ 7.0727 ┆ 9.0192  ┆ 85.8700 ┆ 86.9590 ┆ 87.6172 ┆ 378.5820 ┆ 26.4925   ┆ 0.1091            ┆ 2.0798          ┆ 2.3927          ┆ 2.0000      ┆ 47.7531   │
└───────────┴───────┴─────────────┴─────────────────┴───────────────────────────┴──────────┴─────────┴────────┴────────┴─────────┴─────────┴─────────┴─────────┴──────────┴───────────┴───────────────────┴─────────────────┴─────────────────┴─────────────┴───────────┘

shape: (3, 20)
┌───────────┬───────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ labels_km ┆ count ┆ max_en_dif ┆ energy_per ┆ … ┆ avg_bond_l ┆ max_bond_ ┆ labels_hi ┆ pct_metal │
│ ---       ┆ ---   ┆ f          ┆ _atom      ┆   ┆ ength      ┆ length    ┆ er        ┆ ---       │
│ u64       ┆ u32   ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ f64       │
│           ┆       ┆ f64        ┆ f64        ┆   ┆ f64        ┆ f64       ┆ f64       ┆           │
╞═══════════╪═══════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0         ┆ 1431  ┆ 1.505486   ┆ -14.566277 ┆ … ┆ 2.43425    ┆ 2.700912  ┆ 2.0       ┆ 67.365479 │
│ 1         ┆ 1366  ┆ 1.366223   ┆ -20.685859 ┆ … ┆ 2.506357   ┆ 2.747485  ┆ 1.804539  ┆ 67.203514 │
│ 2         ┆ 2203  ┆ 1.792292   ┆ -8.183299  ┆ … ┆ 2.079832   ┆ 2.392697  ┆ 2.0       ┆ 47.753064 │
└───────────┴───────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [12]:
create_chemiscope_viewer(df, dist_matrix, labels_km, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: materials_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show materials_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'Materials Project - PCA Clustering'}, settings={'map': {'x': {'property': 'PC…

In [13]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="coulomb",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="materials_project",
    labels=labels_km,
    clustering_method="kmedoids"
)

2026-04-21 14:18:48.866 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/materials_project/clustering/euclidean/coulomb/pca_kmedoids_projection.png

{'coords': array([[2697726.16495534,  775134.52071925],
        [  39375.95691272, -340167.10652317],
        [-608319.89685587,  343663.50306851],
        ...,
        [-345752.62596215, -178330.17083463],
        [2206619.52091025,  397226.89582632],
        [-142499.22178026,  -89199.2631573 ]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/materials_project/clustering/euclidean/coulomb/pca_kmedoids_projection.png'),
 'output_dir': PosixPath('figures/materials_project/clustering/euclidean/coulomb'),
 'clustering_method': 'kmedoids'}

# Spectral

In [14]:
model_spectral = SpectralClustering(
                n_clusters=3,
                affinity="precomputed",
                assign_labels='kmeans',
                random_state=42,
            )

labels_spectral = model_spectral.fit_predict(dist_matrix)
df = df.with_columns(labels_spectral=labels_spectral)

KeyboardInterrupt:

In [ ]:
create_chemiscope_viewer(df, dist_matrix, labels_spectral, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: materials_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show materials_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'Materials Project - PCA Clustering'}, settings={'map': {'x': {'property': 'PC…

In [ ]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="coulomb",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="materials_project",
    labels=labels_spectral,
    clustering_method="spectral"
)

NameError: name 'labels_spectral' is not defined

In [ ]:
average_numeric_by_cluster(df, "labels_spectral")

shape: (3, 20)
┌─────────────────┬───────┬─────────────┬─────────────────┬───────────────────────────┬──────────┬─────────┬────────┬────────┬────────┬─────────┬─────────┬──────────┬──────────┬───────────┬───────────────────┬─────────────────┬─────────────────┬─────────────┬───────────┐
│ labels_spectral ┆ count ┆ max_en_diff ┆ energy_per_atom ┆ formation_energy_per_atom ┆ band_gap ┆ density ┆ a      ┆ b      ┆ c      ┆ alpha   ┆ beta    ┆ gamma    ┆ volume   ┆ num_sites ┆ energy_above_hull ┆ avg_bond_length ┆ max_bond_length ┆ labels_hier ┆ labels_km │
│ ---             ┆ ---   ┆ ---         ┆ ---             ┆ ---                       ┆ ---      ┆ ---     ┆ ---    ┆ ---    ┆ ---    ┆ ---     ┆ ---     ┆ ---      ┆ ---      ┆ ---       ┆ ---               ┆ ---             ┆ ---             ┆ ---         ┆ ---       │
│ i32             ┆ u32   ┆ f64         ┆ f64             ┆ f64                       ┆ f64      ┆ f64     ┆ f64    ┆ f64    ┆ f64    ┆ f64     ┆ f64     ┆ f64      ┆ f64      ┆ f64       ┆ f64               ┆ f64             ┆ f64             ┆ f64         ┆ f64       │
╞═════════════════╪═══════╪═════════════╪═════════════════╪═══════════════════════════╪══════════╪═════════╪════════╪════════╪════════╪═════════╪═════════╪══════════╪══════════╪═══════════╪═══════════════════╪═════════════════╪═════════════════╪═════════════╪═══════════╡
│ 0               ┆ 4998  ┆ 1.5940      ┆ -13.4284        ┆ -1.3013                   ┆ 0.6596   ┆ 6.2064  ┆ 6.7005 ┆ 7.1407 ┆ 9.1223 ┆ 86.1023 ┆ 86.7884 ┆ 88.6787  ┆ 379.0941 ┆ 22.3994   ┆ 0.0818            ┆ 2.2981          ┆ 2.5781          ┆ 1.8828      ┆ 1.9114    │
│ 1               ┆ 1     ┆ 2.0800      ┆ -9.5985         ┆ -3.2911                   ┆ 0.0000   ┆ 9.7003  ┆ 3.7659 ┆ 3.7659 ┆ 3.7659 ┆ 90.0000 ┆ 90.0000 ┆ 90.0000  ┆ 53.4060  ┆ 5.0000    ┆ 0.0428            ┆ 2.0389          ┆ 2.6629          ┆ 2.0000      ┆ 3.0000    │
│ 2               ┆ 1     ┆ 0.1600      ┆ -4.4729         ┆ -0.0449                   ┆ 5.3252   ┆ 0.6246  ┆ 4.2906 ┆ 5.7465 ┆ 6.1891 ┆ 90.0000 ┆ 90.0000 ┆ 105.3753 ┆ 147.1344 ┆ 16.0000   ┆ 0.0122            ┆ 1.2204          ┆ 1.3151          ┆ 2.0000      ┆ 2.0000    │
└─────────────────┴───────┴─────────────┴─────────────────┴───────────────────────────┴──────────┴─────────┴────────┴────────┴────────┴─────────┴─────────┴──────────┴──────────┴───────────┴───────────────────┴─────────────────┴─────────────────┴─────────────┴───────────┘

# DBSCAN

In [ ]:
model_db = DBSCAN(
    eps=7500,
    min_samples=5,
    metric='precomputed',
)

labels_db = model_db.fit_predict(dist_matrix)
df = df.with_columns(labels_db=labels_db)
print(np.unique(labels_db,return_counts=True))

(array([-1,  0,  1,  2,  3,  4,  5]), array([ 172, 4756,   42,    7,    6,    8,    9]))

In [ ]:
create_chemiscope_viewer(df, dist_matrix, labels_db, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: materials_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show materials_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'Materials Project - PCA Clustering'}, settings={'map': {'x': {'property': 'PC…

In [ ]:
plot_distance_matrix_projection(
    dist_matrix=dist_matrix,
    fingerprint="coulomb",
    distance_metric="euclidean",
    projection_method="PCA",
    dataset_name="materials_project",
    labels=labels_db,
    clustering_method="dbscan"
)

2026-04-19 14:06:06.701 | SUCCESS  | src.helper_functions:plot_distance_matrix_projection:385 - Saved PCA projection plot to figures/materials_project/clustering/euclidean/coulomb/pca_dbscan_projection.png

{'coords': array([[2800442.63967447,  756369.6823298 ],
        [  48568.4980794 , -326827.80857034],
        [-609746.51810078,  345730.93704956],
        ...,
        [-355393.16155332, -171267.3980381 ],
        [2286565.81470132,  396153.62667518],
        [-157155.44091623,  -94446.57618272]], shape=(5000, 2)),
 'figure_path': PosixPath('figures/materials_project/clustering/euclidean/coulomb/pca_dbscan_projection.png'),
 'output_dir': PosixPath('figures/materials_project/clustering/euclidean/coulomb'),
 'clustering_method': 'dbscan'}

In [ ]:
average_numeric_by_cluster(df, "labels_db")

shape: (11, 22)
┌───────────┬───────┬─────────────┬─────────────────┬───────────────────────────┬──────────┬─────────┬─────────┬─────────┬─────────┬─────────┬──────────┬──────────┬──────────┬───────────┬───────────────────┬─────────────────┬─────────────────┬─────────────┬───────────┬─────────────────┬───────────────────┐
│ labels_db ┆ count ┆ max_en_diff ┆ energy_per_atom ┆ formation_energy_per_atom ┆ band_gap ┆ density ┆ a       ┆ b       ┆ c       ┆ alpha   ┆ beta     ┆ gamma    ┆ volume   ┆ num_sites ┆ energy_above_hull ┆ avg_bond_length ┆ max_bond_length ┆ labels_hier ┆ labels_km ┆ labels_spectral ┆ labels_kmeans_raw │
│ ---       ┆ ---   ┆ ---         ┆ ---             ┆ ---                       ┆ ---      ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---      ┆ ---      ┆ ---      ┆ ---       ┆ ---               ┆ ---             ┆ ---             ┆ ---         ┆ ---       ┆ ---             ┆ ---               │
│ i64       ┆ u32   ┆ f64         ┆ f64             ┆ f64                       ┆ f64      ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64      ┆ f64      ┆ f64      ┆ f64       ┆ f64               ┆ f64             ┆ f64             ┆ f64         ┆ f64       ┆ f64             ┆ f64               │
╞═══════════╪═══════╪═════════════╪═════════════════╪═══════════════════════════╪══════════╪═════════╪═════════╪═════════╪═════════╪═════════╪══════════╪══════════╪══════════╪═══════════╪═══════════════════╪═════════════════╪═════════════════╪═════════════╪═══════════╪═════════════════╪═══════════════════╡
│ -1        ┆ 610   ┆ 1.2345      ┆ -23.4882        ┆ -0.9199                   ┆ 0.3342   ┆ 9.2076  ┆ 8.4298  ┆ 8.9931  ┆ 11.2546 ┆ 88.7897 ┆ 88.8769  ┆ 93.6281  ┆ 697.9752 ┆ 31.2574   ┆ 0.0306            ┆ 2.6048          ┆ 2.8013          ┆ 1.0246      ┆ 1.9197    ┆ 0.0000          ┆ 0.0754            │
│ 0         ┆ 4315  ┆ 1.6517      ┆ -11.8241        ┆ -1.3630                   ┆ 0.7112   ┆ 5.7307  ┆ 6.4449  ┆ 6.8648  ┆ 8.8216  ┆ 85.7236 ┆ 86.4724  ┆ 87.8598  ┆ 332.7563 ┆ 21.1242   ┆ 0.0899            ┆ 2.2515          ┆ 2.5439          ┆ 1.9995      ┆ 0.7390    ┆ 0.0007          ┆ 0.8846            │
│ 1         ┆ 18    ┆ 1.5483      ┆ -14.7658        ┆ -1.1374                   ┆ 0.7275   ┆ 7.0939  ┆ 8.0958  ┆ 8.9344  ┆ 10.0249 ┆ 85.7354 ┆ 89.9692  ┆ 94.5509  ┆ 646.2236 ┆ 35.7222   ┆ 0.1014            ┆ 2.1829          ┆ 2.5520          ┆ 1.6667      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
│ 2         ┆ 9     ┆ 1.1922      ┆ -31.8905        ┆ -0.9316                   ┆ 0.1541   ┆ 12.3876 ┆ 5.7247  ┆ 6.7353  ┆ 7.6857  ┆ 92.4808 ┆ 88.0699  ┆ 108.5437 ┆ 207.6994 ┆ 14.1111   ┆ 0.0000            ┆ 2.3708          ┆ 2.6794          ┆ 2.0000      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
│ 3         ┆ 6     ┆ 1.2017      ┆ -35.3692        ┆ -1.0954                   ┆ 0.3369   ┆ 11.2583 ┆ 6.8242  ┆ 6.8790  ┆ 5.9262  ┆ 84.4333 ┆ 85.5012  ┆ 103.8699 ┆ 250.1248 ┆ 14.8333   ┆ 0.0000            ┆ 2.5657          ┆ 2.7705          ┆ 2.0000      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
│ 4         ┆ 15    ┆ 0.9633      ┆ -24.2356        ┆ -0.7122                   ┆ 0.0326   ┆ 8.9913  ┆ 7.8337  ┆ 8.1160  ┆ 8.3851  ┆ 75.4273 ┆ 75.4193  ┆ 76.1630  ┆ 403.9361 ┆ 24.0000   ┆ 0.0000            ┆ 2.5271          ┆ 2.6866          ┆ 2.0000      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
│ 5         ┆ 6     ┆ 1.1567      ┆ -27.6877        ┆ -0.9969                   ┆ 0.0000   ┆ 11.0140 ┆ 5.7500  ┆ 6.2891  ┆ 10.9905 ┆ 90.0067 ┆ 89.9933  ┆ 121.5594 ┆ 274.0490 ┆ 13.3333   ┆ 0.0008            ┆ 2.7200          ┆ 2.9608          ┆ 0.0000      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
│ 6         ┆ 5     ┆ 0.9700      ┆ -28.5409        ┆ -0.8749                   ┆ 0.0031   ┆ 11.3134 ┆ 6.3666  ┆ 6.9635  ┆ 8.5966  ┆ 98.0580 ┆ 97.2632  ┆ 104.0531 ┆ 306.7260 ┆ 16.8000   ┆ 0.0057            ┆ 2.7255          ┆ 2.8404          ┆ 2.0000      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
│ 7         ┆ 6     ┆ 0.8683      ┆ -17.7552        ┆ -0.5405                   ┆ 0.5178   ┆ 7.9909  ┆ 6.5850  ┆ 7.8830  ┆ 8.6702  ┆ 89.9471 ┆ 90.0153  ┆ 90.0153  ┆ 421.1488 ┆ 15.3333   ┆ 0.0140            ┆ 2.6234          ┆ 2.8333          ┆ 2.0000      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
│ 8         ┆ 5     ┆ 1.3460      ┆ -16.2513        ┆ -0.6237                   ┆ 1.8498   ┆ 5.0739  ┆ 10.4625 ┆ 10.2193 ┆ 11.5700 ┆ 78.5974 ┆ 84.9272  ┆ 99.8675  ┆ 952.5368 ┆ 42.0000   ┆ 0.0929            ┆ 2.3078          ┆ 2.6068          ┆ 2.0000      ┆ 1.8000    ┆ 0.0000          ┆ 0.4000            │
│ 9         ┆ 5     ┆ 1.0180      ┆ -31.0506        ┆ -0.4413                   ┆ 0.0000   ┆ 9.5510  ┆ 6.2750  ┆ 7.2099  ┆ 8.5157  ┆ 96.7965 ┆ 111.6027 ┆ 90.0019  ┆ 355.1526 ┆ 14.0000   ┆ 0.0000            ┆ 2.7712          ┆ 2.8621          ┆ 0.0000      ┆ 2.0000    ┆ 0.0000          ┆ 0.0000            │
└───────────┴───────┴─────────────┴─────────────────┴───────────────────────────┴──────────┴─────────┴─────────┴─────────┴─────────┴─────────┴──────────┴──────────┴──────────┴───────────┴───────────────────┴─────────────────┴─────────────────┴─────────────┴───────────┴─────────────────┴───────────────────┘

# KMeans on Raw Embeddings

In [25]:
from sklearn.decomposition import PCA
X = np.array(df["coulomb_matrix"].to_list(), dtype=np.float32)
pca = PCA(n_components=4)
X = pca.fit_transform(X)

kmeans_raw = KMeans(n_clusters=6, random_state=42, n_init=10)
labels_kmeans_raw = kmeans_raw.fit_predict(X)
df = df.with_columns(labels_kmeans_raw=labels_kmeans_raw)

In [27]:
average_numeric_by_cluster(df, "labels_kmeans_raw")

shape: (6, 21)
┌───────────────────┬───────┬─────────────┬─────────────────┬───────────────────────────┬──────────┬─────────┬────────┬────────┬─────────┬─────────┬─────────┬─────────┬──────────┬───────────┬───────────────────┬─────────────────┬─────────────────┬─────────────┬───────────┬───────────┐
│ labels_kmeans_raw ┆ count ┆ max_en_diff ┆ energy_per_atom ┆ formation_energy_per_atom ┆ band_gap ┆ density ┆ a      ┆ b      ┆ c       ┆ alpha   ┆ beta    ┆ gamma   ┆ volume   ┆ num_sites ┆ energy_above_hull ┆ avg_bond_length ┆ max_bond_length ┆ labels_hier ┆ labels_km ┆ pct_metal │
│ ---               ┆ ---   ┆ ---         ┆ ---             ┆ ---                       ┆ ---      ┆ ---     ┆ ---    ┆ ---    ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---      ┆ ---       ┆ ---               ┆ ---             ┆ ---             ┆ ---         ┆ ---       ┆ ---       │
│ i32               ┆ u32   ┆ f64         ┆ f64             ┆ f64                       ┆ f64      ┆ f64     ┆ f64    ┆ f64    ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64      ┆ f64       ┆ f64               ┆ f64             ┆ f64             ┆ f64         ┆ f64       ┆ f64       │
╞═══════════════════╪═══════╪═════════════╪═════════════════╪═══════════════════════════╪══════════╪═════════╪════════╪════════╪═════════╪═════════╪═════════╪═════════╪══════════╪═══════════╪═══════════════════╪═════════════════╪═════════════════╪═════════════╪═══════════╪═══════════╡
│ 0                 ┆ 1127  ┆ 1.4623      ┆ -15.3580        ┆ -1.1959                   ┆ 0.4817   ┆ 7.2501  ┆ 5.8693 ┆ 6.0618 ┆ 8.0615  ┆ 84.1584 ┆ 84.3053 ┆ 84.5829 ┆ 216.7342 ┆ 11.9725   ┆ 0.0850            ┆ 2.4440          ┆ 2.7033          ┆ 2.0000      ┆ 0.0177    ┆ 70.1863   │
│ 1                 ┆ 315   ┆ 1.2314      ┆ -25.2926        ┆ -0.9641                   ┆ 0.2960   ┆ 9.9335  ┆ 7.5932 ┆ 8.2700 ┆ 9.9930  ┆ 90.6026 ┆ 90.5629 ┆ 93.8243 ┆ 503.4168 ┆ 25.1492   ┆ 0.0331            ┆ 2.5693          ┆ 2.7788          ┆ 1.6952      ┆ 1.0000    ┆ 79.0476   │
│ 2                 ┆ 2248  ┆ 1.8086      ┆ -8.0631         ┆ -1.4816                   ┆ 0.8460   ┆ 4.2521  ┆ 6.4924 ┆ 6.9230 ┆ 8.7888  ┆ 85.8472 ┆ 86.8665 ┆ 87.5408 ┆ 353.1391 ┆ 25.1054   ┆ 0.1111            ┆ 2.0830          ┆ 2.3982          ┆ 2.0000      ┆ 1.8621    ┆ 48.3096   │
│ 3                 ┆ 641   ┆ 1.5493      ┆ -12.7991        ┆ -1.2852                   ┆ 0.7672   ┆ 6.1672  ┆ 8.1181 ┆ 8.9063 ┆ 11.2546 ┆ 88.9921 ┆ 89.9634 ┆ 93.2936 ┆ 655.5995 ┆ 30.8424   ┆ 0.0376            ┆ 2.4629          ┆ 2.7437          ┆ 2.0000      ┆ 0.9282    ┆ 49.7660   │
│ 4                 ┆ 569   ┆ 1.3314      ┆ -22.8040        ┆ -1.0769                   ┆ 0.4434   ┆ 9.0543  ┆ 6.5964 ┆ 7.0332 ┆ 8.9687  ┆ 84.8070 ┆ 85.3634 ┆ 92.5525 ┆ 318.1234 ┆ 17.6309   ┆ 0.0463            ┆ 2.4606          ┆ 2.7013          ┆ 2.0000      ┆ 0.9772    ┆ 72.5835   │
│ 5                 ┆ 100   ┆ 1.1684      ┆ -25.4780        ┆ -0.8879                   ┆ 0.2015   ┆ 10.6607 ┆ 9.3865 ┆ 9.8861 ┆ 12.9523 ┆ 88.4946 ┆ 88.9509 ┆ 92.7668 ┆ 969.6870 ┆ 43.1900   ┆ 0.0245            ┆ 2.6380          ┆ 2.8027          ┆ 0.2900      ┆ 1.0000    ┆ 76.0000   │
└───────────────────┴───────┴─────────────┴─────────────────┴───────────────────────────┴──────────┴─────────┴────────┴────────┴─────────┴─────────┴─────────┴─────────┴──────────┴───────────┴───────────────────┴─────────────────┴─────────────────┴─────────────┴───────────┴───────────┘

shape: (6, 21)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ labels_kme ┆ count ┆ max_en_dif ┆ energy_per ┆ … ┆ max_bond_ ┆ labels_hi ┆ labels_km ┆ pct_metal │
│ ans_raw    ┆ ---   ┆ f          ┆ _atom      ┆   ┆ length    ┆ er        ┆ ---       ┆ ---       │
│ ---        ┆ u32   ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│ i32        ┆       ┆ f64        ┆ f64        ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 1127  ┆ 1.462289   ┆ -15.357988 ┆ … ┆ 2.703292  ┆ 2.0       ┆ 0.017746  ┆ 70.186335 │
│ 1          ┆ 315   ┆ 1.231365   ┆ -25.292602 ┆ … ┆ 2.778839  ┆ 1.695238  ┆ 1.0       ┆ 79.047619 │
│ 2          ┆ 2248  ┆ 1.808581   ┆ -8.06312   ┆ … ┆ 2.39822   ┆ 2.0       ┆ 1.8621    ┆ 48.309609 │
│ 3          ┆ 641   ┆ 1.549251   ┆ -12.799116 ┆ … ┆ 2.743731  ┆ 2.0       ┆ 0.928237  ┆ 49.765991 │
│ 4          ┆ 569   ┆ 1.331371   ┆ -22.804023 ┆ … ┆ 2.701295  ┆ 2.0       ┆ 0.977153  ┆ 72.58348  │
│ 5          ┆ 100   ┆ 1.1684     ┆ -25.477963 ┆ … ┆ 2.8027    ┆ 0.29      ┆ 1.0       ┆ 76.0      │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
create_chemiscope_viewer(df, X, labels_kmeans_raw, 'PCA')

Running PCA dimensionality reduction...
Converting structures/molecules to ASE Atoms for Chemiscope...
Assembling properties for Chemiscope...
Generating Chemiscope widget...
Saved Chemiscope input to: materials_PCA_clustering.json
If the viewer does not open automatically, run `chemiscope show materials_PCA_clustering.json`.

<ChemiscopeWidget(meta={'name': 'Materials Project - PCA Clustering'}, settings={'map': {'x': {'property': 'PC…